//==============================================================================
//
//  This file contains a Javascript/Webassembly/WebAudio export of the Cmajor
//  patch 'WavetableSynth.cmajorpatch'.
//
//  This file was auto-generated by the Cmajor toolkit v1.0.3088
//
//  To use it, import this module into your HTML/Javascript code and call
//  `createAudioWorkletNodePatchConnection()`. The AudioWorkletPatchConnection
//  object that is returned is a PatchConnection with some extra functionality
//  to let you connect it to web audio/MIDI.
//
//  For more details about Cmajor, visit https://cmajor.dev
//
//==============================================================================

import * as helpers from "./cmaj_api/cmaj-audio-worklet-helper.js"


//==============================================================================
/** This exports the patch's manifest, in case a caller needs to find out about its properties.
 */
export const manifest =
{
  "CmajorVersion": 1,
  "ID": "dev.serendiproducts.WavetableSynth",
  "version": "1.0",
  "name": "Wavetable Synth",
  "description": "Wavetable Synthesizer with morphing waveforms",
  "category": "synth",
  "manufacturer": "snp",
  "isInstrument": true,
  "source": [
    "WavetableSynth.cmajor"
  ]
};

/** Returns the patch's output endpoint list */
export function getOutputEndpoints() { return WavetableSynth.prototype.getOutputEndpoints(); }

/** Returns the patch's input endpoint list */
export function getInputEndpoints()  { return WavetableSynth.prototype.getInputEndpoints(); }

//==============================================================================
/**  Creates an audio worklet node for the patch with the given name, attaches it
 *   to the audio context provided, and returns an object containing the node
 *   and a PatchConnection class to control it.
 *
 *   @param {AudioContext} audioContext - a web audio AudioContext object
 *   @param {string} workletName - the name to give the new worklet that is created
 *   @returns {AudioWorkletPatchConnection} an AudioWorkletPatchConnection which has been initialised
 */
export async function createAudioWorkletNodePatchConnection (audioContext, workletName)
{
  const connection = new helpers.AudioWorkletPatchConnection (manifest);

  await connection.initialise ({ CmajorClass: WavetableSynth,
                                 audioContext,
                                 workletName,
                                 hostDescription: "WebAudio" });
  return connection;
}

/***********************************************************************************
 *
 *   A Javascript/Webassembly implementation of the Cmajor processor 'WavetableSynth'.
 *
 *   This class was auto-generated by the Cmajor toolkit.
 *
 *   To use it, construct an instance of this class, and call `initialise()` to
 *   asynchronously prepare it for use. Once initialised, the class provides
 *   appropriate setter/getter methods for reading/writing data to its endpoints,
 *   and an `advance()` method to render the next block.
 *
 *   This roughly mirrors functionality of the cmajor Performer API - see the
 *   C++ API classes and Cmajor docs for more information about how this is used.
 */
class WavetableSynth
{
  /** After constructing one of these objects, call its
   *  initialise() method to prepare it for use.
   */
  constructor()
  {
  }

  //==============================================================================
  /** Prepares this processor for use.
   *
   *  @param {number} sessionID - A unique integer ID which will be used for `processor.session`.
   *  @param {number} frequency - The frequency in Hz that the processor will be expected to run at.
   */
  async initialise (sessionID, frequency)
  {
    if (! ((sessionID ^ 0) > 1))
      throw new Error ("initialise() requires a valid non-zero session ID argument");

    if (! (frequency > 1))
      throw new Error ("initialise() requires a valid frequency argument");

    const isSIMDAvailable = WebAssembly.validate (new Uint8Array([0,97,115,109,1,0,0,0,1,5,1,96,0,1,123,3,2,1,0,10,10,1,8,0,65,0,253,15,253,98,11]));

    if (isSIMDAvailable)
      await this._initialiseInternalSIMD (sessionID, frequency);
    else
      await this._initialiseInternalNonSIMD (sessionID, frequency);

    return true;
  }

  //==============================================================================
  /** Advances the processor by a number of frames.
   *
   *  Before calling `advance()` you should use the appropriate functions to
   *  push data and events into the processor's input endpoints. After calling
   *  `advance()` you can use its output endpoint access functions to read the
   *  results.
   *
   *  @param {number} numFrames - An integer number of frames to advance.
   *                              This must be greater than zero.
   */
  advance (numFrames)
  {
    this._advanceInternal (numFrames);
  }

  //==============================================================================
  /** Returns an object which encapsulates the state of the patch at this point.
   *  The state can be restored by passing this object to `restoreState()`.
   */
  getState()
  {
    return { memory: this.byteMemory.slice(0) };
  }

  /** Restores the patch to a state that was previously saved by a call to `getState()`
   */
  restoreState (savedState)
  {
    if (savedState?.memory && savedState.memory?.length === this.byteMemory.length)
      this.byteMemory.set (savedState.memory);
    else
      throw Error ("restoreState(): not a valid state object");
  }

  /** Returns a list of the output endpoints that this processor exposes.
   *  @returns {Array}
   */
  getOutputEndpoints()
  {
    return [
      {
        "endpointID": "out",
        "endpointType": "stream",
        "dataType": {
          "type": "float32"
        },
        "purpose": "audio out",
        "numAudioChannels": 1
      }
    ];
  }

  /** Returns a list of the input endpoints that this processor exposes.
   *  @returns {Array}
   */
  getInputEndpoints()
  {
    return [
      {
        "endpointID": "midiIn",
        "endpointType": "event",
        "dataType": {
          "type": "object",
          "class": "Message",
          "members": {
            "message": {
              "type": "int32"
            }
          }
        },
        "purpose": "midi in"
      },
      {
        "endpointID": "volume",
        "endpointType": "value",
        "dataType": {
          "type": "float32"
        },
        "annotation": {
          "name": "Master Volume",
          "min": 0.0,
          "max": 1,
          "init": 0.3
        },
        "purpose": "parameter"
      },
      {
        "endpointID": "wavetablePosition",
        "endpointType": "value",
        "dataType": {
          "type": "float32"
        },
        "annotation": {
          "name": "Wavetable Position",
          "min": 0.0,
          "max": 1,
          "init": 0.0,
          "step": 0.01
        },
        "purpose": "parameter"
      },
      {
        "endpointID": "morphSpeed",
        "endpointType": "value",
        "dataType": {
          "type": "float32"
        },
        "annotation": {
          "name": "Morph Speed",
          "min": 0.0,
          "max": 2,
          "init": 0.0,
          "step": 0.01
        },
        "purpose": "parameter"
      },
      {
        "endpointID": "morphDepth",
        "endpointType": "value",
        "dataType": {
          "type": "float32"
        },
        "annotation": {
          "name": "Morph Depth",
          "min": 0.0,
          "max": 1,
          "init": 0.5,
          "step": 0.01
        },
        "purpose": "parameter"
      },
      {
        "endpointID": "attack",
        "endpointType": "value",
        "dataType": {
          "type": "float32"
        },
        "annotation": {
          "name": "Attack",
          "min": 0.0,
          "max": 2,
          "init": 0.1
        },
        "purpose": "parameter"
      },
      {
        "endpointID": "decay",
        "endpointType": "value",
        "dataType": {
          "type": "float32"
        },
        "annotation": {
          "name": "Decay",
          "min": 0.0,
          "max": 2,
          "init": 0.1
        },
        "purpose": "parameter"
      },
      {
        "endpointID": "sustain",
        "endpointType": "value",
        "dataType": {
          "type": "float32"
        },
        "annotation": {
          "name": "Sustain",
          "min": 0.0,
          "max": 1,
          "init": 0.7
        },
        "purpose": "parameter"
      },
      {
        "endpointID": "release",
        "endpointType": "value",
        "dataType": {
          "type": "float32"
        },
        "annotation": {
          "name": "Release",
          "min": 0.0,
          "max": 5,
          "init": 0.3
        },
        "purpose": "parameter"
      }
    ];
  }

  /** Sends an event of type `std::midi::Message` to endpoint "midiIn".
   *  @param {Object} eventValue - The event to be added to the queue for this endpoint.
   */
  sendInputEvent_midiIn (eventValue)
  {
    this._pack_o1_Message_message_i32 (this.scratchSpaceAddress, eventValue);
    this.instance.exports._sendEvent_midiIn (this.stateAddress, this.scratchSpaceAddress);
  }

  /** Sets the value of endpoint "volume".
   *  @param {Object} newValue - The new value, whose type will depend on the endpoint type
   *  @param {number} numFramesToReachValue - If this is non-zero and the type is scalar,
   *                                          this applies a ramp to reach the new value.
  */
  setInputValue_volume (newValue, numFramesToReachValue)
  {
    this._pack_f32 (this.scratchSpaceAddress, newValue);
    this.instance.exports._setValue_volume (this.stateAddress, this.scratchSpaceAddress, numFramesToReachValue);
  }

  /** Sets the value of endpoint "wavetablePosition".
   *  @param {Object} newValue - The new value, whose type will depend on the endpoint type
   *  @param {number} numFramesToReachValue - If this is non-zero and the type is scalar,
   *                                          this applies a ramp to reach the new value.
  */
  setInputValue_wavetablePosition (newValue, numFramesToReachValue)
  {
    this._pack_f32 (this.scratchSpaceAddress, newValue);
    this.instance.exports._setValue_wavetablePosition (this.stateAddress, this.scratchSpaceAddress, numFramesToReachValue);
  }

  /** Sets the value of endpoint "morphSpeed".
   *  @param {Object} newValue - The new value, whose type will depend on the endpoint type
   *  @param {number} numFramesToReachValue - If this is non-zero and the type is scalar,
   *                                          this applies a ramp to reach the new value.
  */
  setInputValue_morphSpeed (newValue, numFramesToReachValue)
  {
    this._pack_f32 (this.scratchSpaceAddress, newValue);
    this.instance.exports._setValue_morphSpeed (this.stateAddress, this.scratchSpaceAddress, numFramesToReachValue);
  }

  /** Sets the value of endpoint "morphDepth".
   *  @param {Object} newValue - The new value, whose type will depend on the endpoint type
   *  @param {number} numFramesToReachValue - If this is non-zero and the type is scalar,
   *                                          this applies a ramp to reach the new value.
  */
  setInputValue_morphDepth (newValue, numFramesToReachValue)
  {
    this._pack_f32 (this.scratchSpaceAddress, newValue);
    this.instance.exports._setValue_morphDepth (this.stateAddress, this.scratchSpaceAddress, numFramesToReachValue);
  }

  /** Sets the value of endpoint "attack".
   *  @param {Object} newValue - The new value, whose type will depend on the endpoint type
   *  @param {number} numFramesToReachValue - If this is non-zero and the type is scalar,
   *                                          this applies a ramp to reach the new value.
  */
  setInputValue_attack (newValue, numFramesToReachValue)
  {
    this._pack_f32 (this.scratchSpaceAddress, newValue);
    this.instance.exports._setValue_attack (this.stateAddress, this.scratchSpaceAddress, numFramesToReachValue);
  }

  /** Sets the value of endpoint "decay".
   *  @param {Object} newValue - The new value, whose type will depend on the endpoint type
   *  @param {number} numFramesToReachValue - If this is non-zero and the type is scalar,
   *                                          this applies a ramp to reach the new value.
  */
  setInputValue_decay (newValue, numFramesToReachValue)
  {
    this._pack_f32 (this.scratchSpaceAddress, newValue);
    this.instance.exports._setValue_decay (this.stateAddress, this.scratchSpaceAddress, numFramesToReachValue);
  }

  /** Sets the value of endpoint "sustain".
   *  @param {Object} newValue - The new value, whose type will depend on the endpoint type
   *  @param {number} numFramesToReachValue - If this is non-zero and the type is scalar,
   *                                          this applies a ramp to reach the new value.
  */
  setInputValue_sustain (newValue, numFramesToReachValue)
  {
    this._pack_f32 (this.scratchSpaceAddress, newValue);
    this.instance.exports._setValue_sustain (this.stateAddress, this.scratchSpaceAddress, numFramesToReachValue);
  }

  /** Sets the value of endpoint "release".
   *  @param {Object} newValue - The new value, whose type will depend on the endpoint type
   *  @param {number} numFramesToReachValue - If this is non-zero and the type is scalar,
   *                                          this applies a ramp to reach the new value.
  */
  setInputValue_release (newValue, numFramesToReachValue)
  {
    this._pack_f32 (this.scratchSpaceAddress, newValue);
    this.instance.exports._setValue_release (this.stateAddress, this.scratchSpaceAddress, numFramesToReachValue);
  }

  /** Returns a frame from the output stream "out"
   *
   * @param {number} frameIndex - the index of the frame to fetch
   */
  getOutputFrame_out (frameIndex)
  {
    return this._getOutputFrameInternal_out (frameIndex);
  }

  /** Copies frames from the output stream "out" into a destination array.
   *
   * @param {Array} destChannelArrays   - An array of arrays (one per channel) into
   *                                      which the samples will be copied
   * @param {number} maxNumFramesToRead - The maximum number of frames to copy
   * @param {number} destChannel        - The channel to start writing from
   */
  getOutputFrames_out (destChannelArrays, maxNumFramesToRead, destChannel)
  {
    this._getOutputFramesInternal_out (destChannelArrays, maxNumFramesToRead, destChannel);
  }

  //==============================================================================
  // Code beyond this point is private internal implementation detail

  //==============================================================================
  /** @access private */
  async _initialiseInternalSIMD (sessionID, frequency)
  {
    this.stateAddress = 5255520;
    this.scratchSpaceAddress = 5258528;

    const memory = new WebAssembly.Memory ({ initial: 82 });
    const stack = new WebAssembly.Global ({ value: "i32", mutable: true }, 5255520);
    const imports = {
      env: {
        __linear_memory: memory,
        __memory_base: 0,
        __stack_pointer: stack,
        __table_base: 0,
        memcpy:  (dst, src, len) => { this.byteMemory.copyWithin (dst, src, src + len); return dst; },
        memmove: (dst, src, len) => { this.byteMemory.copyWithin (dst, src, src + len); return dst; },
        memset:  (dst, value, len) => { this.byteMemory.fill (value, dst, dst + len); return dst; }
      },
    };

    const result = await WebAssembly.instantiate (this._getWasmBytesSIMD(), imports);
    this.instance = result.instance;
    const exports = this.instance.exports;
    const memoryBuffer = exports.memory?.buffer || memory.buffer;
    const memoryDataView = new DataView (memoryBuffer);
    const byteMemory = new Uint8Array (memoryBuffer);
    this.byteMemory = byteMemory;
    this.memoryDataView = memoryDataView;

    exports.initialise?.(this.stateAddress, this.scratchSpaceAddress, sessionID, frequency);

    const advanceFn = exports.advanceBlock ? ((numFrames) => exports.advanceBlock (5255520, 5256480, numFrames))
                                           : (() => exports.advanceOneFrame (5255520, 5256480));

    this.reset = () => {
       byteMemory.fill (0, 5255520, 5256480);
       byteMemory.fill (0, 5258528, 5258528 + 4);
       exports.initialise?.(this.stateAddress, this.scratchSpaceAddress, sessionID, frequency);
    };

    this._advanceInternal = (numFrames) => {
      byteMemory.fill (0, 5256480, 5256480 + numFrames * 4);
      advanceFn (numFrames);
    };

    this._getOutputFrameInternal_out = (frameIndex) => { return memoryDataView.getFloat32 (5256480 + frameIndex * 4, true); };

    this._getOutputFramesInternal_out = (destChannelArrays, maxNumFramesToRead, destChannel) => {
      if (maxNumFramesToRead > 512)
        maxNumFramesToRead = 512;

      const channelsToCopy = Math.min (1, destChannelArrays.length - destChannel);
      let source = 5256480;

      for (let frame = 0; frame < maxNumFramesToRead; ++frame)
      {
        for (let channel = 0; channel < channelsToCopy; ++channel)
          destChannelArrays[destChannel + channel][frame] = memoryDataView.getFloat32 (source + 4 * channel, true);

        source += 4;
      }
    };

    this._pack_o1_Message_message_i32 = (address, newValue) => {
      memoryDataView.setInt32 (address, newValue.message, true);
    };

    this._pack_f32 = (address, newValue) => {
      memoryDataView.setFloat32 (address, newValue, true);
    };
  }

  //==============================================================================
  /** @access private */
  async _initialiseInternalNonSIMD (sessionID, frequency)
  {
    this.stateAddress = 5255808;
    this.scratchSpaceAddress = 5258816;

    const memory = new WebAssembly.Memory ({ initial: 82 });
    const stack = new WebAssembly.Global ({ value: "i32", mutable: true }, 5255808);
    const imports = {
      env: {
        __linear_memory: memory,
        __memory_base: 0,
        __stack_pointer: stack,
        __table_base: 0,
        memcpy:  (dst, src, len) => { this.byteMemory.copyWithin (dst, src, src + len); return dst; },
        memmove: (dst, src, len) => { this.byteMemory.copyWithin (dst, src, src + len); return dst; },
        memset:  (dst, value, len) => { this.byteMemory.fill (value, dst, dst + len); return dst; }
      },
    };

    const result = await WebAssembly.instantiate (this._getWasmBytesNonSIMD(), imports);
    this.instance = result.instance;
    const exports = this.instance.exports;
    const memoryBuffer = exports.memory?.buffer || memory.buffer;
    const memoryDataView = new DataView (memoryBuffer);
    const byteMemory = new Uint8Array (memoryBuffer);
    this.byteMemory = byteMemory;
    this.memoryDataView = memoryDataView;

    exports.initialise?.(this.stateAddress, this.scratchSpaceAddress, sessionID, frequency);

    const advanceFn = exports.advanceBlock ? ((numFrames) => exports.advanceBlock (5255808, 5256768, numFrames))
                                           : (() => exports.advanceOneFrame (5255808, 5256768));

    this.reset = () => {
       byteMemory.fill (0, 5255808, 5256768);
       byteMemory.fill (0, 5258816, 5258816 + 4);
       exports.initialise?.(this.stateAddress, this.scratchSpaceAddress, sessionID, frequency);
    };

    this._advanceInternal = (numFrames) => {
      byteMemory.fill (0, 5256768, 5256768 + numFrames * 4);
      advanceFn (numFrames);
    };

    this._getOutputFrameInternal_out = (frameIndex) => { return memoryDataView.getFloat32 (5256768 + frameIndex * 4, true); };

    this._getOutputFramesInternal_out = (destChannelArrays, maxNumFramesToRead, destChannel) => {
      if (maxNumFramesToRead > 512)
        maxNumFramesToRead = 512;

      const channelsToCopy = Math.min (1, destChannelArrays.length - destChannel);
      let source = 5256768;

      for (let frame = 0; frame < maxNumFramesToRead; ++frame)
      {
        for (let channel = 0; channel < channelsToCopy; ++channel)
          destChannelArrays[destChannel + channel][frame] = memoryDataView.getFloat32 (source + 4 * channel, true);

        source += 4;
      }
    };

    this._pack_o1_Message_message_i32 = (address, newValue) => {
      memoryDataView.setInt32 (address, newValue.message, true);
    };

    this._pack_f32 = (address, newValue) => {
      memoryDataView.setFloat32 (address, newValue, true);
    };
  }

  /** @access private */
  _getWasmBytesSIMD()
  {
    return new Uint8Array([0,97,115,109,1,0,0,0,1,153,128,128,128,0,4,96,2,127,127,0,96,2,125,127,1,125,96,3,127,127,127,0,96,4,127,127,127,124,0,2,175,128,128,128,0,2,3,101,110,118,15,95,95,108,105,110,101,
      97,114,95,109,101,109,111,114,121,2,0,1,3,101,110,118,15,95,95,115,116,97,99,107,95,112,111,105,110,116,101,114,3,127,1,3,141,128,128,128,0,12,0,1,2,2,2,2,2,2,2,2,3,2,7,221,129,128,128,0,11,17,95,115,101,
      110,100,69,118,101,110,116,95,109,105,100,105,73,110,0,0,16,95,115,101,116,86,97,108,117,101,95,118,111,108,117,109,101,0,2,27,95,115,101,116,86,97,108,117,101,95,119,97,118,101,116,97,98,108,101,80,111,
      115,105,116,105,111,110,0,3,20,95,115,101,116,86,97,108,117,101,95,109,111,114,112,104,83,112,101,101,100,0,4,20,95,115,101,116,86,97,108,117,101,95,109,111,114,112,104,68,101,112,116,104,0,5,16,95,115,
      101,116,86,97,108,117,101,95,97,116,116,97,99,107,0,6,15,95,115,101,116,86,97,108,117,101,95,100,101,99,97,121,0,7,17,95,115,101,116,86,97,108,117,101,95,115,117,115,116,97,105,110,0,8,17,95,115,101,116,
      86,97,108,117,101,95,114,101,108,101,97,115,101,0,9,10,105,110,105,116,105,97,108,105,115,101,0,10,12,97,100,118,97,110,99,101,66,108,111,99,107,0,11,12,129,128,128,128,0,2,10,176,216,128,128,0,12,188,
      28,4,4,127,5,125,1,126,1,125,2,64,2,64,2,64,2,64,32,1,40,2,0,34,1,65,128,128,192,7,113,34,2,65,128,128,192,4,71,13,0,32,1,65,255,1,113,69,13,0,32,0,65,7,65,6,65,5,65,4,65,3,65,2,32,0,40,2,176,5,34,2,32,
      0,40,2,160,5,34,3,72,34,4,32,0,40,2,192,5,34,5,32,2,32,3,32,4,27,34,2,72,34,3,27,32,0,40,2,208,5,34,4,32,5,32,2,32,3,27,34,2,72,34,3,27,32,0,40,2,224,5,34,5,32,4,32,2,32,3,27,34,2,72,34,3,27,32,0,40,2,
      240,5,34,4,32,5,32,2,32,3,27,34,2,72,34,3,27,32,0,40,2,128,6,34,5,32,4,32,2,32,3,27,34,2,72,34,3,27,32,0,40,2,144,6,32,5,32,2,32,3,27,72,27,34,3,65,4,116,106,34,2,32,1,65,16,118,65,15,113,54,2,156,5,32,
      2,65,1,59,0,152,5,32,2,32,1,65,8,118,65,255,0,113,34,4,179,34,6,56,2,164,5,32,0,32,3,65,208,0,108,106,34,3,32,6,56,2,28,32,0,32,0,40,2,152,6,65,1,106,34,5,54,2,152,6,32,2,32,5,54,2,160,5,32,3,65,24,106,
      33,0,32,1,65,255,0,113,179,67,4,2,1,60,148,33,7,2,64,32,4,65,187,127,106,178,67,171,170,170,61,148,34,8,188,34,2,65,255,255,255,255,7,113,34,1,13,0,67,0,0,128,63,33,6,12,4,11,2,64,32,1,65,129,128,128,252,
      7,73,13,0,32,8,67,0,0,0,64,146,33,6,12,4,11,2,64,2,64,32,1,65,128,128,128,252,3,70,13,0,32,1,65,128,128,128,252,7,71,13,1,32,8,67,0,0,0,0,32,2,65,127,74,27,33,6,12,5,11,67,0,0,0,64,67,0,0,0,63,32,2,65,
      127,74,27,33,6,12,4,11,32,2,65,128,128,128,248,3,70,13,2,2,64,32,2,65,128,128,128,128,4,71,13,0,67,0,0,128,64,33,6,12,4,11,2,64,32,1,65,129,128,128,232,4,73,13,0,67,0,0,128,127,67,0,0,0,0,32,2,65,0,74,
      27,33,6,12,4,11,67,0,0,128,127,33,6,32,8,67,0,0,0,0,148,32,8,32,2,65,128,96,113,190,34,9,147,146,34,10,32,9,146,34,8,188,34,1,65,128,128,128,152,4,74,13,3,2,64,32,1,65,128,128,128,152,4,71,13,0,32,10,67,
      60,170,56,51,146,32,8,32,9,147,94,13,4,32,8,188,65,255,255,255,255,7,113,33,2,12,2,11,67,0,0,0,0,33,6,32,8,188,65,255,255,255,255,7,113,34,2,65,128,128,216,152,4,75,13,3,32,1,65,128,128,216,152,124,71,
      13,1,32,10,32,8,32,9,147,95,69,13,1,12,3,11,2,64,2,64,2,64,2,64,32,2,65,128,128,128,4,70,13,0,32,1,65,255,129,192,7,113,65,128,128,192,4,71,13,1,11,32,1,65,16,118,65,15,113,33,2,32,1,65,8,118,65,255,0,
      113,179,33,6,32,0,40,2,156,5,33,1,2,64,2,64,32,0,45,0,160,6,13,0,66,1,32,2,173,134,33,11,32,1,32,2,71,13,3,32,0,42,2,164,5,32,6,92,13,3,32,0,41,3,168,6,32,11,131,80,13,1,32,0,65,1,58,0,153,5,12,3,11,2,
      64,32,1,32,2,71,13,0,32,0,42,2,164,5,32,6,92,13,0,32,0,65,1,58,0,153,5,11,2,64,32,0,40,2,172,5,32,2,71,13,0,32,0,42,2,180,5,32,6,92,13,0,32,0,65,1,58,0,169,5,11,2,64,32,0,40,2,188,5,32,2,71,13,0,32,0,42,
      2,196,5,32,6,92,13,0,32,0,65,1,58,0,185,5,11,2,64,32,0,40,2,204,5,32,2,71,13,0,32,0,42,2,212,5,32,6,92,13,0,32,0,65,1,58,0,201,5,11,2,64,32,0,40,2,220,5,32,2,71,13,0,32,0,42,2,228,5,32,6,92,13,0,32,0,65,
      1,58,0,217,5,11,2,64,32,0,40,2,236,5,32,2,71,13,0,32,0,42,2,244,5,32,6,92,13,0,32,0,65,1,58,0,233,5,11,2,64,32,0,40,2,252,5,32,2,71,13,0,32,0,42,2,132,6,32,6,92,13,0,32,0,65,1,58,0,249,5,11,32,0,40,2,140,
      6,32,2,71,13,3,32,0,42,2,148,6,32,6,92,13,3,32,0,65,1,58,0,137,6,15,11,2,64,32,0,42,2,28,32,6,92,13,0,32,0,65,0,54,2,36,11,32,0,65,0,58,0,152,5,32,0,32,0,40,2,156,6,65,1,106,34,1,54,2,156,6,32,0,32,1,54,
      2,160,5,12,1,11,32,2,65,128,128,192,5,71,13,1,32,1,65,8,118,65,255,0,113,34,2,65,202,0,70,13,1,32,2,65,192,0,71,13,1,66,1,32,1,65,16,118,65,15,113,34,2,173,134,33,11,2,64,32,1,65,255,0,113,179,67,4,2,1,
      60,148,67,0,0,0,63,96,69,13,0,32,0,32,0,41,3,168,6,32,11,132,55,3,168,6,32,2,13,2,32,0,65,1,58,0,160,6,15,11,32,0,32,0,41,3,168,6,32,11,66,127,133,131,55,3,168,6,2,64,32,2,69,13,0,2,64,32,0,40,2,156,5,
      32,2,71,13,0,32,0,45,0,152,5,69,13,0,32,0,45,0,153,5,69,13,0,2,64,32,0,42,2,164,5,32,0,42,2,28,92,13,0,32,0,65,0,54,2,36,11,32,0,65,0,58,0,152,5,32,0,32,0,40,2,156,6,65,1,106,34,1,54,2,156,6,32,0,32,1,
      54,2,160,5,11,2,64,32,0,40,2,172,5,32,2,71,13,0,32,0,45,0,168,5,69,13,0,32,0,45,0,169,5,69,13,0,2,64,32,0,42,2,180,5,32,0,42,2,108,92,13,0,32,0,65,0,54,2,116,11,32,0,65,0,58,0,168,5,32,0,32,0,40,2,156,
      6,65,1,106,34,1,54,2,156,6,32,0,32,1,54,2,176,5,11,2,64,32,0,40,2,188,5,32,2,71,13,0,32,0,45,0,184,5,69,13,0,32,0,45,0,185,5,69,13,0,2,64,32,0,42,2,196,5,32,0,42,2,188,1,92,13,0,32,0,65,0,54,2,196,1,11,
      32,0,65,0,58,0,184,5,32,0,32,0,40,2,156,6,65,1,106,34,1,54,2,156,6,32,0,32,1,54,2,192,5,11,2,64,32,0,40,2,204,5,32,2,71,13,0,32,0,45,0,200,5,69,13,0,32,0,45,0,201,5,69,13,0,2,64,32,0,42,2,212,5,32,0,42,
      2,140,2,92,13,0,32,0,65,0,54,2,148,2,11,32,0,65,0,58,0,200,5,32,0,32,0,40,2,156,6,65,1,106,34,1,54,2,156,6,32,0,32,1,54,2,208,5,11,2,64,32,0,40,2,220,5,32,2,71,13,0,32,0,45,0,216,5,69,13,0,32,0,45,0,217,
      5,69,13,0,2,64,32,0,42,2,228,5,32,0,42,2,220,2,92,13,0,32,0,65,0,54,2,228,2,11,32,0,65,0,58,0,216,5,32,0,32,0,40,2,156,6,65,1,106,34,1,54,2,156,6,32,0,32,1,54,2,224,5,11,2,64,32,0,40,2,236,5,32,2,71,13,
      0,32,0,45,0,232,5,69,13,0,32,0,45,0,233,5,69,13,0,2,64,32,0,42,2,244,5,32,0,42,2,172,3,92,13,0,32,0,65,0,54,2,180,3,11,32,0,65,0,58,0,232,5,32,0,32,0,40,2,156,6,65,1,106,34,1,54,2,156,6,32,0,32,1,54,2,
      240,5,11,2,64,32,0,40,2,252,5,32,2,71,13,0,32,0,45,0,248,5,69,13,0,32,0,45,0,249,5,69,13,0,2,64,32,0,42,2,132,6,32,0,42,2,252,3,92,13,0,32,0,65,0,54,2,132,4,11,32,0,65,0,58,0,248,5,32,0,32,0,40,2,156,6,
      65,1,106,34,1,54,2,156,6,32,0,32,1,54,2,128,6,11,32,0,40,2,140,6,32,2,71,13,2,32,0,45,0,136,6,69,13,2,32,0,45,0,137,6,69,13,2,2,64,32,0,42,2,148,6,32,0,42,2,204,4,92,13,0,32,0,65,0,54,2,212,4,11,32,0,65,
      0,58,0,136,6,32,0,32,0,40,2,156,6,65,1,106,34,1,54,2,156,6,32,0,32,1,54,2,144,6,15,11,32,0,65,0,58,0,160,6,2,64,32,0,45,0,152,5,69,13,0,32,0,45,0,153,5,69,13,0,2,64,32,0,42,2,164,5,32,0,42,2,28,92,13,0,
      32,0,65,0,54,2,36,11,32,0,65,0,58,0,152,5,32,0,32,0,40,2,156,6,65,1,106,34,1,54,2,156,6,32,0,32,1,54,2,160,5,11,2,64,32,0,45,0,168,5,69,13,0,32,0,45,0,169,5,69,13,0,2,64,32,0,42,2,180,5,32,0,42,2,108,92,
      13,0,32,0,65,0,54,2,116,11,32,0,65,0,58,0,168,5,32,0,32,0,40,2,156,6,65,1,106,34,1,54,2,156,6,32,0,32,1,54,2,176,5,11,2,64,32,0,45,0,184,5,69,13,0,32,0,45,0,185,5,69,13,0,2,64,32,0,42,2,196,5,32,0,42,2,
      188,1,92,13,0,32,0,65,0,54,2,196,1,11,32,0,65,0,58,0,184,5,32,0,32,0,40,2,156,6,65,1,106,34,1,54,2,156,6,32,0,32,1,54,2,192,5,11,2,64,32,0,45,0,200,5,69,13,0,32,0,45,0,201,5,69,13,0,2,64,32,0,42,2,212,
      5,32,0,42,2,140,2,92,13,0,32,0,65,0,54,2,148,2,11,32,0,65,0,58,0,200,5,32,0,32,0,40,2,156,6,65,1,106,34,1,54,2,156,6,32,0,32,1,54,2,208,5,11,2,64,32,0,45,0,216,5,69,13,0,32,0,45,0,217,5,69,13,0,2,64,32,
      0,42,2,228,5,32,0,42,2,220,2,92,13,0,32,0,65,0,54,2,228,2,11,32,0,65,0,58,0,216,5,32,0,32,0,40,2,156,6,65,1,106,34,1,54,2,156,6,32,0,32,1,54,2,224,5,11,2,64,32,0,45,0,232,5,69,13,0,32,0,45,0,233,5,69,13,
      0,2,64,32,0,42,2,244,5,32,0,42,2,172,3,92,13,0,32,0,65,0,54,2,180,3,11,32,0,65,0,58,0,232,5,32,0,32,0,40,2,156,6,65,1,106,34,1,54,2,156,6,32,0,32,1,54,2,240,5,11,2,64,32,0,45,0,248,5,69,13,0,32,0,45,0,
      249,5,69,13,0,2,64,32,0,42,2,132,6,32,0,42,2,252,3,92,13,0,32,0,65,0,54,2,132,4,11,32,0,65,0,58,0,248,5,32,0,32,0,40,2,156,6,65,1,106,34,1,54,2,156,6,32,0,32,1,54,2,128,6,11,32,0,45,0,136,6,69,13,1,32,
      0,45,0,137,6,69,13,1,2,64,32,0,42,2,148,6,32,0,42,2,204,4,92,13,0,32,0,65,0,54,2,212,4,11,32,0,65,0,58,0,136,6,32,0,32,0,40,2,156,6,65,1,106,34,1,54,2,156,6,32,0,32,1,54,2,144,6,12,1,11,2,64,32,0,40,2,
      172,5,32,2,71,13,0,32,0,42,2,180,5,32,6,92,13,0,2,64,32,0,41,3,168,6,32,11,131,80,13,0,32,0,65,1,58,0,169,5,12,1,11,2,64,32,0,42,2,108,32,6,92,13,0,32,0,65,0,54,2,116,11,32,0,65,0,58,0,168,5,32,0,32,0,
      40,2,156,6,65,1,106,34,1,54,2,156,6,32,0,32,1,54,2,176,5,11,2,64,32,0,40,2,188,5,32,2,71,13,0,32,0,42,2,196,5,32,6,92,13,0,2,64,32,0,41,3,168,6,32,11,131,80,13,0,32,0,65,1,58,0,185,5,12,1,11,2,64,32,0,
      42,2,188,1,32,6,92,13,0,32,0,65,0,54,2,196,1,11,32,0,65,0,58,0,184,5,32,0,32,0,40,2,156,6,65,1,106,34,1,54,2,156,6,32,0,32,1,54,2,192,5,11,2,64,32,0,40,2,204,5,32,2,71,13,0,32,0,42,2,212,5,32,6,92,13,0,
      2,64,32,0,41,3,168,6,32,11,131,80,13,0,32,0,65,1,58,0,201,5,12,1,11,2,64,32,0,42,2,140,2,32,6,92,13,0,32,0,65,0,54,2,148,2,11,32,0,65,0,58,0,200,5,32,0,32,0,40,2,156,6,65,1,106,34,1,54,2,156,6,32,0,32,
      1,54,2,208,5,11,2,64,32,0,40,2,220,5,32,2,71,13,0,32,0,42,2,228,5,32,6,92,13,0,2,64,32,0,41,3,168,6,32,11,131,80,13,0,32,0,65,1,58,0,217,5,12,1,11,2,64,32,0,42,2,220,2,32,6,92,13,0,32,0,65,0,54,2,228,2,
      11,32,0,65,0,58,0,216,5,32,0,32,0,40,2,156,6,65,1,106,34,1,54,2,156,6,32,0,32,1,54,2,224,5,11,2,64,32,0,40,2,236,5,32,2,71,13,0,32,0,42,2,244,5,32,6,92,13,0,2,64,32,0,41,3,168,6,32,11,131,80,13,0,32,0,
      65,1,58,0,233,5,12,1,11,2,64,32,0,42,2,172,3,32,6,92,13,0,32,0,65,0,54,2,180,3,11,32,0,65,0,58,0,232,5,32,0,32,0,40,2,156,6,65,1,106,34,1,54,2,156,6,32,0,32,1,54,2,240,5,11,2,64,32,0,40,2,252,5,32,2,71,
      13,0,32,0,42,2,132,6,32,6,92,13,0,2,64,32,0,41,3,168,6,32,11,131,80,13,0,32,0,65,1,58,0,249,5,12,1,11,2,64,32,0,42,2,252,3,32,6,92,13,0,32,0,65,0,54,2,132,4,11,32,0,65,0,58,0,248,5,32,0,32,0,40,2,156,6,
      65,1,106,34,1,54,2,156,6,32,0,32,1,54,2,128,6,11,32,0,40,2,140,6,32,2,71,13,0,32,0,42,2,148,6,32,6,92,13,0,2,64,32,0,41,3,168,6,32,11,131,80,13,0,32,0,65,1,58,0,137,6,15,11,2,64,32,0,42,2,204,4,32,6,92,
      13,0,32,0,65,0,54,2,212,4,11,32,0,65,0,58,0,136,6,32,0,32,0,40,2,156,6,65,1,106,34,1,54,2,156,6,32,0,32,1,54,2,144,6,15,11,15,11,65,0,33,3,2,64,32,2,65,128,128,128,248,3,77,13,0,65,0,65,128,128,128,4,32,
      2,65,23,118,65,130,127,106,118,32,1,106,34,2,65,255,255,255,3,113,65,128,128,128,4,114,65,150,1,32,2,65,23,118,65,255,1,113,34,4,107,118,34,3,107,32,3,32,1,65,0,72,27,33,3,32,10,32,9,65,128,128,128,124,
      32,4,65,129,127,106,117,32,2,113,190,147,34,9,146,188,33,1,11,2,64,32,3,65,23,116,32,1,65,128,128,126,113,190,34,6,67,0,114,49,63,148,34,12,32,6,67,140,190,191,53,148,32,10,32,6,32,9,147,147,67,24,114,
      49,63,148,146,34,9,146,34,6,32,6,32,6,32,6,32,6,148,34,8,32,8,32,8,32,8,32,8,67,76,187,49,51,148,67,14,234,221,181,146,148,67,85,179,138,56,146,148,67,97,11,54,187,146,148,67,171,170,42,62,146,148,147,
      34,8,148,32,8,67,0,0,0,192,146,149,32,9,32,6,32,12,147,147,34,8,32,6,32,8,148,146,147,147,67,0,0,128,63,146,34,6,188,106,34,1,65,255,255,255,3,74,13,0,32,6,32,3,16,129,128,128,128,0,33,6,12,2,11,32,1,190,
      33,6,12,1,11,67,243,4,181,63,33,6,11,32,0,32,7,56,2,12,32,0,32,6,67,0,0,220,67,148,56,2,8,11,160,1,0,2,64,2,64,2,64,32,1,65,128,1,72,13,0,32,0,67,0,0,0,127,148,33,0,32,1,65,254,1,75,13,1,32,1,65,129,127,
      106,33,1,12,2,11,32,1,65,130,127,78,13,1,32,0,67,0,0,128,12,148,33,0,2,64,32,1,65,155,126,77,13,0,32,1,65,230,0,106,33,1,12,2,11,32,0,67,0,0,128,12,148,33,0,32,1,65,182,125,32,1,65,182,125,75,27,65,204,
      1,106,33,1,12,1,11,32,0,67,0,0,0,127,148,33,0,32,1,65,253,2,32,1,65,253,2,73,27,65,130,126,106,33,1,11,32,0,32,1,65,23,116,65,128,128,128,252,3,106,190,148,11,72,1,1,125,2,64,32,0,40,2,232,6,13,0,32,0,
      32,0,40,2,0,65,1,106,54,2,0,11,32,1,42,2,0,33,3,32,0,32,2,65,1,32,2,65,1,75,27,34,2,54,2,232,6,32,0,32,3,32,0,42,2,224,6,147,32,2,178,149,56,2,228,6,11,72,1,1,125,2,64,32,0,40,2,244,6,13,0,32,0,32,0,40,
      2,0,65,1,106,54,2,0,11,32,1,42,2,0,33,3,32,0,32,2,65,1,32,2,65,1,75,27,34,2,54,2,244,6,32,0,32,3,32,0,42,2,236,6,147,32,2,178,149,56,2,240,6,11,72,1,1,125,2,64,32,0,40,2,128,7,13,0,32,0,32,0,40,2,0,65,
      1,106,54,2,0,11,32,1,42,2,0,33,3,32,0,32,2,65,1,32,2,65,1,75,27,34,2,54,2,128,7,32,0,32,3,32,0,42,2,248,6,147,32,2,178,149,56,2,252,6,11,72,1,1,125,2,64,32,0,40,2,140,7,13,0,32,0,32,0,40,2,0,65,1,106,54,
      2,0,11,32,1,42,2,0,33,3,32,0,32,2,65,1,32,2,65,1,75,27,34,2,54,2,140,7,32,0,32,3,32,0,42,2,132,7,147,32,2,178,149,56,2,136,7,11,72,1,1,125,2,64,32,0,40,2,152,7,13,0,32,0,32,0,40,2,0,65,1,106,54,2,0,11,
      32,1,42,2,0,33,3,32,0,32,2,65,1,32,2,65,1,75,27,34,2,54,2,152,7,32,0,32,3,32,0,42,2,144,7,147,32,2,178,149,56,2,148,7,11,72,1,1,125,2,64,32,0,40,2,164,7,13,0,32,0,32,0,40,2,0,65,1,106,54,2,0,11,32,1,42,
      2,0,33,3,32,0,32,2,65,1,32,2,65,1,75,27,34,2,54,2,164,7,32,0,32,3,32,0,42,2,156,7,147,32,2,178,149,56,2,160,7,11,72,1,1,125,2,64,32,0,40,2,176,7,13,0,32,0,32,0,40,2,0,65,1,106,54,2,0,11,32,1,42,2,0,33,
      3,32,0,32,2,65,1,32,2,65,1,75,27,34,2,54,2,176,7,32,0,32,3,32,0,42,2,168,7,147,32,2,178,149,56,2,172,7,11,72,1,1,125,2,64,32,0,40,2,188,7,13,0,32,0,32,0,40,2,0,65,1,106,54,2,0,11,32,1,42,2,0,33,3,32,0,
      32,2,65,1,32,2,65,1,75,27,34,2,54,2,188,7,32,0,32,3,32,0,42,2,180,7,147,32,2,178,149,56,2,184,7,11,181,1,0,32,0,66,128,128,240,158,4,55,2,208,4,32,0,65,7,54,2,200,4,32,0,66,128,128,240,158,4,55,2,128,4,
      32,0,65,6,54,2,248,3,32,0,66,128,128,240,158,4,55,2,176,3,32,0,65,5,54,2,168,3,32,0,66,128,128,240,158,4,55,2,224,2,32,0,65,4,54,2,216,2,32,0,66,128,128,240,158,4,55,2,144,2,32,0,65,3,54,2,136,2,32,0,66,
      128,128,240,158,4,55,2,192,1,32,0,65,2,54,2,184,1,32,0,66,128,128,240,158,4,55,2,112,32,0,65,1,54,2,104,32,0,66,128,128,240,158,4,55,2,32,32,0,65,0,54,2,24,65,0,32,3,57,3,128,128,128,128,0,32,0,66,128,
      128,128,128,23,55,2,152,6,11,206,52,19,9,127,2,125,1,127,1,123,1,125,1,127,1,125,3,127,2,125,1,127,3,124,1,125,7,127,1,124,1,123,7,127,16,123,2,126,2,127,35,128,128,128,128,0,65,192,3,107,34,3,36,128,128,
      128,128,0,2,64,32,0,40,2,4,32,2,70,13,0,32,0,65,24,106,33,4,32,3,65,192,0,106,65,100,106,33,5,32,3,65,128,1,106,65,32,106,33,6,32,3,65,4,114,34,7,65,56,106,33,8,32,7,65,48,106,33,9,32,7,65,16,106,33,10,
      3,64,2,64,2,64,32,0,40,2,0,34,11,13,0,32,0,42,2,204,6,33,12,32,0,42,2,200,6,33,13,12,1,11,2,64,32,0,40,2,232,6,34,14,69,13,0,32,0,32,14,65,127,106,34,14,54,2,232,6,32,0,32,0,42,2,228,6,32,0,42,2,224,6,
      146,56,2,224,6,32,14,13,0,32,0,32,11,65,127,106,34,11,54,2,0,11,2,64,32,0,40,2,244,6,34,14,69,13,0,32,0,32,14,65,127,106,34,14,54,2,244,6,32,0,32,0,42,2,240,6,32,0,42,2,236,6,146,56,2,236,6,32,14,13,0,
      32,0,32,11,65,127,106,34,11,54,2,0,11,2,64,32,0,40,2,128,7,34,14,69,13,0,32,0,32,14,65,127,106,34,14,54,2,128,7,32,0,32,0,42,2,252,6,32,0,42,2,248,6,146,56,2,248,6,32,14,13,0,32,0,32,11,65,127,106,34,11,
      54,2,0,11,2,64,32,0,40,2,140,7,34,14,69,13,0,32,0,32,14,65,127,106,34,14,54,2,140,7,32,0,32,0,42,2,136,7,32,0,42,2,132,7,146,56,2,132,7,32,14,13,0,32,0,32,11,65,127,106,34,11,54,2,0,11,2,64,32,0,40,2,152,
      7,34,14,69,13,0,32,0,32,14,65,127,106,34,14,54,2,152,7,32,0,32,0,42,2,148,7,32,0,42,2,144,7,146,56,2,144,7,32,14,13,0,32,0,32,11,65,127,106,34,11,54,2,0,11,2,64,32,0,40,2,164,7,34,14,69,13,0,32,0,32,14,
      65,127,106,34,14,54,2,164,7,32,0,32,0,42,2,160,7,32,0,42,2,156,7,146,56,2,156,7,32,14,13,0,32,0,32,11,65,127,106,34,11,54,2,0,11,2,64,32,0,40,2,176,7,34,14,69,13,0,32,0,32,14,65,127,106,34,14,54,2,176,
      7,32,0,32,0,42,2,172,7,32,0,42,2,168,7,146,56,2,168,7,32,14,13,0,32,0,32,11,65,127,106,34,11,54,2,0,11,32,0,42,2,180,7,33,13,2,64,32,0,40,2,188,7,34,14,69,13,0,32,0,32,14,65,127,106,34,14,54,2,188,7,32,
      0,32,0,42,2,184,7,32,13,146,34,13,56,2,180,7,32,14,13,0,32,0,32,11,65,127,106,54,2,0,11,32,0,32,13,56,2,220,6,32,0,32,0,42,2,224,6,56,2,192,6,32,0,32,0,42,2,236,6,56,2,196,6,32,0,32,0,42,2,248,6,34,13,
      56,2,200,6,32,0,32,0,42,2,132,7,34,12,56,2,204,6,32,0,32,0,42,2,144,7,56,2,208,6,32,0,32,0,42,2,156,7,56,2,212,6,32,0,32,0,42,2,168,7,56,2,216,6,11,32,7,253,12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,34,15,253,
      11,2,0,32,0,32,12,56,2,184,6,32,0,32,13,56,2,180,6,32,8,65,0,54,2,0,32,9,66,0,55,2,0,32,7,65,32,106,32,15,253,11,2,0,32,10,32,15,253,11,2,0,67,0,0,0,0,33,16,2,64,32,0,40,2,188,6,65,127,70,13,0,2,64,32,
      13,67,0,0,0,0,94,69,13,0,32,12,32,0,42,2,176,6,34,16,32,16,146,67,0,0,128,191,146,139,148,33,12,2,64,32,16,32,13,65,0,43,3,128,128,128,128,0,182,149,146,34,13,67,0,0,128,63,96,69,13,0,3,64,32,13,67,0,0,
      128,191,146,34,13,67,0,0,128,63,96,13,0,11,11,32,12,67,0,0,0,0,146,33,16,32,0,32,13,56,2,176,6,11,32,0,65,1,54,2,188,6,11,32,0,32,0,42,2,192,6,34,13,56,2,128,5,32,0,32,13,56,2,176,4,32,0,32,13,56,2,224,
      3,32,0,32,13,56,2,144,3,32,0,32,13,56,2,192,2,32,0,32,13,56,2,240,1,32,0,32,13,56,2,160,1,32,0,32,13,56,2,80,32,0,32,0,42,2,196,6,34,13,56,2,132,5,32,0,32,13,56,2,180,4,32,0,32,13,56,2,228,3,32,0,32,13,
      56,2,148,3,32,0,32,13,56,2,196,2,32,0,32,13,56,2,244,1,32,0,32,13,56,2,164,1,32,0,32,13,56,2,84,32,3,32,16,56,2,56,32,3,32,16,56,2,48,32,3,32,16,56,2,40,32,3,32,16,56,2,32,32,3,32,16,56,2,24,32,3,32,16,
      56,2,16,32,3,32,16,56,2,8,32,3,32,16,56,2,0,32,0,32,0,42,2,208,6,34,13,56,2,136,5,32,0,32,13,56,2,184,4,32,0,32,13,56,2,232,3,32,0,32,13,56,2,152,3,32,0,32,13,56,2,200,2,32,0,32,13,56,2,248,1,32,0,32,13,
      56,2,168,1,32,0,32,13,56,2,88,32,0,32,0,42,2,212,6,34,13,56,2,140,5,32,0,32,13,56,2,188,4,32,0,32,13,56,2,236,3,32,0,32,13,56,2,156,3,32,0,32,13,56,2,204,2,32,0,32,13,56,2,252,1,32,0,32,13,56,2,172,1,32,
      0,32,13,56,2,92,32,0,32,0,42,2,216,6,34,13,56,2,144,5,32,0,32,13,56,2,192,4,32,0,32,13,56,2,240,3,32,0,32,13,56,2,160,3,32,0,32,13,56,2,208,2,32,0,32,13,56,2,128,2,32,0,32,13,56,2,176,1,32,0,32,13,56,2,
      96,32,0,32,0,42,2,220,6,34,13,56,2,148,5,32,0,32,13,56,2,196,4,32,0,32,13,56,2,244,3,32,0,32,13,56,2,164,3,32,0,32,13,56,2,212,2,32,0,32,13,56,2,132,2,32,0,32,13,56,2,180,1,32,0,32,13,56,2,100,65,0,33,
      17,65,0,43,3,128,128,128,128,0,182,33,18,3,64,67,0,0,0,0,33,13,65,0,33,19,67,0,0,0,0,33,16,2,64,32,4,32,17,65,208,0,108,106,34,20,40,2,16,65,127,70,13,0,32,20,65,1,54,2,16,32,20,42,2,12,67,0,0,0,0,94,33,
      19,32,20,42,2,8,67,0,0,0,0,146,33,16,11,32,3,32,17,65,3,116,106,33,21,2,64,32,20,40,2,24,65,127,70,13,0,32,21,42,2,0,32,20,42,2,60,146,34,22,67,0,0,0,0,146,33,12,2,64,2,64,32,20,42,2,20,34,13,67,219,15,
      201,64,148,34,23,188,34,24,65,255,255,255,255,7,113,34,11,65,218,159,164,250,3,75,13,0,32,23,32,23,187,34,25,32,25,162,34,26,32,25,162,34,27,32,26,32,26,162,162,32,26,68,167,70,59,140,135,205,198,62,162,
      68,116,231,202,226,249,0,42,191,160,162,32,27,32,26,68,178,251,110,137,16,17,129,63,162,68,119,172,203,84,85,85,197,191,160,162,32,25,160,160,182,32,11,65,128,128,128,204,3,73,27,33,28,12,1,11,2,64,32,
      11,65,209,167,237,131,4,75,13,0,32,23,187,33,26,2,64,32,11,65,228,151,219,128,4,79,13,0,68,0,0,0,0,0,0,240,63,32,26,68,24,45,68,84,251,33,249,63,160,34,25,32,25,162,34,25,68,129,94,12,253,255,255,223,63,
      162,161,32,25,32,25,162,34,27,68,66,58,5,225,83,85,165,63,162,160,32,25,32,27,162,32,25,68,105,80,238,224,66,147,249,62,162,68,39,30,15,232,135,192,86,191,160,162,160,182,140,68,0,0,0,0,0,0,240,63,32,26,
      68,24,45,68,84,251,33,249,191,160,34,26,32,26,162,34,26,68,129,94,12,253,255,255,223,63,162,161,32,26,32,26,162,34,25,68,66,58,5,225,83,85,165,63,162,160,32,26,32,25,162,32,26,68,105,80,238,224,66,147,
      249,62,162,68,39,30,15,232,135,192,86,191,160,162,160,182,32,24,65,0,72,27,33,28,12,2,11,68,24,45,68,84,251,33,9,64,68,24,45,68,84,251,33,9,192,32,24,65,0,72,27,32,26,160,34,25,32,25,162,34,26,32,25,154,
      162,34,27,32,26,32,26,162,162,32,26,68,167,70,59,140,135,205,198,62,162,68,116,231,202,226,249,0,42,191,160,162,32,27,32,26,68,178,251,110,137,16,17,129,63,162,68,119,172,203,84,85,85,197,191,160,162,32,
      25,161,160,182,33,28,12,1,11,2,64,2,64,2,64,32,11,65,214,227,136,135,4,73,13,0,32,11,65,255,255,255,251,7,77,13,1,32,23,32,23,147,33,28,12,3,11,32,23,187,33,26,32,11,65,224,219,191,133,4,73,13,1,68,24,
      45,68,84,251,33,25,64,68,24,45,68,84,251,33,25,192,32,24,65,0,72,27,32,26,160,34,25,32,25,32,25,162,34,26,162,34,27,32,26,32,26,162,162,32,26,68,167,70,59,140,135,205,198,62,162,68,116,231,202,226,249,
      0,42,191,160,162,32,25,32,27,32,26,68,178,251,110,137,16,17,129,63,162,68,119,172,203,84,85,85,197,191,160,162,160,160,182,33,28,12,2,11,2,64,2,64,32,11,65,218,159,164,238,4,75,13,0,32,23,187,34,26,32,
      26,68,131,200,201,109,48,95,228,63,162,68,0,0,0,0,0,0,56,67,160,68,0,0,0,0,0,0,56,195,160,34,25,68,0,0,0,80,251,33,249,191,162,160,32,25,68,99,98,26,97,180,16,81,190,162,160,33,26,32,25,252,2,33,29,12,
      1,11,32,3,66,128,128,128,128,208,227,252,180,53,55,3,184,3,32,3,66,128,128,128,128,168,196,224,241,54,55,3,176,3,32,3,66,128,128,128,128,132,164,137,189,56,55,3,168,3,32,3,66,128,128,128,128,184,240,134,
      248,57,55,3,160,3,32,3,66,128,128,128,128,150,138,179,188,59,55,3,152,3,32,3,66,128,128,128,128,136,211,145,252,60,55,3,144,3,32,3,66,128,128,128,128,208,133,145,186,62,55,3,136,3,32,3,66,128,128,128,128,
      180,191,200,252,63,55,3,128,3,2,64,65,128,1,69,13,0,32,3,65,128,2,106,65,0,65,128,1,252,11,0,11,2,64,65,224,0,69,13,0,32,6,65,0,65,224,0,252,11,0,11,32,3,65,192,0,106,65,16,106,32,15,253,11,3,0,32,3,65,
      192,0,106,65,32,106,32,15,253,11,3,0,32,3,65,192,0,106,65,48,106,32,15,253,11,3,0,32,3,32,15,253,11,3,64,32,3,32,11,32,11,65,23,118,34,14,65,234,126,106,34,30,65,23,116,107,190,187,34,27,32,14,65,231,126,
      106,65,255,1,113,65,24,110,34,31,65,2,116,34,11,65,156,128,128,128,0,106,40,2,0,183,162,68,0,0,0,0,0,0,0,0,160,57,3,152,1,32,3,32,27,32,11,65,152,128,128,128,0,106,40,2,0,183,162,68,0,0,0,0,0,0,0,0,160,
      57,3,144,1,32,3,32,27,32,11,65,148,128,128,128,0,106,40,2,0,183,162,68,0,0,0,0,0,0,0,0,160,57,3,136,1,32,3,32,27,32,11,65,144,128,128,128,0,106,40,2,0,183,162,68,0,0,0,0,0,0,0,0,160,57,3,128,1,65,47,32,
      31,65,104,108,32,30,106,34,32,107,33,33,65,48,32,32,107,33,34,32,32,65,104,106,33,35,32,32,65,231,7,106,173,66,52,134,191,33,36,32,27,253,20,33,37,65,3,33,38,32,32,65,25,72,33,39,32,32,65,103,106,33,40,
      2,64,3,64,32,3,65,128,1,106,32,38,34,41,65,15,113,34,42,65,3,116,106,43,3,0,33,26,2,64,32,41,65,1,72,34,30,13,0,32,41,65,127,106,33,11,65,0,33,14,3,64,32,3,65,192,0,106,32,14,65,15,113,65,2,116,106,32,
      26,32,26,68,0,0,0,0,0,0,112,62,162,252,2,183,34,25,68,0,0,0,0,0,0,112,193,162,160,252,2,54,2,0,32,3,65,128,1,106,32,11,65,15,113,65,3,116,106,43,3,0,32,25,160,33,26,32,14,65,1,106,33,14,32,11,65,127,106,
      34,11,65,127,71,13,0,11,11,32,26,32,36,162,34,26,32,26,68,0,0,0,0,0,0,192,63,162,156,68,0,0,0,0,0,0,32,192,162,160,34,26,32,26,252,2,34,29,183,161,33,26,2,64,2,64,2,64,2,64,32,39,13,0,32,3,65,192,0,106,
      32,41,65,127,106,65,15,113,65,2,116,106,34,11,32,11,40,2,0,34,11,32,11,32,34,117,34,11,32,34,116,107,34,14,54,2,0,32,14,32,33,117,33,43,32,11,32,29,106,33,29,12,1,11,2,64,32,35,13,0,32,3,65,192,0,106,32,
      41,65,127,106,65,15,113,65,2,116,106,40,2,0,65,23,117,33,43,12,1,11,65,2,33,43,65,0,33,44,32,26,68,0,0,0,0,0,0,224,63,102,69,13,2,12,1,11,32,43,65,0,74,13,0,32,43,33,44,12,1,11,2,64,2,64,32,30,69,13,0,
      65,0,33,30,12,1,11,65,0,33,11,65,0,33,30,3,64,32,3,65,192,0,106,32,11,65,15,113,65,2,116,106,34,38,40,2,0,33,14,2,64,2,64,2,64,2,64,32,30,65,1,113,69,13,0,65,255,255,255,7,33,30,12,1,11,32,14,69,13,1,65,
      128,128,128,8,33,30,11,32,38,32,30,32,14,107,54,2,0,65,1,33,30,12,1,11,65,0,33,30,11,32,41,32,11,65,1,106,34,11,71,13,0,11,11,2,64,32,39,13,0,65,255,255,255,3,33,11,2,64,2,64,32,40,14,2,1,0,2,11,65,255,
      255,255,1,33,11,11,32,3,65,192,0,106,32,41,65,127,106,65,15,113,65,2,116,106,34,14,32,14,40,2,0,32,11,113,54,2,0,11,32,29,65,1,106,33,29,65,2,33,44,32,43,65,2,71,13,0,68,0,0,0,0,0,0,240,63,32,26,161,34,
      26,32,36,161,32,26,32,30,27,33,26,11,2,64,32,26,68,0,0,0,0,0,0,0,0,98,13,0,2,64,32,41,65,127,106,34,11,65,3,72,13,0,65,0,33,14,2,64,2,64,32,41,65,125,106,34,43,65,7,77,13,0,32,41,65,127,106,65,15,113,65,
      3,73,13,0,32,41,65,108,106,65,112,73,13,0,65,0,33,30,65,0,33,14,2,64,32,43,65,32,73,13,0,32,3,65,192,0,106,32,11,65,15,113,65,2,116,106,34,14,65,132,127,106,34,30,253,0,2,0,32,37,253,13,12,13,14,15,8,9,
      10,11,4,5,6,7,0,1,2,3,33,45,32,30,253,0,2,16,32,37,253,13,12,13,14,15,8,9,10,11,4,5,6,7,0,1,2,3,33,46,32,14,65,164,127,106,34,30,253,0,2,0,32,37,253,13,12,13,14,15,8,9,10,11,4,5,6,7,0,1,2,3,33,47,32,30,
      253,0,2,16,32,37,253,13,12,13,14,15,8,9,10,11,4,5,6,7,0,1,2,3,33,48,32,14,65,68,106,34,30,253,0,2,0,32,37,253,13,12,13,14,15,8,9,10,11,4,5,6,7,0,1,2,3,33,49,32,30,253,0,2,16,32,37,253,13,12,13,14,15,8,
      9,10,11,4,5,6,7,0,1,2,3,33,50,32,14,65,100,106,34,14,253,0,2,0,32,37,253,13,12,13,14,15,8,9,10,11,4,5,6,7,0,1,2,3,33,51,32,14,253,0,2,16,32,37,253,13,12,13,14,15,8,9,10,11,4,5,6,7,0,1,2,3,33,52,32,43,65,
      96,113,34,30,33,14,253,12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,34,53,33,54,32,53,33,55,32,53,33,56,32,53,33,57,32,53,33,58,32,53,33,59,32,53,33,60,3,64,32,46,32,59,253,80,33,59,32,48,32,57,253,80,33,57,32,50,
      32,55,253,80,33,55,32,52,32,53,253,80,33,53,32,45,32,60,253,80,33,60,32,47,32,58,253,80,33,58,32,49,32,56,253,80,33,56,32,51,32,54,253,80,33,54,32,14,65,96,106,34,14,13,0,11,32,59,32,57,32,55,32,53,253,
      80,253,80,253,80,32,60,32,58,32,56,32,54,253,80,253,80,253,80,253,80,34,53,32,53,32,37,253,13,8,9,10,11,12,13,14,15,0,1,2,3,0,1,2,3,253,80,34,53,32,53,32,37,253,13,4,5,6,7,0,1,2,3,0,1,2,3,0,1,2,3,253,80,
      253,27,0,33,14,32,43,32,30,70,13,2,32,43,65,24,113,13,0,32,11,32,30,107,33,11,12,1,11,253,12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,34,53,32,14,253,28,0,33,54,32,30,65,127,115,32,41,106,33,14,32,30,32,43,65,120,
      113,34,42,107,33,30,32,11,32,42,107,33,11,3,64,32,5,32,14,65,15,113,65,2,116,106,34,38,253,0,2,0,32,37,253,13,12,13,14,15,8,9,10,11,4,5,6,7,0,1,2,3,32,53,253,80,33,53,32,38,253,0,2,16,32,37,253,13,12,13,
      14,15,8,9,10,11,4,5,6,7,0,1,2,3,32,54,253,80,33,54,32,14,65,120,106,33,14,32,30,65,8,106,34,30,13,0,11,32,54,32,53,253,80,34,53,32,53,32,37,253,13,8,9,10,11,12,13,14,15,0,1,2,3,0,1,2,3,253,80,34,53,32,
      53,32,37,253,13,4,5,6,7,0,1,2,3,0,1,2,3,0,1,2,3,253,80,253,27,0,33,14,32,43,32,42,70,13,1,11,3,64,32,3,65,192,0,106,32,11,65,15,113,65,2,116,106,40,2,0,32,14,114,33,14,32,11,65,3,75,33,30,32,11,65,127,
      106,33,11,32,30,13,0,11,11,32,14,69,13,0,32,35,33,32,3,64,32,32,65,104,106,33,32,32,3,65,192,0,106,32,41,65,127,106,34,41,65,15,113,65,2,116,106,40,2,0,69,13,0,12,4,11,11,65,0,33,11,3,64,32,11,34,14,65,
      127,106,33,11,32,3,65,192,0,106,32,14,65,2,106,65,15,113,65,2,116,106,40,2,0,69,13,0,11,32,41,65,1,106,34,30,32,41,32,11,107,34,38,74,13,1,2,64,32,41,65,127,115,34,29,32,38,172,66,1,124,34,61,32,41,65,
      2,106,34,11,172,34,62,32,61,32,62,85,27,34,61,167,106,34,63,65,12,73,13,0,32,11,32,61,32,62,125,34,61,167,34,43,106,32,11,72,13,0,65,14,32,41,107,65,15,113,32,43,65,15,113,73,13,0,32,61,66,15,86,13,0,32,
      29,32,30,32,14,107,172,66,1,124,34,61,32,62,32,61,32,62,85,27,167,106,65,124,113,33,44,32,31,32,41,106,33,42,32,30,32,63,65,124,113,34,64,106,33,30,65,0,33,11,3,64,32,3,65,128,1,106,32,41,32,11,106,65,
      1,106,65,15,113,65,3,116,106,34,43,32,37,32,42,32,11,106,34,14,65,3,106,65,194,0,111,34,29,65,194,0,106,32,29,32,29,65,0,72,27,65,2,116,65,144,128,128,128,0,106,40,2,0,183,253,20,32,14,65,4,106,65,194,
      0,111,34,29,65,194,0,106,32,29,32,29,65,0,72,27,65,2,116,65,144,128,128,128,0,106,40,2,0,183,253,34,1,253,242,1,253,12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,34,53,253,240,1,253,11,3,16,32,43,32,37,32,14,65,1,
      106,65,194,0,111,34,29,65,194,0,106,32,29,32,29,65,0,72,27,65,2,116,65,144,128,128,128,0,106,40,2,0,183,253,20,32,14,65,2,106,65,194,0,111,34,14,65,194,0,106,32,14,32,14,65,0,72,27,65,2,116,65,144,128,
      128,128,0,106,40,2,0,183,253,34,1,253,242,1,32,53,253,240,1,253,11,3,0,32,44,32,11,65,4,106,34,11,71,13,0,11,32,63,32,64,70,13,2,11,3,64,32,3,65,128,1,106,32,30,65,15,113,65,3,116,106,32,27,32,31,32,30,
      106,65,194,0,111,34,11,65,194,0,106,32,11,32,11,65,0,72,27,65,2,116,65,144,128,128,128,0,106,40,2,0,183,162,68,0,0,0,0,0,0,0,0,160,57,3,0,32,30,65,1,106,34,30,32,38,76,13,0,12,2,11,11,11,2,64,2,64,32,26,
      65,151,8,32,32,107,173,66,52,134,191,162,34,26,68,0,0,0,0,0,0,112,65,102,69,13,0,32,3,65,192,0,106,32,42,65,2,116,106,32,26,32,26,68,0,0,0,0,0,0,112,62,162,252,2,34,11,183,68,0,0,0,0,0,0,112,193,162,160,
      252,2,54,2,0,32,41,65,1,106,34,41,65,15,113,33,42,12,1,11,32,26,252,2,33,11,32,35,33,32,11,32,3,65,192,0,106,32,42,65,2,116,106,32,11,54,2,0,11,2,64,2,64,2,64,2,64,32,32,65,128,8,72,13,0,32,32,65,254,15,
      75,13,1,32,32,65,129,120,106,33,32,68,0,0,0,0,0,0,224,127,33,26,12,3,11,32,32,65,130,120,72,13,1,68,0,0,0,0,0,0,240,63,33,26,12,2,11,32,32,65,253,23,32,32,65,253,23,73,27,65,130,112,106,33,32,68,0,0,0,
      0,0,0,240,127,33,26,12,1,11,2,64,32,32,65,184,112,77,13,0,32,32,65,201,7,106,33,32,68,0,0,0,0,0,0,96,3,33,26,12,1,11,32,32,65,240,104,32,32,65,240,104,75,27,65,146,15,106,33,32,68,0,0,0,0,0,0,0,0,33,26,
      11,2,64,2,64,32,41,65,0,78,13,0,68,0,0,0,0,0,0,0,0,33,26,12,1,11,32,26,32,32,65,255,7,106,173,66,52,134,191,162,33,26,32,41,33,11,3,64,32,3,65,128,1,106,32,11,65,15,113,34,14,65,3,116,106,32,26,32,3,65,
      192,0,106,32,14,65,2,116,106,40,2,0,183,162,57,3,0,32,26,68,0,0,0,0,0,0,112,62,162,33,26,32,11,65,127,106,34,11,65,127,71,13,0,11,65,0,33,31,32,41,33,30,3,64,32,31,65,3,32,31,65,3,73,27,65,1,106,33,38,
      68,0,0,0,0,0,0,0,0,33,26,32,3,65,128,3,106,33,11,65,0,33,14,3,64,32,26,32,3,65,128,1,106,32,30,32,14,106,65,15,113,65,3,116,106,43,3,0,32,11,43,3,0,162,160,33,26,32,11,65,8,106,33,11,32,38,32,14,65,1,106,
      34,14,71,13,0,11,32,3,65,128,2,106,32,41,32,30,107,65,15,113,65,3,116,106,32,26,57,3,0,32,30,65,127,106,33,30,32,31,32,41,71,33,11,32,31,65,1,106,33,31,32,11,13,0,11,68,0,0,0,0,0,0,0,0,33,26,3,64,32,26,
      32,3,65,128,2,106,32,41,65,15,113,65,3,116,106,43,3,0,160,33,26,32,41,65,127,106,34,41,65,127,71,13,0,11,11,32,26,154,32,26,32,44,27,33,26,32,24,65,127,74,13,0,65,0,32,29,107,33,29,32,26,154,33,26,11,2,
      64,2,64,2,64,2,64,32,29,65,3,113,14,4,0,1,2,3,0,11,32,26,32,26,32,26,162,34,25,162,34,27,32,25,32,25,162,162,32,25,68,167,70,59,140,135,205,198,62,162,68,116,231,202,226,249,0,42,191,160,162,32,26,32,27,
      32,25,68,178,251,110,137,16,17,129,63,162,68,119,172,203,84,85,85,197,191,160,162,160,160,182,33,28,12,4,11,32,26,32,26,162,34,26,68,129,94,12,253,255,255,223,191,162,68,0,0,0,0,0,0,240,63,160,32,26,32,
      26,162,34,25,68,66,58,5,225,83,85,165,63,162,160,32,26,32,25,162,32,26,68,105,80,238,224,66,147,249,62,162,68,39,30,15,232,135,192,86,191,160,162,160,182,33,28,12,3,11,32,26,32,26,162,34,25,32,26,154,162,
      34,27,32,25,32,25,162,162,32,25,68,167,70,59,140,135,205,198,62,162,68,116,231,202,226,249,0,42,191,160,162,32,27,32,25,68,178,251,110,137,16,17,129,63,162,68,119,172,203,84,85,85,197,191,160,162,32,26,
      161,160,182,33,28,12,2,11,32,26,32,26,162,34,26,68,129,94,12,253,255,255,223,191,162,68,0,0,0,0,0,0,240,63,160,32,26,32,26,162,34,25,68,66,58,5,225,83,85,165,63,162,160,32,26,32,25,162,32,26,68,105,80,
      238,224,66,147,249,62,162,68,39,30,15,232,135,192,86,191,160,162,160,182,140,33,28,12,1,11,68,0,0,0,0,0,0,240,63,32,26,68,210,33,51,127,124,217,18,64,160,34,25,32,25,162,34,25,68,129,94,12,253,255,255,
      223,63,162,161,32,25,32,25,162,34,27,68,66,58,5,225,83,85,165,63,162,160,32,25,32,27,162,32,25,68,105,80,238,224,66,147,249,62,162,68,39,30,15,232,135,192,86,191,160,162,160,182,68,0,0,0,0,0,0,240,63,32,
      26,68,210,33,51,127,124,217,18,192,160,34,26,32,26,162,34,26,68,129,94,12,253,255,255,223,63,162,161,32,26,32,26,162,34,25,68,66,58,5,225,83,85,165,63,162,160,32,26,32,25,162,32,26,68,105,80,238,224,66,
      147,249,62,162,68,39,30,15,232,135,192,86,191,160,162,160,182,140,32,24,65,0,72,27,33,28,11,32,13,32,13,146,67,0,0,128,191,146,33,23,2,64,2,64,67,0,0,128,63,67,0,0,0,0,32,12,32,12,67,0,0,0,0,93,27,32,22,
      67,0,0,128,63,94,27,34,12,67,250,126,170,62,93,69,13,0,32,12,67,250,126,170,62,149,34,12,32,23,148,67,0,0,128,63,32,12,147,32,28,148,146,33,12,12,1,11,67,0,0,128,63,67,0,0,128,191,32,13,67,0,0,0,63,93,
      27,33,22,2,64,32,12,67,250,126,42,63,93,69,13,0,32,12,67,250,126,170,190,146,67,250,126,170,62,149,34,12,32,22,148,67,0,0,128,63,32,12,147,32,23,148,146,33,12,12,1,11,67,0,0,128,63,32,12,67,250,126,42,
      191,146,67,12,2,171,62,149,34,12,147,32,22,148,32,12,32,13,67,0,0,0,191,146,139,67,0,0,128,64,148,67,0,0,128,191,146,148,146,33,12,11,2,64,32,16,32,18,149,32,13,146,34,13,67,0,0,128,63,96,69,13,0,3,64,
      32,13,67,0,0,128,191,146,34,13,67,0,0,128,63,96,13,0,11,11,32,20,32,13,56,2,20,2,64,32,13,67,0,0,0,0,93,69,13,0,3,64,32,13,67,0,0,128,63,146,34,13,67,0,0,0,0,93,13,0,11,32,20,32,13,56,2,20,11,32,20,65,
      1,54,2,24,32,12,67,0,0,0,0,146,33,13,11,32,20,32,20,42,2,64,34,23,56,2,36,32,20,32,20,42,2,68,34,22,56,2,40,32,20,32,20,42,2,72,34,12,56,2,44,32,20,32,20,42,2,76,34,16,56,2,48,2,64,2,64,32,20,40,2,52,65,
      127,71,13,0,67,0,0,0,0,33,16,12,1,11,32,20,40,2,32,33,11,2,64,2,64,2,64,2,64,2,64,2,64,2,64,2,64,2,64,32,19,69,13,0,32,11,14,5,1,2,3,4,1,7,11,32,11,65,123,113,13,4,32,11,65,127,106,14,4,1,2,3,5,6,11,32,
      20,65,1,54,2,32,11,32,20,67,0,0,128,63,67,0,0,128,63,32,23,32,18,148,34,16,149,32,16,67,0,0,128,63,93,27,32,20,42,2,28,146,34,16,56,2,28,32,16,67,0,0,128,63,96,69,13,5,32,20,66,128,128,128,252,35,55,2,
      28,67,0,0,128,63,33,16,12,5,11,32,20,32,20,42,2,28,67,0,0,128,63,67,0,0,128,63,32,12,147,32,22,32,18,148,34,16,149,32,16,67,0,0,128,63,93,27,147,34,16,56,2,28,32,16,32,12,95,69,13,4,32,20,65,3,54,2,32,
      11,32,20,32,12,56,2,28,32,12,33,16,12,3,11,32,20,65,4,54,2,32,11,32,20,32,20,42,2,28,34,12,32,12,32,12,32,16,32,18,148,34,16,149,32,16,67,0,0,128,63,93,27,147,34,16,56,2,28,32,16,67,0,0,0,0,95,69,13,1,
      32,20,66,0,55,2,28,67,0,0,0,0,33,16,12,1,11,32,20,42,2,28,33,16,11,32,20,65,1,54,2,52,32,16,67,0,0,0,0,146,33,16,11,32,21,32,21,42,2,4,32,13,32,16,148,32,20,42,2,56,148,146,56,2,4,32,17,65,1,106,34,17,
      65,8,71,13,0,11,32,1,32,0,40,2,4,65,2,116,106,32,3,42,2,60,32,3,42,2,52,32,3,42,2,44,32,3,42,2,36,32,3,42,2,28,32,3,42,2,20,32,3,42,2,12,32,3,42,2,4,67,0,0,0,0,146,146,146,146,146,146,146,146,56,2,0,32,
      0,32,0,40,2,4,65,1,106,34,11,54,2,4,32,11,32,2,71,13,0,11,11,32,0,65,0,54,2,4,32,3,65,192,3,106,36,128,128,128,128,0,11,11,156,130,128,128,0,2,0,65,0,11,8,0,0,0,0,0,0,0,0,0,65,16,11,136,2,131,249,162,0,
      68,78,110,0,252,41,21,0,209,87,39,0,221,52,245,0,98,219,192,0,60,153,149,0,65,144,67,0,99,81,254,0,187,222,171,0,183,97,197,0,58,110,36,0,210,77,66,0,73,6,224,0,9,234,46,0,28,146,209,0,235,29,254,0,41,
      177,28,0,232,62,167,0,245,53,130,0,68,187,46,0,156,233,132,0,180,38,112,0,65,126,95,0,214,145,57,0,83,131,57,0,156,244,57,0,139,95,132,0,40,249,189,0,248,31,59,0,222,255,151,0,15,152,5,0,17,47,239,0,10,
      90,139,0,109,31,109,0,207,126,54,0,9,203,39,0,70,79,183,0,158,102,63,0,45,234,95,0,186,39,117,0,229,235,199,0,61,123,241,0,247,57,7,0,146,82,138,0,251,107,234,0,31,177,95,0,8,93,141,0,48,3,86,0,123,252,
      70,0,240,171,107,0,32,188,207,0,54,244,154,0,227,169,29,0,94,97,145,0,8,27,230,0,133,153,101,0,160,20,95,0,141,64,104,0,128,216,255,0,39,115,77,0,6,6,49,0,202,86,21,0,201,168,115,0,123,226,96,0,107,140,
      192,0,0,162,131,128,128,0,7,108,105,110,107,105,110,103,2,8,220,130,128,128,0,15,0,32,0,17,95,115,101,110,100,69,118,101,110,116,95,109,105,100,105,73,110,0,2,1,67,46,76,115,116,100,95,95,105,110,116,114,
      105,110,115,105,99,115,95,95,105,110,116,101,114,110,97,108,95,95,109,97,116,104,95,105,109,112,108,101,109,101,110,116,97,116,105,111,110,115,95,95,104,101,108,112,101,114,115,95,95,115,99,97,108,98,110,
      102,0,32,2,16,95,115,101,116,86,97,108,117,101,95,118,111,108,117,109,101,0,32,3,27,95,115,101,116,86,97,108,117,101,95,119,97,118,101,116,97,98,108,101,80,111,115,105,116,105,111,110,0,32,4,20,95,115,
      101,116,86,97,108,117,101,95,109,111,114,112,104,83,112,101,101,100,0,32,5,20,95,115,101,116,86,97,108,117,101,95,109,111,114,112,104,68,101,112,116,104,0,32,6,16,95,115,101,116,86,97,108,117,101,95,97,
      116,116,97,99,107,0,32,7,15,95,115,101,116,86,97,108,117,101,95,100,101,99,97,121,0,32,8,17,95,115,101,116,86,97,108,117,101,95,115,117,115,116,97,105,110,0,32,9,17,95,115,101,116,86,97,108,117,101,95,
      114,101,108,101,97,115,101,0,32,10,10,105,110,105,116,105,97,108,105,115,101,1,2,14,46,76,103,95,95,102,114,101,113,117,101,110,99,121,0,0,8,0,32,11,12,97,100,118,97,110,99,101,66,108,111,99,107,2,16,0,
      1,2,15,46,76,103,95,95,95,99,111,110,115,116,97,110,116,95,1,0,136,2,5,177,128,128,128,0,2,19,46,98,115,115,46,46,76,103,95,95,102,114,101,113,117,101,110,99,121,3,0,23,46,114,111,100,97,116,97,46,46,76,
      103,95,95,95,99,111,110,115,116,97,110,116,95,4,0,0,217,128,128,128,0,10,114,101,108,111,99,46,67,79,68,69,5,16,0,144,28,1,3,206,35,11,0,7,138,36,13,7,150,36,13,3,226,42,11,0,3,133,47,11,0,4,202,55,14,
      12,4,234,55,14,8,4,138,56,14,4,4,170,56,14,0,4,195,70,14,0,4,234,70,14,0,4,180,71,14,0,4,219,71,14,0,4,183,72,14,0,7,170,88,13,0,157,129,128,128,0,15,116,97,114,103,101,116,95,102,101,97,116,117,114,101,
      115,9,43,11,98,117,108,107,45,109,101,109,111,114,121,43,15,98,117,108,107,45,109,101,109,111,114,121,45,111,112,116,43,22,99,97,108,108,45,105,110,100,105,114,101,99,116,45,111,118,101,114,108,111,110,
      103,43,10,109,117,108,116,105,118,97,108,117,101,43,15,109,117,116,97,98,108,101,45,103,108,111,98,97,108,115,43,19,110,111,110,116,114,97,112,112,105,110,103,45,102,112,116,111,105,110,116,43,15,114,101,
      102,101,114,101,110,99,101,45,116,121,112,101,115,43,8,115,105,103,110,45,101,120,116,43,7,115,105,109,100,49,50,56,]);
  }

  /** @access private */
  _getWasmBytesNonSIMD()
  {
    return new Uint8Array([0,97,115,109,1,0,0,0,1,153,128,128,128,0,4,96,2,127,127,0,96,2,125,127,1,125,96,3,127,127,127,0,96,4,127,127,127,124,0,2,175,128,128,128,0,2,3,101,110,118,15,95,95,108,105,110,101,
      97,114,95,109,101,109,111,114,121,2,0,1,3,101,110,118,15,95,95,115,116,97,99,107,95,112,111,105,110,116,101,114,3,127,1,3,141,128,128,128,0,12,0,1,2,2,2,2,2,2,2,2,3,2,7,221,129,128,128,0,11,17,95,115,101,
      110,100,69,118,101,110,116,95,109,105,100,105,73,110,0,0,16,95,115,101,116,86,97,108,117,101,95,118,111,108,117,109,101,0,2,27,95,115,101,116,86,97,108,117,101,95,119,97,118,101,116,97,98,108,101,80,111,
      115,105,116,105,111,110,0,3,20,95,115,101,116,86,97,108,117,101,95,109,111,114,112,104,83,112,101,101,100,0,4,20,95,115,101,116,86,97,108,117,101,95,109,111,114,112,104,68,101,112,116,104,0,5,16,95,115,
      101,116,86,97,108,117,101,95,97,116,116,97,99,107,0,6,15,95,115,101,116,86,97,108,117,101,95,100,101,99,97,121,0,7,17,95,115,101,116,86,97,108,117,101,95,115,117,115,116,97,105,110,0,8,17,95,115,101,116,
      86,97,108,117,101,95,114,101,108,101,97,115,101,0,9,10,105,110,105,116,105,97,108,105,115,101,0,10,12,97,100,118,97,110,99,101,66,108,111,99,107,0,11,12,129,128,128,128,0,2,10,218,218,128,128,0,12,188,
      28,4,4,127,5,125,1,126,1,125,2,64,2,64,2,64,2,64,32,1,40,2,0,34,1,65,128,128,192,7,113,34,2,65,128,128,192,4,71,13,0,32,1,65,255,1,113,69,13,0,32,0,65,7,65,6,65,5,65,4,65,3,65,2,32,0,40,2,176,5,34,2,32,
      0,40,2,160,5,34,3,72,34,4,32,0,40,2,192,5,34,5,32,2,32,3,32,4,27,34,2,72,34,3,27,32,0,40,2,208,5,34,4,32,5,32,2,32,3,27,34,2,72,34,3,27,32,0,40,2,224,5,34,5,32,4,32,2,32,3,27,34,2,72,34,3,27,32,0,40,2,
      240,5,34,4,32,5,32,2,32,3,27,34,2,72,34,3,27,32,0,40,2,128,6,34,5,32,4,32,2,32,3,27,34,2,72,34,3,27,32,0,40,2,144,6,32,5,32,2,32,3,27,72,27,34,3,65,4,116,106,34,2,32,1,65,16,118,65,15,113,54,2,156,5,32,
      2,65,1,59,0,152,5,32,2,32,1,65,8,118,65,255,0,113,34,4,179,34,6,56,2,164,5,32,0,32,3,65,208,0,108,106,34,3,32,6,56,2,28,32,0,32,0,40,2,152,6,65,1,106,34,5,54,2,152,6,32,2,32,5,54,2,160,5,32,3,65,24,106,
      33,0,32,1,65,255,0,113,179,67,4,2,1,60,148,33,7,2,64,32,4,65,187,127,106,178,67,171,170,170,61,148,34,8,188,34,2,65,255,255,255,255,7,113,34,1,13,0,67,0,0,128,63,33,6,12,4,11,2,64,32,1,65,129,128,128,252,
      7,73,13,0,32,8,67,0,0,0,64,146,33,6,12,4,11,2,64,2,64,32,1,65,128,128,128,252,3,70,13,0,32,1,65,128,128,128,252,7,71,13,1,32,8,67,0,0,0,0,32,2,65,127,74,27,33,6,12,5,11,67,0,0,0,64,67,0,0,0,63,32,2,65,
      127,74,27,33,6,12,4,11,32,2,65,128,128,128,248,3,70,13,2,2,64,32,2,65,128,128,128,128,4,71,13,0,67,0,0,128,64,33,6,12,4,11,2,64,32,1,65,129,128,128,232,4,73,13,0,67,0,0,128,127,67,0,0,0,0,32,2,65,0,74,
      27,33,6,12,4,11,67,0,0,128,127,33,6,32,8,67,0,0,0,0,148,32,8,32,2,65,128,96,113,190,34,9,147,146,34,10,32,9,146,34,8,188,34,1,65,128,128,128,152,4,74,13,3,2,64,32,1,65,128,128,128,152,4,71,13,0,32,10,67,
      60,170,56,51,146,32,8,32,9,147,94,13,4,32,8,188,65,255,255,255,255,7,113,33,2,12,2,11,67,0,0,0,0,33,6,32,8,188,65,255,255,255,255,7,113,34,2,65,128,128,216,152,4,75,13,3,32,1,65,128,128,216,152,124,71,
      13,1,32,10,32,8,32,9,147,95,69,13,1,12,3,11,2,64,2,64,2,64,2,64,32,2,65,128,128,128,4,70,13,0,32,1,65,255,129,192,7,113,65,128,128,192,4,71,13,1,11,32,1,65,16,118,65,15,113,33,2,32,1,65,8,118,65,255,0,
      113,179,33,6,32,0,40,2,156,5,33,1,2,64,2,64,32,0,45,0,160,6,13,0,66,1,32,2,173,134,33,11,32,1,32,2,71,13,3,32,0,42,2,164,5,32,6,92,13,3,32,0,41,3,168,6,32,11,131,80,13,1,32,0,65,1,58,0,153,5,12,3,11,2,
      64,32,1,32,2,71,13,0,32,0,42,2,164,5,32,6,92,13,0,32,0,65,1,58,0,153,5,11,2,64,32,0,40,2,172,5,32,2,71,13,0,32,0,42,2,180,5,32,6,92,13,0,32,0,65,1,58,0,169,5,11,2,64,32,0,40,2,188,5,32,2,71,13,0,32,0,42,
      2,196,5,32,6,92,13,0,32,0,65,1,58,0,185,5,11,2,64,32,0,40,2,204,5,32,2,71,13,0,32,0,42,2,212,5,32,6,92,13,0,32,0,65,1,58,0,201,5,11,2,64,32,0,40,2,220,5,32,2,71,13,0,32,0,42,2,228,5,32,6,92,13,0,32,0,65,
      1,58,0,217,5,11,2,64,32,0,40,2,236,5,32,2,71,13,0,32,0,42,2,244,5,32,6,92,13,0,32,0,65,1,58,0,233,5,11,2,64,32,0,40,2,252,5,32,2,71,13,0,32,0,42,2,132,6,32,6,92,13,0,32,0,65,1,58,0,249,5,11,32,0,40,2,140,
      6,32,2,71,13,3,32,0,42,2,148,6,32,6,92,13,3,32,0,65,1,58,0,137,6,15,11,2,64,32,0,42,2,28,32,6,92,13,0,32,0,65,0,54,2,36,11,32,0,65,0,58,0,152,5,32,0,32,0,40,2,156,6,65,1,106,34,1,54,2,156,6,32,0,32,1,54,
      2,160,5,12,1,11,32,2,65,128,128,192,5,71,13,1,32,1,65,8,118,65,255,0,113,34,2,65,202,0,70,13,1,32,2,65,192,0,71,13,1,66,1,32,1,65,16,118,65,15,113,34,2,173,134,33,11,2,64,32,1,65,255,0,113,179,67,4,2,1,
      60,148,67,0,0,0,63,96,69,13,0,32,0,32,0,41,3,168,6,32,11,132,55,3,168,6,32,2,13,2,32,0,65,1,58,0,160,6,15,11,32,0,32,0,41,3,168,6,32,11,66,127,133,131,55,3,168,6,2,64,32,2,69,13,0,2,64,32,0,40,2,156,5,
      32,2,71,13,0,32,0,45,0,152,5,69,13,0,32,0,45,0,153,5,69,13,0,2,64,32,0,42,2,164,5,32,0,42,2,28,92,13,0,32,0,65,0,54,2,36,11,32,0,65,0,58,0,152,5,32,0,32,0,40,2,156,6,65,1,106,34,1,54,2,156,6,32,0,32,1,
      54,2,160,5,11,2,64,32,0,40,2,172,5,32,2,71,13,0,32,0,45,0,168,5,69,13,0,32,0,45,0,169,5,69,13,0,2,64,32,0,42,2,180,5,32,0,42,2,108,92,13,0,32,0,65,0,54,2,116,11,32,0,65,0,58,0,168,5,32,0,32,0,40,2,156,
      6,65,1,106,34,1,54,2,156,6,32,0,32,1,54,2,176,5,11,2,64,32,0,40,2,188,5,32,2,71,13,0,32,0,45,0,184,5,69,13,0,32,0,45,0,185,5,69,13,0,2,64,32,0,42,2,196,5,32,0,42,2,188,1,92,13,0,32,0,65,0,54,2,196,1,11,
      32,0,65,0,58,0,184,5,32,0,32,0,40,2,156,6,65,1,106,34,1,54,2,156,6,32,0,32,1,54,2,192,5,11,2,64,32,0,40,2,204,5,32,2,71,13,0,32,0,45,0,200,5,69,13,0,32,0,45,0,201,5,69,13,0,2,64,32,0,42,2,212,5,32,0,42,
      2,140,2,92,13,0,32,0,65,0,54,2,148,2,11,32,0,65,0,58,0,200,5,32,0,32,0,40,2,156,6,65,1,106,34,1,54,2,156,6,32,0,32,1,54,2,208,5,11,2,64,32,0,40,2,220,5,32,2,71,13,0,32,0,45,0,216,5,69,13,0,32,0,45,0,217,
      5,69,13,0,2,64,32,0,42,2,228,5,32,0,42,2,220,2,92,13,0,32,0,65,0,54,2,228,2,11,32,0,65,0,58,0,216,5,32,0,32,0,40,2,156,6,65,1,106,34,1,54,2,156,6,32,0,32,1,54,2,224,5,11,2,64,32,0,40,2,236,5,32,2,71,13,
      0,32,0,45,0,232,5,69,13,0,32,0,45,0,233,5,69,13,0,2,64,32,0,42,2,244,5,32,0,42,2,172,3,92,13,0,32,0,65,0,54,2,180,3,11,32,0,65,0,58,0,232,5,32,0,32,0,40,2,156,6,65,1,106,34,1,54,2,156,6,32,0,32,1,54,2,
      240,5,11,2,64,32,0,40,2,252,5,32,2,71,13,0,32,0,45,0,248,5,69,13,0,32,0,45,0,249,5,69,13,0,2,64,32,0,42,2,132,6,32,0,42,2,252,3,92,13,0,32,0,65,0,54,2,132,4,11,32,0,65,0,58,0,248,5,32,0,32,0,40,2,156,6,
      65,1,106,34,1,54,2,156,6,32,0,32,1,54,2,128,6,11,32,0,40,2,140,6,32,2,71,13,2,32,0,45,0,136,6,69,13,2,32,0,45,0,137,6,69,13,2,2,64,32,0,42,2,148,6,32,0,42,2,204,4,92,13,0,32,0,65,0,54,2,212,4,11,32,0,65,
      0,58,0,136,6,32,0,32,0,40,2,156,6,65,1,106,34,1,54,2,156,6,32,0,32,1,54,2,144,6,15,11,32,0,65,0,58,0,160,6,2,64,32,0,45,0,152,5,69,13,0,32,0,45,0,153,5,69,13,0,2,64,32,0,42,2,164,5,32,0,42,2,28,92,13,0,
      32,0,65,0,54,2,36,11,32,0,65,0,58,0,152,5,32,0,32,0,40,2,156,6,65,1,106,34,1,54,2,156,6,32,0,32,1,54,2,160,5,11,2,64,32,0,45,0,168,5,69,13,0,32,0,45,0,169,5,69,13,0,2,64,32,0,42,2,180,5,32,0,42,2,108,92,
      13,0,32,0,65,0,54,2,116,11,32,0,65,0,58,0,168,5,32,0,32,0,40,2,156,6,65,1,106,34,1,54,2,156,6,32,0,32,1,54,2,176,5,11,2,64,32,0,45,0,184,5,69,13,0,32,0,45,0,185,5,69,13,0,2,64,32,0,42,2,196,5,32,0,42,2,
      188,1,92,13,0,32,0,65,0,54,2,196,1,11,32,0,65,0,58,0,184,5,32,0,32,0,40,2,156,6,65,1,106,34,1,54,2,156,6,32,0,32,1,54,2,192,5,11,2,64,32,0,45,0,200,5,69,13,0,32,0,45,0,201,5,69,13,0,2,64,32,0,42,2,212,
      5,32,0,42,2,140,2,92,13,0,32,0,65,0,54,2,148,2,11,32,0,65,0,58,0,200,5,32,0,32,0,40,2,156,6,65,1,106,34,1,54,2,156,6,32,0,32,1,54,2,208,5,11,2,64,32,0,45,0,216,5,69,13,0,32,0,45,0,217,5,69,13,0,2,64,32,
      0,42,2,228,5,32,0,42,2,220,2,92,13,0,32,0,65,0,54,2,228,2,11,32,0,65,0,58,0,216,5,32,0,32,0,40,2,156,6,65,1,106,34,1,54,2,156,6,32,0,32,1,54,2,224,5,11,2,64,32,0,45,0,232,5,69,13,0,32,0,45,0,233,5,69,13,
      0,2,64,32,0,42,2,244,5,32,0,42,2,172,3,92,13,0,32,0,65,0,54,2,180,3,11,32,0,65,0,58,0,232,5,32,0,32,0,40,2,156,6,65,1,106,34,1,54,2,156,6,32,0,32,1,54,2,240,5,11,2,64,32,0,45,0,248,5,69,13,0,32,0,45,0,
      249,5,69,13,0,2,64,32,0,42,2,132,6,32,0,42,2,252,3,92,13,0,32,0,65,0,54,2,132,4,11,32,0,65,0,58,0,248,5,32,0,32,0,40,2,156,6,65,1,106,34,1,54,2,156,6,32,0,32,1,54,2,128,6,11,32,0,45,0,136,6,69,13,1,32,
      0,45,0,137,6,69,13,1,2,64,32,0,42,2,148,6,32,0,42,2,204,4,92,13,0,32,0,65,0,54,2,212,4,11,32,0,65,0,58,0,136,6,32,0,32,0,40,2,156,6,65,1,106,34,1,54,2,156,6,32,0,32,1,54,2,144,6,12,1,11,2,64,32,0,40,2,
      172,5,32,2,71,13,0,32,0,42,2,180,5,32,6,92,13,0,2,64,32,0,41,3,168,6,32,11,131,80,13,0,32,0,65,1,58,0,169,5,12,1,11,2,64,32,0,42,2,108,32,6,92,13,0,32,0,65,0,54,2,116,11,32,0,65,0,58,0,168,5,32,0,32,0,
      40,2,156,6,65,1,106,34,1,54,2,156,6,32,0,32,1,54,2,176,5,11,2,64,32,0,40,2,188,5,32,2,71,13,0,32,0,42,2,196,5,32,6,92,13,0,2,64,32,0,41,3,168,6,32,11,131,80,13,0,32,0,65,1,58,0,185,5,12,1,11,2,64,32,0,
      42,2,188,1,32,6,92,13,0,32,0,65,0,54,2,196,1,11,32,0,65,0,58,0,184,5,32,0,32,0,40,2,156,6,65,1,106,34,1,54,2,156,6,32,0,32,1,54,2,192,5,11,2,64,32,0,40,2,204,5,32,2,71,13,0,32,0,42,2,212,5,32,6,92,13,0,
      2,64,32,0,41,3,168,6,32,11,131,80,13,0,32,0,65,1,58,0,201,5,12,1,11,2,64,32,0,42,2,140,2,32,6,92,13,0,32,0,65,0,54,2,148,2,11,32,0,65,0,58,0,200,5,32,0,32,0,40,2,156,6,65,1,106,34,1,54,2,156,6,32,0,32,
      1,54,2,208,5,11,2,64,32,0,40,2,220,5,32,2,71,13,0,32,0,42,2,228,5,32,6,92,13,0,2,64,32,0,41,3,168,6,32,11,131,80,13,0,32,0,65,1,58,0,217,5,12,1,11,2,64,32,0,42,2,220,2,32,6,92,13,0,32,0,65,0,54,2,228,2,
      11,32,0,65,0,58,0,216,5,32,0,32,0,40,2,156,6,65,1,106,34,1,54,2,156,6,32,0,32,1,54,2,224,5,11,2,64,32,0,40,2,236,5,32,2,71,13,0,32,0,42,2,244,5,32,6,92,13,0,2,64,32,0,41,3,168,6,32,11,131,80,13,0,32,0,
      65,1,58,0,233,5,12,1,11,2,64,32,0,42,2,172,3,32,6,92,13,0,32,0,65,0,54,2,180,3,11,32,0,65,0,58,0,232,5,32,0,32,0,40,2,156,6,65,1,106,34,1,54,2,156,6,32,0,32,1,54,2,240,5,11,2,64,32,0,40,2,252,5,32,2,71,
      13,0,32,0,42,2,132,6,32,6,92,13,0,2,64,32,0,41,3,168,6,32,11,131,80,13,0,32,0,65,1,58,0,249,5,12,1,11,2,64,32,0,42,2,252,3,32,6,92,13,0,32,0,65,0,54,2,132,4,11,32,0,65,0,58,0,248,5,32,0,32,0,40,2,156,6,
      65,1,106,34,1,54,2,156,6,32,0,32,1,54,2,128,6,11,32,0,40,2,140,6,32,2,71,13,0,32,0,42,2,148,6,32,6,92,13,0,2,64,32,0,41,3,168,6,32,11,131,80,13,0,32,0,65,1,58,0,137,6,15,11,2,64,32,0,42,2,204,4,32,6,92,
      13,0,32,0,65,0,54,2,212,4,11,32,0,65,0,58,0,136,6,32,0,32,0,40,2,156,6,65,1,106,34,1,54,2,156,6,32,0,32,1,54,2,144,6,15,11,15,11,65,0,33,3,2,64,32,2,65,128,128,128,248,3,77,13,0,65,0,65,128,128,128,4,32,
      2,65,23,118,65,130,127,106,118,32,1,106,34,2,65,255,255,255,3,113,65,128,128,128,4,114,65,150,1,32,2,65,23,118,65,255,1,113,34,4,107,118,34,3,107,32,3,32,1,65,0,72,27,33,3,32,10,32,9,65,128,128,128,124,
      32,4,65,129,127,106,117,32,2,113,190,147,34,9,146,188,33,1,11,2,64,32,3,65,23,116,32,1,65,128,128,126,113,190,34,6,67,0,114,49,63,148,34,12,32,6,67,140,190,191,53,148,32,10,32,6,32,9,147,147,67,24,114,
      49,63,148,146,34,9,146,34,6,32,6,32,6,32,6,32,6,148,34,8,32,8,32,8,32,8,32,8,67,76,187,49,51,148,67,14,234,221,181,146,148,67,85,179,138,56,146,148,67,97,11,54,187,146,148,67,171,170,42,62,146,148,147,
      34,8,148,32,8,67,0,0,0,192,146,149,32,9,32,6,32,12,147,147,34,8,32,6,32,8,148,146,147,147,67,0,0,128,63,146,34,6,188,106,34,1,65,255,255,255,3,74,13,0,32,6,32,3,16,129,128,128,128,0,33,6,12,2,11,32,1,190,
      33,6,12,1,11,67,243,4,181,63,33,6,11,32,0,32,7,56,2,12,32,0,32,6,67,0,0,220,67,148,56,2,8,11,160,1,0,2,64,2,64,2,64,32,1,65,128,1,72,13,0,32,0,67,0,0,0,127,148,33,0,32,1,65,254,1,75,13,1,32,1,65,129,127,
      106,33,1,12,2,11,32,1,65,130,127,78,13,1,32,0,67,0,0,128,12,148,33,0,2,64,32,1,65,155,126,77,13,0,32,1,65,230,0,106,33,1,12,2,11,32,0,67,0,0,128,12,148,33,0,32,1,65,182,125,32,1,65,182,125,75,27,65,204,
      1,106,33,1,12,1,11,32,0,67,0,0,0,127,148,33,0,32,1,65,253,2,32,1,65,253,2,73,27,65,130,126,106,33,1,11,32,0,32,1,65,23,116,65,128,128,128,252,3,106,190,148,11,72,1,1,125,2,64,32,0,40,2,232,6,13,0,32,0,
      32,0,40,2,0,65,1,106,54,2,0,11,32,1,42,2,0,33,3,32,0,32,2,65,1,32,2,65,1,75,27,34,2,54,2,232,6,32,0,32,3,32,0,42,2,224,6,147,32,2,178,149,56,2,228,6,11,72,1,1,125,2,64,32,0,40,2,244,6,13,0,32,0,32,0,40,
      2,0,65,1,106,54,2,0,11,32,1,42,2,0,33,3,32,0,32,2,65,1,32,2,65,1,75,27,34,2,54,2,244,6,32,0,32,3,32,0,42,2,236,6,147,32,2,178,149,56,2,240,6,11,72,1,1,125,2,64,32,0,40,2,128,7,13,0,32,0,32,0,40,2,0,65,
      1,106,54,2,0,11,32,1,42,2,0,33,3,32,0,32,2,65,1,32,2,65,1,75,27,34,2,54,2,128,7,32,0,32,3,32,0,42,2,248,6,147,32,2,178,149,56,2,252,6,11,72,1,1,125,2,64,32,0,40,2,140,7,13,0,32,0,32,0,40,2,0,65,1,106,54,
      2,0,11,32,1,42,2,0,33,3,32,0,32,2,65,1,32,2,65,1,75,27,34,2,54,2,140,7,32,0,32,3,32,0,42,2,132,7,147,32,2,178,149,56,2,136,7,11,72,1,1,125,2,64,32,0,40,2,152,7,13,0,32,0,32,0,40,2,0,65,1,106,54,2,0,11,
      32,1,42,2,0,33,3,32,0,32,2,65,1,32,2,65,1,75,27,34,2,54,2,152,7,32,0,32,3,32,0,42,2,144,7,147,32,2,178,149,56,2,148,7,11,72,1,1,125,2,64,32,0,40,2,164,7,13,0,32,0,32,0,40,2,0,65,1,106,54,2,0,11,32,1,42,
      2,0,33,3,32,0,32,2,65,1,32,2,65,1,75,27,34,2,54,2,164,7,32,0,32,3,32,0,42,2,156,7,147,32,2,178,149,56,2,160,7,11,72,1,1,125,2,64,32,0,40,2,176,7,13,0,32,0,32,0,40,2,0,65,1,106,54,2,0,11,32,1,42,2,0,33,
      3,32,0,32,2,65,1,32,2,65,1,75,27,34,2,54,2,176,7,32,0,32,3,32,0,42,2,168,7,147,32,2,178,149,56,2,172,7,11,72,1,1,125,2,64,32,0,40,2,188,7,13,0,32,0,32,0,40,2,0,65,1,106,54,2,0,11,32,1,42,2,0,33,3,32,0,
      32,2,65,1,32,2,65,1,75,27,34,2,54,2,188,7,32,0,32,3,32,0,42,2,180,7,147,32,2,178,149,56,2,184,7,11,181,1,0,32,0,66,128,128,240,158,4,55,2,208,4,32,0,65,7,54,2,200,4,32,0,66,128,128,240,158,4,55,2,128,4,
      32,0,65,6,54,2,248,3,32,0,66,128,128,240,158,4,55,2,176,3,32,0,65,5,54,2,168,3,32,0,66,128,128,240,158,4,55,2,224,2,32,0,65,4,54,2,216,2,32,0,66,128,128,240,158,4,55,2,144,2,32,0,65,3,54,2,136,2,32,0,66,
      128,128,240,158,4,55,2,192,1,32,0,65,2,54,2,184,1,32,0,66,128,128,240,158,4,55,2,112,32,0,65,1,54,2,104,32,0,66,128,128,240,158,4,55,2,32,32,0,65,0,54,2,24,65,0,32,3,57,3,128,128,128,128,0,32,0,66,128,
      128,128,128,23,55,2,152,6,11,248,54,15,11,127,2,125,1,127,1,125,1,127,1,125,3,127,2,125,1,127,3,124,1,125,7,127,1,124,70,127,2,126,35,128,128,128,128,0,65,192,3,107,34,3,36,128,128,128,128,0,2,64,32,0,
      40,2,4,32,2,70,13,0,32,0,65,24,106,33,4,32,3,65,192,0,106,65,100,106,33,5,32,3,65,128,1,106,65,32,106,33,6,32,3,65,4,114,34,7,65,56,106,33,8,32,7,65,48,106,33,9,32,7,65,40,106,33,10,32,7,65,16,106,33,11,
      32,7,65,8,106,33,12,3,64,2,64,2,64,32,0,40,2,0,34,13,13,0,32,0,42,2,204,6,33,14,32,0,42,2,200,6,33,15,12,1,11,2,64,32,0,40,2,232,6,34,16,69,13,0,32,0,32,16,65,127,106,34,16,54,2,232,6,32,0,32,0,42,2,228,
      6,32,0,42,2,224,6,146,56,2,224,6,32,16,13,0,32,0,32,13,65,127,106,34,13,54,2,0,11,2,64,32,0,40,2,244,6,34,16,69,13,0,32,0,32,16,65,127,106,34,16,54,2,244,6,32,0,32,0,42,2,240,6,32,0,42,2,236,6,146,56,2,
      236,6,32,16,13,0,32,0,32,13,65,127,106,34,13,54,2,0,11,2,64,32,0,40,2,128,7,34,16,69,13,0,32,0,32,16,65,127,106,34,16,54,2,128,7,32,0,32,0,42,2,252,6,32,0,42,2,248,6,146,56,2,248,6,32,16,13,0,32,0,32,13,
      65,127,106,34,13,54,2,0,11,2,64,32,0,40,2,140,7,34,16,69,13,0,32,0,32,16,65,127,106,34,16,54,2,140,7,32,0,32,0,42,2,136,7,32,0,42,2,132,7,146,56,2,132,7,32,16,13,0,32,0,32,13,65,127,106,34,13,54,2,0,11,
      2,64,32,0,40,2,152,7,34,16,69,13,0,32,0,32,16,65,127,106,34,16,54,2,152,7,32,0,32,0,42,2,148,7,32,0,42,2,144,7,146,56,2,144,7,32,16,13,0,32,0,32,13,65,127,106,34,13,54,2,0,11,2,64,32,0,40,2,164,7,34,16,
      69,13,0,32,0,32,16,65,127,106,34,16,54,2,164,7,32,0,32,0,42,2,160,7,32,0,42,2,156,7,146,56,2,156,7,32,16,13,0,32,0,32,13,65,127,106,34,13,54,2,0,11,2,64,32,0,40,2,176,7,34,16,69,13,0,32,0,32,16,65,127,
      106,34,16,54,2,176,7,32,0,32,0,42,2,172,7,32,0,42,2,168,7,146,56,2,168,7,32,16,13,0,32,0,32,13,65,127,106,34,13,54,2,0,11,32,0,42,2,180,7,33,15,2,64,32,0,40,2,188,7,34,16,69,13,0,32,0,32,16,65,127,106,
      34,16,54,2,188,7,32,0,32,0,42,2,184,7,32,15,146,34,15,56,2,180,7,32,16,13,0,32,0,32,13,65,127,106,54,2,0,11,32,0,32,15,56,2,220,6,32,0,32,0,42,2,224,6,56,2,192,6,32,0,32,0,42,2,236,6,56,2,196,6,32,0,32,
      0,42,2,248,6,34,15,56,2,200,6,32,0,32,0,42,2,132,7,34,14,56,2,204,6,32,0,32,0,42,2,144,7,56,2,208,6,32,0,32,0,42,2,156,7,56,2,212,6,32,0,32,0,42,2,168,7,56,2,216,6,11,32,7,66,0,55,2,0,32,0,32,14,56,2,184,
      6,32,0,32,15,56,2,180,6,32,8,65,0,54,2,0,32,9,66,0,55,2,0,32,10,66,0,55,2,0,32,7,65,32,106,66,0,55,2,0,32,7,65,24,106,66,0,55,2,0,32,11,66,0,55,2,0,32,12,66,0,55,2,0,67,0,0,0,0,33,17,2,64,32,0,40,2,188,
      6,65,127,70,13,0,2,64,32,15,67,0,0,0,0,94,69,13,0,32,14,32,0,42,2,176,6,34,17,32,17,146,67,0,0,128,191,146,139,148,33,14,2,64,32,17,32,15,65,0,43,3,128,128,128,128,0,182,149,146,34,15,67,0,0,128,63,96,
      69,13,0,3,64,32,15,67,0,0,128,191,146,34,15,67,0,0,128,63,96,13,0,11,11,32,14,67,0,0,0,0,146,33,17,32,0,32,15,56,2,176,6,11,32,0,65,1,54,2,188,6,11,32,0,32,0,42,2,192,6,34,15,56,2,128,5,32,0,32,15,56,2,
      176,4,32,0,32,15,56,2,224,3,32,0,32,15,56,2,144,3,32,0,32,15,56,2,192,2,32,0,32,15,56,2,240,1,32,0,32,15,56,2,160,1,32,0,32,15,56,2,80,32,0,32,0,42,2,196,6,34,15,56,2,132,5,32,0,32,15,56,2,180,4,32,0,32,
      15,56,2,228,3,32,0,32,15,56,2,148,3,32,0,32,15,56,2,196,2,32,0,32,15,56,2,244,1,32,0,32,15,56,2,164,1,32,0,32,15,56,2,84,32,3,32,17,56,2,56,32,3,32,17,56,2,48,32,3,32,17,56,2,40,32,3,32,17,56,2,32,32,3,
      32,17,56,2,24,32,3,32,17,56,2,16,32,3,32,17,56,2,8,32,3,32,17,56,2,0,32,0,32,0,42,2,208,6,34,15,56,2,136,5,32,0,32,15,56,2,184,4,32,0,32,15,56,2,232,3,32,0,32,15,56,2,152,3,32,0,32,15,56,2,200,2,32,0,32,
      15,56,2,248,1,32,0,32,15,56,2,168,1,32,0,32,15,56,2,88,32,0,32,0,42,2,212,6,34,15,56,2,140,5,32,0,32,15,56,2,188,4,32,0,32,15,56,2,236,3,32,0,32,15,56,2,156,3,32,0,32,15,56,2,204,2,32,0,32,15,56,2,252,
      1,32,0,32,15,56,2,172,1,32,0,32,15,56,2,92,32,0,32,0,42,2,216,6,34,15,56,2,144,5,32,0,32,15,56,2,192,4,32,0,32,15,56,2,240,3,32,0,32,15,56,2,160,3,32,0,32,15,56,2,208,2,32,0,32,15,56,2,128,2,32,0,32,15,
      56,2,176,1,32,0,32,15,56,2,96,32,0,32,0,42,2,220,6,34,15,56,2,148,5,32,0,32,15,56,2,196,4,32,0,32,15,56,2,244,3,32,0,32,15,56,2,164,3,32,0,32,15,56,2,212,2,32,0,32,15,56,2,132,2,32,0,32,15,56,2,180,1,32,
      0,32,15,56,2,100,65,0,33,18,65,0,43,3,128,128,128,128,0,182,33,19,3,64,67,0,0,0,0,33,15,65,0,33,20,67,0,0,0,0,33,17,2,64,32,4,32,18,65,208,0,108,106,34,21,40,2,16,65,127,70,13,0,32,21,65,1,54,2,16,32,21,
      42,2,12,67,0,0,0,0,94,33,20,32,21,42,2,8,67,0,0,0,0,146,33,17,11,32,3,32,18,65,3,116,106,33,22,2,64,32,21,40,2,24,65,127,70,13,0,32,22,42,2,0,32,21,42,2,60,146,34,23,67,0,0,0,0,146,33,14,2,64,2,64,32,21,
      42,2,20,34,15,67,219,15,201,64,148,34,24,188,34,25,65,255,255,255,255,7,113,34,13,65,218,159,164,250,3,75,13,0,32,24,32,24,187,34,26,32,26,162,34,27,32,26,162,34,28,32,27,32,27,162,162,32,27,68,167,70,
      59,140,135,205,198,62,162,68,116,231,202,226,249,0,42,191,160,162,32,28,32,27,68,178,251,110,137,16,17,129,63,162,68,119,172,203,84,85,85,197,191,160,162,32,26,160,160,182,32,13,65,128,128,128,204,3,73,
      27,33,29,12,1,11,2,64,32,13,65,209,167,237,131,4,75,13,0,32,24,187,33,27,2,64,32,13,65,228,151,219,128,4,79,13,0,68,0,0,0,0,0,0,240,63,32,27,68,24,45,68,84,251,33,249,63,160,34,26,32,26,162,34,26,68,129,
      94,12,253,255,255,223,63,162,161,32,26,32,26,162,34,28,68,66,58,5,225,83,85,165,63,162,160,32,26,32,28,162,32,26,68,105,80,238,224,66,147,249,62,162,68,39,30,15,232,135,192,86,191,160,162,160,182,140,68,
      0,0,0,0,0,0,240,63,32,27,68,24,45,68,84,251,33,249,191,160,34,27,32,27,162,34,27,68,129,94,12,253,255,255,223,63,162,161,32,27,32,27,162,34,26,68,66,58,5,225,83,85,165,63,162,160,32,27,32,26,162,32,27,
      68,105,80,238,224,66,147,249,62,162,68,39,30,15,232,135,192,86,191,160,162,160,182,32,25,65,0,72,27,33,29,12,2,11,68,24,45,68,84,251,33,9,64,68,24,45,68,84,251,33,9,192,32,25,65,0,72,27,32,27,160,34,26,
      32,26,162,34,27,32,26,154,162,34,28,32,27,32,27,162,162,32,27,68,167,70,59,140,135,205,198,62,162,68,116,231,202,226,249,0,42,191,160,162,32,28,32,27,68,178,251,110,137,16,17,129,63,162,68,119,172,203,
      84,85,85,197,191,160,162,32,26,161,160,182,33,29,12,1,11,2,64,2,64,2,64,32,13,65,214,227,136,135,4,73,13,0,32,13,65,255,255,255,251,7,77,13,1,32,24,32,24,147,33,29,12,3,11,32,24,187,33,27,32,13,65,224,
      219,191,133,4,73,13,1,68,24,45,68,84,251,33,25,64,68,24,45,68,84,251,33,25,192,32,25,65,0,72,27,32,27,160,34,26,32,26,32,26,162,34,27,162,34,28,32,27,32,27,162,162,32,27,68,167,70,59,140,135,205,198,62,
      162,68,116,231,202,226,249,0,42,191,160,162,32,26,32,28,32,27,68,178,251,110,137,16,17,129,63,162,68,119,172,203,84,85,85,197,191,160,162,160,160,182,33,29,12,2,11,2,64,2,64,32,13,65,218,159,164,238,4,
      75,13,0,32,24,187,34,27,32,27,68,131,200,201,109,48,95,228,63,162,68,0,0,0,0,0,0,56,67,160,68,0,0,0,0,0,0,56,195,160,34,26,68,0,0,0,80,251,33,249,191,162,160,32,26,68,99,98,26,97,180,16,81,190,162,160,
      33,27,32,26,252,2,33,30,12,1,11,32,3,66,128,128,128,128,208,227,252,180,53,55,3,184,3,32,3,66,128,128,128,128,168,196,224,241,54,55,3,176,3,32,3,66,128,128,128,128,132,164,137,189,56,55,3,168,3,32,3,66,
      128,128,128,128,184,240,134,248,57,55,3,160,3,32,3,66,128,128,128,128,150,138,179,188,59,55,3,152,3,32,3,66,128,128,128,128,136,211,145,252,60,55,3,144,3,32,3,66,128,128,128,128,208,133,145,186,62,55,3,
      136,3,32,3,66,128,128,128,128,180,191,200,252,63,55,3,128,3,2,64,65,128,1,69,13,0,32,3,65,128,2,106,65,0,65,128,1,252,11,0,11,2,64,65,224,0,69,13,0,32,6,65,0,65,224,0,252,11,0,11,32,3,65,192,0,106,65,8,
      106,66,0,55,3,0,32,3,65,192,0,106,65,16,106,66,0,55,3,0,32,3,65,192,0,106,65,24,106,66,0,55,3,0,32,3,65,192,0,106,65,32,106,66,0,55,3,0,32,3,65,192,0,106,65,40,106,66,0,55,3,0,32,3,65,192,0,106,65,48,106,
      66,0,55,3,0,32,3,65,192,0,106,65,56,106,66,0,55,3,0,32,3,66,0,55,3,64,32,3,32,13,32,13,65,23,118,34,16,65,234,126,106,34,31,65,23,116,107,190,187,34,28,32,16,65,231,126,106,65,255,1,113,65,24,110,34,32,
      65,2,116,34,13,65,156,128,128,128,0,106,40,2,0,183,162,68,0,0,0,0,0,0,0,0,160,57,3,152,1,32,3,32,28,32,13,65,152,128,128,128,0,106,40,2,0,183,162,68,0,0,0,0,0,0,0,0,160,57,3,144,1,32,3,32,28,32,13,65,148,
      128,128,128,0,106,40,2,0,183,162,68,0,0,0,0,0,0,0,0,160,57,3,136,1,32,3,32,28,32,13,65,144,128,128,128,0,106,40,2,0,183,162,68,0,0,0,0,0,0,0,0,160,57,3,128,1,65,47,32,32,65,104,108,32,31,106,34,33,107,
      33,34,65,48,32,33,107,33,35,32,33,65,104,106,33,36,32,33,65,231,7,106,173,66,52,134,191,33,37,65,3,33,38,32,33,65,25,72,33,39,32,33,65,103,106,33,40,2,64,3,64,32,3,65,128,1,106,32,38,34,41,65,15,113,34,
      42,65,3,116,106,43,3,0,33,27,2,64,32,41,65,1,72,34,31,13,0,32,41,65,127,106,33,13,65,0,33,16,3,64,32,3,65,192,0,106,32,16,65,15,113,65,2,116,106,32,27,32,27,68,0,0,0,0,0,0,112,62,162,252,2,183,34,26,68,
      0,0,0,0,0,0,112,193,162,160,252,2,54,2,0,32,3,65,128,1,106,32,13,65,15,113,65,3,116,106,43,3,0,32,26,160,33,27,32,16,65,1,106,33,16,32,13,65,127,106,34,13,65,127,71,13,0,11,11,32,27,32,37,162,34,27,32,
      27,68,0,0,0,0,0,0,192,63,162,156,68,0,0,0,0,0,0,32,192,162,160,34,27,32,27,252,2,34,30,183,161,33,27,2,64,2,64,2,64,2,64,32,39,13,0,32,3,65,192,0,106,32,41,65,127,106,65,15,113,65,2,116,106,34,13,32,13,
      40,2,0,34,13,32,13,32,35,117,34,13,32,35,116,107,34,16,54,2,0,32,16,32,34,117,33,43,32,13,32,30,106,33,30,12,1,11,2,64,32,36,13,0,32,3,65,192,0,106,32,41,65,127,106,65,15,113,65,2,116,106,40,2,0,65,23,
      117,33,43,12,1,11,65,2,33,43,65,0,33,44,32,27,68,0,0,0,0,0,0,224,63,102,69,13,2,12,1,11,32,43,65,0,74,13,0,32,43,33,44,12,1,11,2,64,2,64,32,31,69,13,0,65,0,33,31,12,1,11,65,0,33,13,65,0,33,31,3,64,32,3,
      65,192,0,106,32,13,65,15,113,65,2,116,106,34,38,40,2,0,33,16,2,64,2,64,2,64,2,64,32,31,65,1,113,69,13,0,65,255,255,255,7,33,31,12,1,11,32,16,69,13,1,65,128,128,128,8,33,31,11,32,38,32,31,32,16,107,54,2,
      0,65,1,33,31,12,1,11,65,0,33,31,11,32,41,32,13,65,1,106,34,13,71,13,0,11,11,2,64,32,39,13,0,65,255,255,255,3,33,13,2,64,2,64,32,40,14,2,1,0,2,11,65,255,255,255,1,33,13,11,32,3,65,192,0,106,32,41,65,127,
      106,65,15,113,65,2,116,106,34,16,32,16,40,2,0,32,13,113,54,2,0,11,32,30,65,1,106,33,30,65,2,33,44,32,43,65,2,71,13,0,68,0,0,0,0,0,0,240,63,32,27,161,34,27,32,37,161,32,27,32,31,27,33,27,11,2,64,32,27,68,
      0,0,0,0,0,0,0,0,98,13,0,2,64,32,41,65,127,106,34,13,65,3,72,13,0,65,0,33,16,2,64,2,64,32,41,65,125,106,34,45,65,7,77,13,0,32,41,65,127,106,65,15,113,65,3,73,13,0,32,41,65,108,106,65,112,73,13,0,65,0,33,
      43,65,0,33,46,65,0,33,16,2,64,32,45,65,32,73,13,0,32,3,65,192,0,106,32,13,65,15,113,65,2,116,106,34,31,40,2,0,33,47,32,31,65,132,127,106,34,16,40,2,0,33,48,32,16,40,2,4,33,49,32,16,40,2,8,33,50,32,16,40,
      2,12,33,51,32,16,40,2,16,33,52,32,16,40,2,20,33,53,32,16,40,2,24,33,54,32,16,40,2,28,33,55,32,31,65,164,127,106,34,16,40,2,0,33,56,32,16,40,2,4,33,57,32,16,40,2,8,33,58,32,16,40,2,12,33,59,32,16,40,2,16,
      33,60,32,16,40,2,20,33,61,32,16,40,2,24,33,62,32,16,40,2,28,33,63,32,31,65,68,106,34,16,40,2,0,33,64,32,16,40,2,4,33,65,32,16,40,2,8,33,66,32,16,40,2,12,33,67,32,16,40,2,16,33,68,32,16,40,2,20,33,69,32,
      16,40,2,24,33,70,32,16,40,2,28,33,71,32,31,65,100,106,34,16,40,2,0,33,72,32,16,40,2,4,33,73,32,16,40,2,8,33,74,32,16,40,2,12,33,75,32,16,40,2,16,33,76,32,16,40,2,20,33,77,32,16,40,2,24,33,78,65,0,33,16,
      32,45,65,96,113,34,46,33,79,65,0,33,31,65,0,33,38,65,0,33,42,65,0,33,80,65,0,33,81,65,0,33,82,65,0,33,83,65,0,33,84,65,0,33,85,65,0,33,86,65,0,33,87,65,0,33,88,65,0,33,89,65,0,33,90,65,0,33,91,65,0,33,
      92,65,0,33,93,65,0,33,94,65,0,33,95,65,0,33,96,65,0,33,97,65,0,33,98,65,0,33,99,65,0,33,100,65,0,33,101,65,0,33,102,65,0,33,103,65,0,33,104,65,0,33,105,65,0,33,106,65,0,33,107,3,64,32,55,32,100,114,33,
      100,32,63,32,92,114,33,92,32,71,32,84,114,33,84,32,47,32,16,114,33,16,32,54,32,101,114,33,101,32,62,32,93,114,33,93,32,70,32,85,114,33,85,32,78,32,31,114,33,31,32,53,32,102,114,33,102,32,61,32,94,114,33,
      94,32,69,32,86,114,33,86,32,77,32,38,114,33,38,32,52,32,103,114,33,103,32,60,32,95,114,33,95,32,68,32,87,114,33,87,32,76,32,42,114,33,42,32,51,32,104,114,33,104,32,59,32,96,114,33,96,32,67,32,88,114,33,
      88,32,75,32,80,114,33,80,32,50,32,105,114,33,105,32,58,32,97,114,33,97,32,66,32,89,114,33,89,32,74,32,81,114,33,81,32,49,32,106,114,33,106,32,57,32,98,114,33,98,32,65,32,90,114,33,90,32,73,32,82,114,33,
      82,32,48,32,107,114,33,107,32,56,32,99,114,33,99,32,64,32,91,114,33,91,32,72,32,83,114,33,83,32,79,65,96,106,34,79,13,0,11,32,100,32,92,32,84,32,16,114,114,114,32,104,32,96,32,88,32,80,114,114,114,114,
      32,102,32,94,32,86,32,38,114,114,114,32,106,32,98,32,90,32,82,114,114,114,114,114,32,101,32,93,32,85,32,31,114,114,114,32,105,32,97,32,89,32,81,114,114,114,114,32,103,32,95,32,87,32,42,114,114,114,32,107,
      32,99,32,91,32,83,114,114,114,114,114,114,33,16,32,45,32,46,70,13,2,32,45,65,24,113,13,0,32,13,32,46,107,33,13,12,1,11,32,46,65,127,115,32,41,106,33,38,32,46,32,45,65,120,113,34,86,107,33,85,32,13,32,86,
      107,33,13,65,0,33,42,65,0,33,80,65,0,33,81,65,0,33,82,65,0,33,83,65,0,33,84,3,64,32,5,32,38,65,15,113,65,2,116,106,34,31,40,2,12,32,81,114,33,81,32,31,40,2,16,32,80,114,33,80,32,31,40,2,20,32,42,114,33,
      42,32,31,40,2,24,32,43,114,33,43,32,31,40,2,28,32,16,114,33,16,32,31,40,2,8,32,82,114,33,82,32,31,40,2,4,32,83,114,33,83,32,31,40,2,0,32,84,114,33,84,32,38,65,120,106,33,38,32,85,65,8,106,34,85,13,0,11,
      32,16,32,81,114,32,42,32,83,114,114,32,43,32,82,114,32,80,32,84,114,114,114,33,16,32,45,32,86,70,13,1,11,3,64,32,3,65,192,0,106,32,13,65,15,113,65,2,116,106,40,2,0,32,16,114,33,16,32,13,65,3,75,33,31,32,
      13,65,127,106,33,13,32,31,13,0,11,11,32,16,69,13,0,32,36,33,33,3,64,32,33,65,104,106,33,33,32,3,65,192,0,106,32,41,65,127,106,34,41,65,15,113,65,2,116,106,40,2,0,69,13,0,12,4,11,11,65,0,33,13,3,64,32,13,
      34,16,65,127,106,33,13,32,3,65,192,0,106,32,16,65,2,106,65,15,113,65,2,116,106,40,2,0,69,13,0,11,32,41,65,1,106,34,31,32,41,32,13,107,34,38,74,13,1,2,64,32,41,65,127,115,34,43,32,38,172,66,1,124,34,108,
      32,41,65,2,106,34,13,172,34,109,32,108,32,109,85,27,34,108,167,106,34,82,65,12,73,13,0,32,13,32,108,32,109,125,34,108,167,34,42,106,32,13,72,13,0,65,14,32,41,107,65,15,113,32,42,65,15,113,73,13,0,32,108,
      66,15,86,13,0,32,43,32,31,32,16,107,172,66,1,124,34,108,32,109,32,108,32,109,85,27,167,106,65,124,113,33,80,32,32,32,41,106,33,81,32,31,32,82,65,124,113,34,83,106,33,31,65,0,33,13,3,64,32,3,65,128,1,106,
      32,41,32,13,106,65,1,106,65,15,113,65,3,116,106,34,16,32,28,32,81,32,13,106,34,43,65,4,106,65,194,0,111,34,42,65,194,0,106,32,42,32,42,65,0,72,27,65,2,116,65,144,128,128,128,0,106,40,2,0,183,162,68,0,0,
      0,0,0,0,0,0,160,57,3,24,32,16,32,28,32,43,65,3,106,65,194,0,111,34,42,65,194,0,106,32,42,32,42,65,0,72,27,65,2,116,65,144,128,128,128,0,106,40,2,0,183,162,68,0,0,0,0,0,0,0,0,160,57,3,16,32,16,32,28,32,
      43,65,2,106,65,194,0,111,34,42,65,194,0,106,32,42,32,42,65,0,72,27,65,2,116,65,144,128,128,128,0,106,40,2,0,183,162,68,0,0,0,0,0,0,0,0,160,57,3,8,32,16,32,28,32,43,65,1,106,65,194,0,111,34,43,65,194,0,
      106,32,43,32,43,65,0,72,27,65,2,116,65,144,128,128,128,0,106,40,2,0,183,162,68,0,0,0,0,0,0,0,0,160,57,3,0,32,80,32,13,65,4,106,34,13,71,13,0,11,32,82,32,83,70,13,2,11,3,64,32,3,65,128,1,106,32,31,65,15,
      113,65,3,116,106,32,28,32,32,32,31,106,65,194,0,111,34,13,65,194,0,106,32,13,32,13,65,0,72,27,65,2,116,65,144,128,128,128,0,106,40,2,0,183,162,68,0,0,0,0,0,0,0,0,160,57,3,0,32,31,65,1,106,34,31,32,38,76,
      13,0,12,2,11,11,11,2,64,2,64,32,27,65,151,8,32,33,107,173,66,52,134,191,162,34,27,68,0,0,0,0,0,0,112,65,102,69,13,0,32,3,65,192,0,106,32,42,65,2,116,106,32,27,32,27,68,0,0,0,0,0,0,112,62,162,252,2,34,13,
      183,68,0,0,0,0,0,0,112,193,162,160,252,2,54,2,0,32,41,65,1,106,34,41,65,15,113,33,42,12,1,11,32,27,252,2,33,13,32,36,33,33,11,32,3,65,192,0,106,32,42,65,2,116,106,32,13,54,2,0,11,2,64,2,64,2,64,2,64,32,
      33,65,128,8,72,13,0,32,33,65,254,15,75,13,1,32,33,65,129,120,106,33,33,68,0,0,0,0,0,0,224,127,33,27,12,3,11,32,33,65,130,120,72,13,1,68,0,0,0,0,0,0,240,63,33,27,12,2,11,32,33,65,253,23,32,33,65,253,23,
      73,27,65,130,112,106,33,33,68,0,0,0,0,0,0,240,127,33,27,12,1,11,2,64,32,33,65,184,112,77,13,0,32,33,65,201,7,106,33,33,68,0,0,0,0,0,0,96,3,33,27,12,1,11,32,33,65,240,104,32,33,65,240,104,75,27,65,146,15,
      106,33,33,68,0,0,0,0,0,0,0,0,33,27,11,2,64,2,64,32,41,65,0,78,13,0,68,0,0,0,0,0,0,0,0,33,27,12,1,11,32,27,32,33,65,255,7,106,173,66,52,134,191,162,33,27,32,41,33,13,3,64,32,3,65,128,1,106,32,13,65,15,113,
      34,16,65,3,116,106,32,27,32,3,65,192,0,106,32,16,65,2,116,106,40,2,0,183,162,57,3,0,32,27,68,0,0,0,0,0,0,112,62,162,33,27,32,13,65,127,106,34,13,65,127,71,13,0,11,65,0,33,43,32,41,33,31,3,64,32,43,65,3,
      32,43,65,3,73,27,65,1,106,33,38,68,0,0,0,0,0,0,0,0,33,27,32,3,65,128,3,106,33,13,65,0,33,16,3,64,32,27,32,3,65,128,1,106,32,31,32,16,106,65,15,113,65,3,116,106,43,3,0,32,13,43,3,0,162,160,33,27,32,13,65,
      8,106,33,13,32,38,32,16,65,1,106,34,16,71,13,0,11,32,3,65,128,2,106,32,41,32,31,107,65,15,113,65,3,116,106,32,27,57,3,0,32,31,65,127,106,33,31,32,43,32,41,71,33,13,32,43,65,1,106,33,43,32,13,13,0,11,68,
      0,0,0,0,0,0,0,0,33,27,3,64,32,27,32,3,65,128,2,106,32,41,65,15,113,65,3,116,106,43,3,0,160,33,27,32,41,65,127,106,34,41,65,127,71,13,0,11,11,32,27,154,32,27,32,44,27,33,27,32,25,65,127,74,13,0,65,0,32,
      30,107,33,30,32,27,154,33,27,11,2,64,2,64,2,64,2,64,32,30,65,3,113,14,4,0,1,2,3,0,11,32,27,32,27,32,27,162,34,26,162,34,28,32,26,32,26,162,162,32,26,68,167,70,59,140,135,205,198,62,162,68,116,231,202,226,
      249,0,42,191,160,162,32,27,32,28,32,26,68,178,251,110,137,16,17,129,63,162,68,119,172,203,84,85,85,197,191,160,162,160,160,182,33,29,12,4,11,32,27,32,27,162,34,27,68,129,94,12,253,255,255,223,191,162,68,
      0,0,0,0,0,0,240,63,160,32,27,32,27,162,34,26,68,66,58,5,225,83,85,165,63,162,160,32,27,32,26,162,32,27,68,105,80,238,224,66,147,249,62,162,68,39,30,15,232,135,192,86,191,160,162,160,182,33,29,12,3,11,32,
      27,32,27,162,34,26,32,27,154,162,34,28,32,26,32,26,162,162,32,26,68,167,70,59,140,135,205,198,62,162,68,116,231,202,226,249,0,42,191,160,162,32,28,32,26,68,178,251,110,137,16,17,129,63,162,68,119,172,203,
      84,85,85,197,191,160,162,32,27,161,160,182,33,29,12,2,11,32,27,32,27,162,34,27,68,129,94,12,253,255,255,223,191,162,68,0,0,0,0,0,0,240,63,160,32,27,32,27,162,34,26,68,66,58,5,225,83,85,165,63,162,160,32,
      27,32,26,162,32,27,68,105,80,238,224,66,147,249,62,162,68,39,30,15,232,135,192,86,191,160,162,160,182,140,33,29,12,1,11,68,0,0,0,0,0,0,240,63,32,27,68,210,33,51,127,124,217,18,64,160,34,26,32,26,162,34,
      26,68,129,94,12,253,255,255,223,63,162,161,32,26,32,26,162,34,28,68,66,58,5,225,83,85,165,63,162,160,32,26,32,28,162,32,26,68,105,80,238,224,66,147,249,62,162,68,39,30,15,232,135,192,86,191,160,162,160,
      182,68,0,0,0,0,0,0,240,63,32,27,68,210,33,51,127,124,217,18,192,160,34,27,32,27,162,34,27,68,129,94,12,253,255,255,223,63,162,161,32,27,32,27,162,34,26,68,66,58,5,225,83,85,165,63,162,160,32,27,32,26,162,
      32,27,68,105,80,238,224,66,147,249,62,162,68,39,30,15,232,135,192,86,191,160,162,160,182,140,32,25,65,0,72,27,33,29,11,32,15,32,15,146,67,0,0,128,191,146,33,24,2,64,2,64,67,0,0,128,63,67,0,0,0,0,32,14,
      32,14,67,0,0,0,0,93,27,32,23,67,0,0,128,63,94,27,34,14,67,250,126,170,62,93,69,13,0,32,14,67,250,126,170,62,149,34,14,32,24,148,67,0,0,128,63,32,14,147,32,29,148,146,33,14,12,1,11,67,0,0,128,63,67,0,0,
      128,191,32,15,67,0,0,0,63,93,27,33,23,2,64,32,14,67,250,126,42,63,93,69,13,0,32,14,67,250,126,170,190,146,67,250,126,170,62,149,34,14,32,23,148,67,0,0,128,63,32,14,147,32,24,148,146,33,14,12,1,11,67,0,
      0,128,63,32,14,67,250,126,42,191,146,67,12,2,171,62,149,34,14,147,32,23,148,32,14,32,15,67,0,0,0,191,146,139,67,0,0,128,64,148,67,0,0,128,191,146,148,146,33,14,11,2,64,32,17,32,19,149,32,15,146,34,15,67,
      0,0,128,63,96,69,13,0,3,64,32,15,67,0,0,128,191,146,34,15,67,0,0,128,63,96,13,0,11,11,32,21,32,15,56,2,20,2,64,32,15,67,0,0,0,0,93,69,13,0,3,64,32,15,67,0,0,128,63,146,34,15,67,0,0,0,0,93,13,0,11,32,21,
      32,15,56,2,20,11,32,21,65,1,54,2,24,32,14,67,0,0,0,0,146,33,15,11,32,21,32,21,42,2,64,34,24,56,2,36,32,21,32,21,42,2,68,34,23,56,2,40,32,21,32,21,42,2,72,34,14,56,2,44,32,21,32,21,42,2,76,34,17,56,2,48,
      2,64,2,64,32,21,40,2,52,65,127,71,13,0,67,0,0,0,0,33,17,12,1,11,32,21,40,2,32,33,13,2,64,2,64,2,64,2,64,2,64,2,64,2,64,2,64,2,64,32,20,69,13,0,32,13,14,5,1,2,3,4,1,7,11,32,13,65,123,113,13,4,32,13,65,127,
      106,14,4,1,2,3,5,6,11,32,21,65,1,54,2,32,11,32,21,67,0,0,128,63,67,0,0,128,63,32,24,32,19,148,34,17,149,32,17,67,0,0,128,63,93,27,32,21,42,2,28,146,34,17,56,2,28,32,17,67,0,0,128,63,96,69,13,5,32,21,66,
      128,128,128,252,35,55,2,28,67,0,0,128,63,33,17,12,5,11,32,21,32,21,42,2,28,67,0,0,128,63,67,0,0,128,63,32,14,147,32,23,32,19,148,34,17,149,32,17,67,0,0,128,63,93,27,147,34,17,56,2,28,32,17,32,14,95,69,
      13,4,32,21,65,3,54,2,32,11,32,21,32,14,56,2,28,32,14,33,17,12,3,11,32,21,65,4,54,2,32,11,32,21,32,21,42,2,28,34,14,32,14,32,14,32,17,32,19,148,34,17,149,32,17,67,0,0,128,63,93,27,147,34,17,56,2,28,32,17,
      67,0,0,0,0,95,69,13,1,32,21,66,0,55,2,28,67,0,0,0,0,33,17,12,1,11,32,21,42,2,28,33,17,11,32,21,65,1,54,2,52,32,17,67,0,0,0,0,146,33,17,11,32,22,32,22,42,2,4,32,15,32,17,148,32,21,42,2,56,148,146,56,2,4,
      32,18,65,1,106,34,18,65,8,71,13,0,11,32,1,32,0,40,2,4,65,2,116,106,32,3,42,2,60,32,3,42,2,52,32,3,42,2,44,32,3,42,2,36,32,3,42,2,28,32,3,42,2,20,32,3,42,2,12,32,3,42,2,4,67,0,0,0,0,146,146,146,146,146,
      146,146,146,56,2,0,32,0,32,0,40,2,4,65,1,106,34,13,54,2,4,32,13,32,2,71,13,0,11,11,32,0,65,0,54,2,4,32,3,65,192,3,106,36,128,128,128,128,0,11,11,156,130,128,128,0,2,0,65,0,11,8,0,0,0,0,0,0,0,0,0,65,16,
      11,136,2,131,249,162,0,68,78,110,0,252,41,21,0,209,87,39,0,221,52,245,0,98,219,192,0,60,153,149,0,65,144,67,0,99,81,254,0,187,222,171,0,183,97,197,0,58,110,36,0,210,77,66,0,73,6,224,0,9,234,46,0,28,146,
      209,0,235,29,254,0,41,177,28,0,232,62,167,0,245,53,130,0,68,187,46,0,156,233,132,0,180,38,112,0,65,126,95,0,214,145,57,0,83,131,57,0,156,244,57,0,139,95,132,0,40,249,189,0,248,31,59,0,222,255,151,0,15,
      152,5,0,17,47,239,0,10,90,139,0,109,31,109,0,207,126,54,0,9,203,39,0,70,79,183,0,158,102,63,0,45,234,95,0,186,39,117,0,229,235,199,0,61,123,241,0,247,57,7,0,146,82,138,0,251,107,234,0,31,177,95,0,8,93,
      141,0,48,3,86,0,123,252,70,0,240,171,107,0,32,188,207,0,54,244,154,0,227,169,29,0,94,97,145,0,8,27,230,0,133,153,101,0,160,20,95,0,141,64,104,0,128,216,255,0,39,115,77,0,6,6,49,0,202,86,21,0,201,168,115,
      0,123,226,96,0,107,140,192,0,0,162,131,128,128,0,7,108,105,110,107,105,110,103,2,8,220,130,128,128,0,15,0,32,0,17,95,115,101,110,100,69,118,101,110,116,95,109,105,100,105,73,110,0,2,1,67,46,76,115,116,
      100,95,95,105,110,116,114,105,110,115,105,99,115,95,95,105,110,116,101,114,110,97,108,95,95,109,97,116,104,95,105,109,112,108,101,109,101,110,116,97,116,105,111,110,115,95,95,104,101,108,112,101,114,115,
      95,95,115,99,97,108,98,110,102,0,32,2,16,95,115,101,116,86,97,108,117,101,95,118,111,108,117,109,101,0,32,3,27,95,115,101,116,86,97,108,117,101,95,119,97,118,101,116,97,98,108,101,80,111,115,105,116,105,
      111,110,0,32,4,20,95,115,101,116,86,97,108,117,101,95,109,111,114,112,104,83,112,101,101,100,0,32,5,20,95,115,101,116,86,97,108,117,101,95,109,111,114,112,104,68,101,112,116,104,0,32,6,16,95,115,101,116,
      86,97,108,117,101,95,97,116,116,97,99,107,0,32,7,15,95,115,101,116,86,97,108,117,101,95,100,101,99,97,121,0,32,8,17,95,115,101,116,86,97,108,117,101,95,115,117,115,116,97,105,110,0,32,9,17,95,115,101,116,
      86,97,108,117,101,95,114,101,108,101,97,115,101,0,32,10,10,105,110,105,116,105,97,108,105,115,101,1,2,14,46,76,103,95,95,102,114,101,113,117,101,110,99,121,0,0,8,0,32,11,12,97,100,118,97,110,99,101,66,
      108,111,99,107,2,16,0,1,2,15,46,76,103,95,95,95,99,111,110,115,116,97,110,116,95,1,0,136,2,5,177,128,128,128,0,2,19,46,98,115,115,46,46,76,103,95,95,102,114,101,113,117,101,110,99,121,3,0,23,46,114,111,
      100,97,116,97,46,46,76,103,95,95,95,99,111,110,115,116,97,110,116,95,4,0,0,217,128,128,128,0,10,114,101,108,111,99,46,67,79,68,69,5,16,0,144,28,1,3,206,35,11,0,7,130,36,13,7,142,36,13,3,235,42,11,0,3,142,
      47,11,0,4,135,56,14,12,4,167,56,14,8,4,199,56,14,4,4,231,56,14,0,4,225,72,14,0,4,152,73,14,0,4,207,73,14,0,4,134,74,14,0,4,225,74,14,0,7,212,90,13,0,148,129,128,128,0,15,116,97,114,103,101,116,95,102,101,
      97,116,117,114,101,115,8,43,11,98,117,108,107,45,109,101,109,111,114,121,43,15,98,117,108,107,45,109,101,109,111,114,121,45,111,112,116,43,22,99,97,108,108,45,105,110,100,105,114,101,99,116,45,111,118,
      101,114,108,111,110,103,43,10,109,117,108,116,105,118,97,108,117,101,43,15,109,117,116,97,98,108,101,45,103,108,111,98,97,108,115,43,19,110,111,110,116,114,97,112,112,105,110,103,45,102,112,116,111,105,
      110,116,43,15,114,101,102,101,114,101,110,99,101,45,116,121,112,101,115,43,8,115,105,103,110,45,101,120,116,]);
  }
}
