//==============================================================================
//
//  This file contains a Javascript/Webassembly/WebAudio export of the Cmajor
//  patch 'FMSynth.cmajorpatch'.
//
//  This file was auto-generated by the Cmajor toolkit v1.0.3088
//
//  To use it, import this module into your HTML/Javascript code and call
//  `createAudioWorkletNodePatchConnection()`. The AudioWorkletPatchConnection
//  object that is returned is a PatchConnection with some extra functionality
//  to let you connect it to web audio/MIDI.
//
//  For more details about Cmajor, visit https://cmajor.dev
//
//==============================================================================

import * as helpers from "./cmaj_api/cmaj-audio-worklet-helper.js"


//==============================================================================
/** This exports the patch's manifest, in case a caller needs to find out about its properties.
 */
export const manifest =
{
  "CmajorVersion": 1,
  "ID": "dev.serendiproducts.FMSynth",
  "version": "1.0",
  "name": "FM Synth",
  "description": "FM Synthesizer",
  "category": "synth",
  "manufacturer": "snp",
  "isInstrument": true,
  "source": [
    "FMSynth.cmajor"
  ]
};

/** Returns the patch's output endpoint list */
export function getOutputEndpoints() { return FMSynth.prototype.getOutputEndpoints(); }

/** Returns the patch's input endpoint list */
export function getInputEndpoints()  { return FMSynth.prototype.getInputEndpoints(); }

//==============================================================================
/**  Creates an audio worklet node for the patch with the given name, attaches it
 *   to the audio context provided, and returns an object containing the node
 *   and a PatchConnection class to control it.
 *
 *   @param {AudioContext} audioContext - a web audio AudioContext object
 *   @param {string} workletName - the name to give the new worklet that is created
 *   @returns {AudioWorkletPatchConnection} an AudioWorkletPatchConnection which has been initialised
 */
export async function createAudioWorkletNodePatchConnection (audioContext, workletName)
{
  const connection = new helpers.AudioWorkletPatchConnection (manifest);

  await connection.initialise ({ CmajorClass: FMSynth,
                                 audioContext,
                                 workletName,
                                 hostDescription: "WebAudio" });
  return connection;
}

/***********************************************************************************
 *
 *   A Javascript/Webassembly implementation of the Cmajor processor 'FMSynth'.
 *
 *   This class was auto-generated by the Cmajor toolkit.
 *
 *   To use it, construct an instance of this class, and call `initialise()` to
 *   asynchronously prepare it for use. Once initialised, the class provides
 *   appropriate setter/getter methods for reading/writing data to its endpoints,
 *   and an `advance()` method to render the next block.
 *
 *   This roughly mirrors functionality of the cmajor Performer API - see the
 *   C++ API classes and Cmajor docs for more information about how this is used.
 */
class FMSynth
{
  /** After constructing one of these objects, call its
   *  initialise() method to prepare it for use.
   */
  constructor()
  {
  }

  //==============================================================================
  /** Prepares this processor for use.
   *
   *  @param {number} sessionID - A unique integer ID which will be used for `processor.session`.
   *  @param {number} frequency - The frequency in Hz that the processor will be expected to run at.
   */
  async initialise (sessionID, frequency)
  {
    if (! ((sessionID ^ 0) > 1))
      throw new Error ("initialise() requires a valid non-zero session ID argument");

    if (! (frequency > 1))
      throw new Error ("initialise() requires a valid frequency argument");

    const isSIMDAvailable = WebAssembly.validate (new Uint8Array([0,97,115,109,1,0,0,0,1,5,1,96,0,1,123,3,2,1,0,10,10,1,8,0,65,0,253,15,253,98,11]));

    if (isSIMDAvailable)
      await this._initialiseInternalSIMD (sessionID, frequency);
    else
      await this._initialiseInternalNonSIMD (sessionID, frequency);

    return true;
  }

  //==============================================================================
  /** Advances the processor by a number of frames.
   *
   *  Before calling `advance()` you should use the appropriate functions to
   *  push data and events into the processor's input endpoints. After calling
   *  `advance()` you can use its output endpoint access functions to read the
   *  results.
   *
   *  @param {number} numFrames - An integer number of frames to advance.
   *                              This must be greater than zero.
   */
  advance (numFrames)
  {
    this._advanceInternal (numFrames);
  }

  //==============================================================================
  /** Returns an object which encapsulates the state of the patch at this point.
   *  The state can be restored by passing this object to `restoreState()`.
   */
  getState()
  {
    return { memory: this.byteMemory.slice(0) };
  }

  /** Restores the patch to a state that was previously saved by a call to `getState()`
   */
  restoreState (savedState)
  {
    if (savedState?.memory && savedState.memory?.length === this.byteMemory.length)
      this.byteMemory.set (savedState.memory);
    else
      throw Error ("restoreState(): not a valid state object");
  }

  /** Returns a list of the output endpoints that this processor exposes.
   *  @returns {Array}
   */
  getOutputEndpoints()
  {
    return [
      {
        "endpointID": "out",
        "endpointType": "stream",
        "dataType": {
          "type": "float32"
        },
        "purpose": "audio out",
        "numAudioChannels": 1
      }
    ];
  }

  /** Returns a list of the input endpoints that this processor exposes.
   *  @returns {Array}
   */
  getInputEndpoints()
  {
    return [
      {
        "endpointID": "midiIn",
        "endpointType": "event",
        "dataType": {
          "type": "object",
          "class": "Message",
          "members": {
            "message": {
              "type": "int32"
            }
          }
        },
        "purpose": "midi in"
      },
      {
        "endpointID": "volume",
        "endpointType": "value",
        "dataType": {
          "type": "float32"
        },
        "annotation": {
          "name": "Master Volume",
          "min": 0.0,
          "max": 1,
          "init": 0.3
        },
        "purpose": "parameter"
      },
      {
        "endpointID": "carrierRatio",
        "endpointType": "value",
        "dataType": {
          "type": "float32"
        },
        "annotation": {
          "name": "Carrier Ratio",
          "min": 0.25,
          "max": 8,
          "init": 1,
          "step": 0.25
        },
        "purpose": "parameter"
      },
      {
        "endpointID": "modulatorRatio",
        "endpointType": "value",
        "dataType": {
          "type": "float32"
        },
        "annotation": {
          "name": "Modulator Ratio",
          "min": 0.25,
          "max": 8,
          "init": 1,
          "step": 0.25
        },
        "purpose": "parameter"
      },
      {
        "endpointID": "fmIndex",
        "endpointType": "value",
        "dataType": {
          "type": "float32"
        },
        "annotation": {
          "name": "FM Index",
          "min": 0.0,
          "max": 10,
          "init": 2,
          "step": 0.1
        },
        "purpose": "parameter"
      },
      {
        "endpointID": "attack",
        "endpointType": "value",
        "dataType": {
          "type": "float32"
        },
        "annotation": {
          "name": "Attack",
          "min": 0.0,
          "max": 2,
          "init": 0.1
        },
        "purpose": "parameter"
      },
      {
        "endpointID": "decay",
        "endpointType": "value",
        "dataType": {
          "type": "float32"
        },
        "annotation": {
          "name": "Decay",
          "min": 0.0,
          "max": 2,
          "init": 0.1
        },
        "purpose": "parameter"
      },
      {
        "endpointID": "sustain",
        "endpointType": "value",
        "dataType": {
          "type": "float32"
        },
        "annotation": {
          "name": "Sustain",
          "min": 0.0,
          "max": 1,
          "init": 0.7
        },
        "purpose": "parameter"
      },
      {
        "endpointID": "release",
        "endpointType": "value",
        "dataType": {
          "type": "float32"
        },
        "annotation": {
          "name": "Release",
          "min": 0.0,
          "max": 5,
          "init": 0.3
        },
        "purpose": "parameter"
      }
    ];
  }

  /** Sends an event of type `std::midi::Message` to endpoint "midiIn".
   *  @param {Object} eventValue - The event to be added to the queue for this endpoint.
   */
  sendInputEvent_midiIn (eventValue)
  {
    this._pack_o1_Message_message_i32 (this.scratchSpaceAddress, eventValue);
    this.instance.exports._sendEvent_midiIn (this.stateAddress, this.scratchSpaceAddress);
  }

  /** Sets the value of endpoint "volume".
   *  @param {Object} newValue - The new value, whose type will depend on the endpoint type
   *  @param {number} numFramesToReachValue - If this is non-zero and the type is scalar,
   *                                          this applies a ramp to reach the new value.
  */
  setInputValue_volume (newValue, numFramesToReachValue)
  {
    this._pack_f32 (this.scratchSpaceAddress, newValue);
    this.instance.exports._setValue_volume (this.stateAddress, this.scratchSpaceAddress, numFramesToReachValue);
  }

  /** Sets the value of endpoint "carrierRatio".
   *  @param {Object} newValue - The new value, whose type will depend on the endpoint type
   *  @param {number} numFramesToReachValue - If this is non-zero and the type is scalar,
   *                                          this applies a ramp to reach the new value.
  */
  setInputValue_carrierRatio (newValue, numFramesToReachValue)
  {
    this._pack_f32 (this.scratchSpaceAddress, newValue);
    this.instance.exports._setValue_carrierRatio (this.stateAddress, this.scratchSpaceAddress, numFramesToReachValue);
  }

  /** Sets the value of endpoint "modulatorRatio".
   *  @param {Object} newValue - The new value, whose type will depend on the endpoint type
   *  @param {number} numFramesToReachValue - If this is non-zero and the type is scalar,
   *                                          this applies a ramp to reach the new value.
  */
  setInputValue_modulatorRatio (newValue, numFramesToReachValue)
  {
    this._pack_f32 (this.scratchSpaceAddress, newValue);
    this.instance.exports._setValue_modulatorRatio (this.stateAddress, this.scratchSpaceAddress, numFramesToReachValue);
  }

  /** Sets the value of endpoint "fmIndex".
   *  @param {Object} newValue - The new value, whose type will depend on the endpoint type
   *  @param {number} numFramesToReachValue - If this is non-zero and the type is scalar,
   *                                          this applies a ramp to reach the new value.
  */
  setInputValue_fmIndex (newValue, numFramesToReachValue)
  {
    this._pack_f32 (this.scratchSpaceAddress, newValue);
    this.instance.exports._setValue_fmIndex (this.stateAddress, this.scratchSpaceAddress, numFramesToReachValue);
  }

  /** Sets the value of endpoint "attack".
   *  @param {Object} newValue - The new value, whose type will depend on the endpoint type
   *  @param {number} numFramesToReachValue - If this is non-zero and the type is scalar,
   *                                          this applies a ramp to reach the new value.
  */
  setInputValue_attack (newValue, numFramesToReachValue)
  {
    this._pack_f32 (this.scratchSpaceAddress, newValue);
    this.instance.exports._setValue_attack (this.stateAddress, this.scratchSpaceAddress, numFramesToReachValue);
  }

  /** Sets the value of endpoint "decay".
   *  @param {Object} newValue - The new value, whose type will depend on the endpoint type
   *  @param {number} numFramesToReachValue - If this is non-zero and the type is scalar,
   *                                          this applies a ramp to reach the new value.
  */
  setInputValue_decay (newValue, numFramesToReachValue)
  {
    this._pack_f32 (this.scratchSpaceAddress, newValue);
    this.instance.exports._setValue_decay (this.stateAddress, this.scratchSpaceAddress, numFramesToReachValue);
  }

  /** Sets the value of endpoint "sustain".
   *  @param {Object} newValue - The new value, whose type will depend on the endpoint type
   *  @param {number} numFramesToReachValue - If this is non-zero and the type is scalar,
   *                                          this applies a ramp to reach the new value.
  */
  setInputValue_sustain (newValue, numFramesToReachValue)
  {
    this._pack_f32 (this.scratchSpaceAddress, newValue);
    this.instance.exports._setValue_sustain (this.stateAddress, this.scratchSpaceAddress, numFramesToReachValue);
  }

  /** Sets the value of endpoint "release".
   *  @param {Object} newValue - The new value, whose type will depend on the endpoint type
   *  @param {number} numFramesToReachValue - If this is non-zero and the type is scalar,
   *                                          this applies a ramp to reach the new value.
  */
  setInputValue_release (newValue, numFramesToReachValue)
  {
    this._pack_f32 (this.scratchSpaceAddress, newValue);
    this.instance.exports._setValue_release (this.stateAddress, this.scratchSpaceAddress, numFramesToReachValue);
  }

  /** Returns a frame from the output stream "out"
   *
   * @param {number} frameIndex - the index of the frame to fetch
   */
  getOutputFrame_out (frameIndex)
  {
    return this._getOutputFrameInternal_out (frameIndex);
  }

  /** Copies frames from the output stream "out" into a destination array.
   *
   * @param {Array} destChannelArrays   - An array of arrays (one per channel) into
   *                                      which the samples will be copied
   * @param {number} maxNumFramesToRead - The maximum number of frames to copy
   * @param {number} destChannel        - The channel to start writing from
   */
  getOutputFrames_out (destChannelArrays, maxNumFramesToRead, destChannel)
  {
    this._getOutputFramesInternal_out (destChannelArrays, maxNumFramesToRead, destChannel);
  }

  //==============================================================================
  // Code beyond this point is private internal implementation detail

  //==============================================================================
  /** @access private */
  async _initialiseInternalSIMD (sessionID, frequency)
  {
    this.stateAddress = 5255424;
    this.scratchSpaceAddress = 5258544;

    const memory = new WebAssembly.Memory ({ initial: 82 });
    const stack = new WebAssembly.Global ({ value: "i32", mutable: true }, 5255424);
    const imports = {
      env: {
        __linear_memory: memory,
        __memory_base: 0,
        __stack_pointer: stack,
        __table_base: 0,
        memcpy:  (dst, src, len) => { this.byteMemory.copyWithin (dst, src, src + len); return dst; },
        memmove: (dst, src, len) => { this.byteMemory.copyWithin (dst, src, src + len); return dst; },
        memset:  (dst, value, len) => { this.byteMemory.fill (value, dst, dst + len); return dst; }
      },
    };

    const result = await WebAssembly.instantiate (this._getWasmBytesSIMD(), imports);
    this.instance = result.instance;
    const exports = this.instance.exports;
    const memoryBuffer = exports.memory?.buffer || memory.buffer;
    const memoryDataView = new DataView (memoryBuffer);
    const byteMemory = new Uint8Array (memoryBuffer);
    this.byteMemory = byteMemory;
    this.memoryDataView = memoryDataView;

    exports.initialise?.(this.stateAddress, this.scratchSpaceAddress, sessionID, frequency);

    const advanceFn = exports.advanceBlock ? ((numFrames) => exports.advanceBlock (5255424, 5256496, numFrames))
                                           : (() => exports.advanceOneFrame (5255424, 5256496));

    this.reset = () => {
       byteMemory.fill (0, 5255424, 5256496);
       byteMemory.fill (0, 5258544, 5258544 + 4);
       exports.initialise?.(this.stateAddress, this.scratchSpaceAddress, sessionID, frequency);
    };

    this._advanceInternal = (numFrames) => {
      byteMemory.fill (0, 5256496, 5256496 + numFrames * 4);
      advanceFn (numFrames);
    };

    this._getOutputFrameInternal_out = (frameIndex) => { return memoryDataView.getFloat32 (5256496 + frameIndex * 4, true); };

    this._getOutputFramesInternal_out = (destChannelArrays, maxNumFramesToRead, destChannel) => {
      if (maxNumFramesToRead > 512)
        maxNumFramesToRead = 512;

      const channelsToCopy = Math.min (1, destChannelArrays.length - destChannel);
      let source = 5256496;

      for (let frame = 0; frame < maxNumFramesToRead; ++frame)
      {
        for (let channel = 0; channel < channelsToCopy; ++channel)
          destChannelArrays[destChannel + channel][frame] = memoryDataView.getFloat32 (source + 4 * channel, true);

        source += 4;
      }
    };

    this._pack_o1_Message_message_i32 = (address, newValue) => {
      memoryDataView.setInt32 (address, newValue.message, true);
    };

    this._pack_f32 = (address, newValue) => {
      memoryDataView.setFloat32 (address, newValue, true);
    };
  }

  //==============================================================================
  /** @access private */
  async _initialiseInternalNonSIMD (sessionID, frequency)
  {
    this.stateAddress = 5255664;
    this.scratchSpaceAddress = 5258784;

    const memory = new WebAssembly.Memory ({ initial: 82 });
    const stack = new WebAssembly.Global ({ value: "i32", mutable: true }, 5255664);
    const imports = {
      env: {
        __linear_memory: memory,
        __memory_base: 0,
        __stack_pointer: stack,
        __table_base: 0,
        memcpy:  (dst, src, len) => { this.byteMemory.copyWithin (dst, src, src + len); return dst; },
        memmove: (dst, src, len) => { this.byteMemory.copyWithin (dst, src, src + len); return dst; },
        memset:  (dst, value, len) => { this.byteMemory.fill (value, dst, dst + len); return dst; }
      },
    };

    const result = await WebAssembly.instantiate (this._getWasmBytesNonSIMD(), imports);
    this.instance = result.instance;
    const exports = this.instance.exports;
    const memoryBuffer = exports.memory?.buffer || memory.buffer;
    const memoryDataView = new DataView (memoryBuffer);
    const byteMemory = new Uint8Array (memoryBuffer);
    this.byteMemory = byteMemory;
    this.memoryDataView = memoryDataView;

    exports.initialise?.(this.stateAddress, this.scratchSpaceAddress, sessionID, frequency);

    const advanceFn = exports.advanceBlock ? ((numFrames) => exports.advanceBlock (5255664, 5256736, numFrames))
                                           : (() => exports.advanceOneFrame (5255664, 5256736));

    this.reset = () => {
       byteMemory.fill (0, 5255664, 5256736);
       byteMemory.fill (0, 5258784, 5258784 + 4);
       exports.initialise?.(this.stateAddress, this.scratchSpaceAddress, sessionID, frequency);
    };

    this._advanceInternal = (numFrames) => {
      byteMemory.fill (0, 5256736, 5256736 + numFrames * 4);
      advanceFn (numFrames);
    };

    this._getOutputFrameInternal_out = (frameIndex) => { return memoryDataView.getFloat32 (5256736 + frameIndex * 4, true); };

    this._getOutputFramesInternal_out = (destChannelArrays, maxNumFramesToRead, destChannel) => {
      if (maxNumFramesToRead > 512)
        maxNumFramesToRead = 512;

      const channelsToCopy = Math.min (1, destChannelArrays.length - destChannel);
      let source = 5256736;

      for (let frame = 0; frame < maxNumFramesToRead; ++frame)
      {
        for (let channel = 0; channel < channelsToCopy; ++channel)
          destChannelArrays[destChannel + channel][frame] = memoryDataView.getFloat32 (source + 4 * channel, true);

        source += 4;
      }
    };

    this._pack_o1_Message_message_i32 = (address, newValue) => {
      memoryDataView.setInt32 (address, newValue.message, true);
    };

    this._pack_f32 = (address, newValue) => {
      memoryDataView.setFloat32 (address, newValue, true);
    };
  }

  /** @access private */
  _getWasmBytesSIMD()
  {
    return new Uint8Array([0,97,115,109,1,0,0,0,1,158,128,128,128,0,5,96,2,127,127,0,96,2,125,127,1,125,96,3,127,127,127,0,96,4,127,127,127,124,0,96,1,125,1,125,2,175,128,128,128,0,2,3,101,110,118,15,95,95,
      108,105,110,101,97,114,95,109,101,109,111,114,121,2,0,1,3,101,110,118,15,95,95,115,116,97,99,107,95,112,111,105,110,116,101,114,3,127,1,3,142,128,128,128,0,13,0,1,2,2,2,2,2,2,2,2,3,2,4,7,217,129,128,128,
      0,11,17,95,115,101,110,100,69,118,101,110,116,95,109,105,100,105,73,110,0,0,16,95,115,101,116,86,97,108,117,101,95,118,111,108,117,109,101,0,2,22,95,115,101,116,86,97,108,117,101,95,99,97,114,114,105,101,
      114,82,97,116,105,111,0,3,24,95,115,101,116,86,97,108,117,101,95,109,111,100,117,108,97,116,111,114,82,97,116,105,111,0,4,17,95,115,101,116,86,97,108,117,101,95,102,109,73,110,100,101,120,0,5,16,95,115,
      101,116,86,97,108,117,101,95,97,116,116,97,99,107,0,6,15,95,115,101,116,86,97,108,117,101,95,100,101,99,97,121,0,7,17,95,115,101,116,86,97,108,117,101,95,115,117,115,116,97,105,110,0,8,17,95,115,101,116,
      86,97,108,117,101,95,114,101,108,101,97,115,101,0,9,10,105,110,105,116,105,97,108,105,115,101,0,10,12,97,100,118,97,110,99,101,66,108,111,99,107,0,11,12,129,128,128,128,0,2,10,141,215,128,128,0,13,191,
      28,4,4,127,5,125,1,126,1,125,2,64,2,64,2,64,2,64,32,1,40,2,0,34,1,65,128,128,192,7,113,34,2,65,128,128,192,4,71,13,0,32,1,65,255,1,113,69,13,0,32,0,65,7,65,6,65,5,65,4,65,3,65,2,32,0,40,2,176,6,34,2,32,
      0,40,2,160,6,34,3,72,34,4,32,0,40,2,192,6,34,5,32,2,32,3,32,4,27,34,2,72,34,3,27,32,0,40,2,208,6,34,4,32,5,32,2,32,3,27,34,2,72,34,3,27,32,0,40,2,224,6,34,5,32,4,32,2,32,3,27,34,2,72,34,3,27,32,0,40,2,
      240,6,34,4,32,5,32,2,32,3,27,34,2,72,34,3,27,32,0,40,2,128,7,34,5,32,4,32,2,32,3,27,34,2,72,34,3,27,32,0,40,2,144,7,32,5,32,2,32,3,27,72,27,34,3,65,4,116,106,34,2,32,1,65,16,118,65,15,113,54,2,156,6,32,
      2,65,1,59,0,152,6,32,2,32,1,65,8,118,65,255,0,113,34,4,179,34,6,56,2,164,6,32,0,32,3,65,224,0,108,106,34,3,32,6,56,2,28,32,0,32,0,40,2,152,7,65,1,106,34,5,54,2,152,7,32,2,32,5,54,2,160,6,32,3,65,24,106,
      33,0,32,1,65,255,0,113,179,67,4,2,1,60,148,33,7,2,64,32,4,65,187,127,106,178,67,171,170,170,61,148,34,8,188,34,2,65,255,255,255,255,7,113,34,1,13,0,67,0,0,128,63,33,6,12,4,11,2,64,32,1,65,129,128,128,252,
      7,73,13,0,32,8,67,0,0,0,64,146,33,6,12,4,11,2,64,2,64,32,1,65,128,128,128,252,3,70,13,0,32,1,65,128,128,128,252,7,71,13,1,32,8,67,0,0,0,0,32,2,65,127,74,27,33,6,12,5,11,67,0,0,0,64,67,0,0,0,63,32,2,65,
      127,74,27,33,6,12,4,11,32,2,65,128,128,128,248,3,70,13,2,2,64,32,2,65,128,128,128,128,4,71,13,0,67,0,0,128,64,33,6,12,4,11,2,64,32,1,65,129,128,128,232,4,73,13,0,67,0,0,128,127,67,0,0,0,0,32,2,65,0,74,
      27,33,6,12,4,11,67,0,0,128,127,33,6,32,8,67,0,0,0,0,148,32,8,32,2,65,128,96,113,190,34,9,147,146,34,10,32,9,146,34,8,188,34,1,65,128,128,128,152,4,74,13,3,2,64,32,1,65,128,128,128,152,4,71,13,0,32,10,67,
      60,170,56,51,146,32,8,32,9,147,94,13,4,32,8,188,65,255,255,255,255,7,113,33,2,12,2,11,67,0,0,0,0,33,6,32,8,188,65,255,255,255,255,7,113,34,2,65,128,128,216,152,4,75,13,3,32,1,65,128,128,216,152,124,71,
      13,1,32,10,32,8,32,9,147,95,69,13,1,12,3,11,2,64,2,64,2,64,2,64,32,2,65,128,128,128,4,70,13,0,32,1,65,255,129,192,7,113,65,128,128,192,4,71,13,1,11,32,1,65,16,118,65,15,113,33,2,32,1,65,8,118,65,255,0,
      113,179,33,6,32,0,40,2,156,6,33,1,2,64,2,64,32,0,45,0,160,7,13,0,66,1,32,2,173,134,33,11,32,1,32,2,71,13,3,32,0,42,2,164,6,32,6,92,13,3,32,0,41,3,168,7,32,11,131,80,13,1,32,0,65,1,58,0,153,6,12,3,11,2,
      64,32,1,32,2,71,13,0,32,0,42,2,164,6,32,6,92,13,0,32,0,65,1,58,0,153,6,11,2,64,32,0,40,2,172,6,32,2,71,13,0,32,0,42,2,180,6,32,6,92,13,0,32,0,65,1,58,0,169,6,11,2,64,32,0,40,2,188,6,32,2,71,13,0,32,0,42,
      2,196,6,32,6,92,13,0,32,0,65,1,58,0,185,6,11,2,64,32,0,40,2,204,6,32,2,71,13,0,32,0,42,2,212,6,32,6,92,13,0,32,0,65,1,58,0,201,6,11,2,64,32,0,40,2,220,6,32,2,71,13,0,32,0,42,2,228,6,32,6,92,13,0,32,0,65,
      1,58,0,217,6,11,2,64,32,0,40,2,236,6,32,2,71,13,0,32,0,42,2,244,6,32,6,92,13,0,32,0,65,1,58,0,233,6,11,2,64,32,0,40,2,252,6,32,2,71,13,0,32,0,42,2,132,7,32,6,92,13,0,32,0,65,1,58,0,249,6,11,32,0,40,2,140,
      7,32,2,71,13,3,32,0,42,2,148,7,32,6,92,13,3,32,0,65,1,58,0,137,7,15,11,2,64,32,0,42,2,28,32,6,92,13,0,32,0,65,0,54,2,36,11,32,0,65,0,58,0,152,6,32,0,32,0,40,2,156,7,65,1,106,34,1,54,2,156,7,32,0,32,1,54,
      2,160,6,12,1,11,32,2,65,128,128,192,5,71,13,1,32,1,65,8,118,65,255,0,113,34,2,65,202,0,70,13,1,32,2,65,192,0,71,13,1,66,1,32,1,65,16,118,65,15,113,34,2,173,134,33,11,2,64,32,1,65,255,0,113,179,67,4,2,1,
      60,148,67,0,0,0,63,96,69,13,0,32,0,32,0,41,3,168,7,32,11,132,55,3,168,7,32,2,13,2,32,0,65,1,58,0,160,7,15,11,32,0,32,0,41,3,168,7,32,11,66,127,133,131,55,3,168,7,2,64,32,2,69,13,0,2,64,32,0,40,2,156,6,
      32,2,71,13,0,32,0,45,0,152,6,69,13,0,32,0,45,0,153,6,69,13,0,2,64,32,0,42,2,164,6,32,0,42,2,28,92,13,0,32,0,65,0,54,2,36,11,32,0,65,0,58,0,152,6,32,0,32,0,40,2,156,7,65,1,106,34,1,54,2,156,7,32,0,32,1,
      54,2,160,6,11,2,64,32,0,40,2,172,6,32,2,71,13,0,32,0,45,0,168,6,69,13,0,32,0,45,0,169,6,69,13,0,2,64,32,0,42,2,180,6,32,0,42,2,124,92,13,0,32,0,65,0,54,2,132,1,11,32,0,65,0,58,0,168,6,32,0,32,0,40,2,156,
      7,65,1,106,34,1,54,2,156,7,32,0,32,1,54,2,176,6,11,2,64,32,0,40,2,188,6,32,2,71,13,0,32,0,45,0,184,6,69,13,0,32,0,45,0,185,6,69,13,0,2,64,32,0,42,2,196,6,32,0,42,2,220,1,92,13,0,32,0,65,0,54,2,228,1,11,
      32,0,65,0,58,0,184,6,32,0,32,0,40,2,156,7,65,1,106,34,1,54,2,156,7,32,0,32,1,54,2,192,6,11,2,64,32,0,40,2,204,6,32,2,71,13,0,32,0,45,0,200,6,69,13,0,32,0,45,0,201,6,69,13,0,2,64,32,0,42,2,212,6,32,0,42,
      2,188,2,92,13,0,32,0,65,0,54,2,196,2,11,32,0,65,0,58,0,200,6,32,0,32,0,40,2,156,7,65,1,106,34,1,54,2,156,7,32,0,32,1,54,2,208,6,11,2,64,32,0,40,2,220,6,32,2,71,13,0,32,0,45,0,216,6,69,13,0,32,0,45,0,217,
      6,69,13,0,2,64,32,0,42,2,228,6,32,0,42,2,156,3,92,13,0,32,0,65,0,54,2,164,3,11,32,0,65,0,58,0,216,6,32,0,32,0,40,2,156,7,65,1,106,34,1,54,2,156,7,32,0,32,1,54,2,224,6,11,2,64,32,0,40,2,236,6,32,2,71,13,
      0,32,0,45,0,232,6,69,13,0,32,0,45,0,233,6,69,13,0,2,64,32,0,42,2,244,6,32,0,42,2,252,3,92,13,0,32,0,65,0,54,2,132,4,11,32,0,65,0,58,0,232,6,32,0,32,0,40,2,156,7,65,1,106,34,1,54,2,156,7,32,0,32,1,54,2,
      240,6,11,2,64,32,0,40,2,252,6,32,2,71,13,0,32,0,45,0,248,6,69,13,0,32,0,45,0,249,6,69,13,0,2,64,32,0,42,2,132,7,32,0,42,2,220,4,92,13,0,32,0,65,0,54,2,228,4,11,32,0,65,0,58,0,248,6,32,0,32,0,40,2,156,7,
      65,1,106,34,1,54,2,156,7,32,0,32,1,54,2,128,7,11,32,0,40,2,140,7,32,2,71,13,2,32,0,45,0,136,7,69,13,2,32,0,45,0,137,7,69,13,2,2,64,32,0,42,2,148,7,32,0,42,2,188,5,92,13,0,32,0,65,0,54,2,196,5,11,32,0,65,
      0,58,0,136,7,32,0,32,0,40,2,156,7,65,1,106,34,1,54,2,156,7,32,0,32,1,54,2,144,7,15,11,32,0,65,0,58,0,160,7,2,64,32,0,45,0,152,6,69,13,0,32,0,45,0,153,6,69,13,0,2,64,32,0,42,2,164,6,32,0,42,2,28,92,13,0,
      32,0,65,0,54,2,36,11,32,0,65,0,58,0,152,6,32,0,32,0,40,2,156,7,65,1,106,34,1,54,2,156,7,32,0,32,1,54,2,160,6,11,2,64,32,0,45,0,168,6,69,13,0,32,0,45,0,169,6,69,13,0,2,64,32,0,42,2,180,6,32,0,42,2,124,92,
      13,0,32,0,65,0,54,2,132,1,11,32,0,65,0,58,0,168,6,32,0,32,0,40,2,156,7,65,1,106,34,1,54,2,156,7,32,0,32,1,54,2,176,6,11,2,64,32,0,45,0,184,6,69,13,0,32,0,45,0,185,6,69,13,0,2,64,32,0,42,2,196,6,32,0,42,
      2,220,1,92,13,0,32,0,65,0,54,2,228,1,11,32,0,65,0,58,0,184,6,32,0,32,0,40,2,156,7,65,1,106,34,1,54,2,156,7,32,0,32,1,54,2,192,6,11,2,64,32,0,45,0,200,6,69,13,0,32,0,45,0,201,6,69,13,0,2,64,32,0,42,2,212,
      6,32,0,42,2,188,2,92,13,0,32,0,65,0,54,2,196,2,11,32,0,65,0,58,0,200,6,32,0,32,0,40,2,156,7,65,1,106,34,1,54,2,156,7,32,0,32,1,54,2,208,6,11,2,64,32,0,45,0,216,6,69,13,0,32,0,45,0,217,6,69,13,0,2,64,32,
      0,42,2,228,6,32,0,42,2,156,3,92,13,0,32,0,65,0,54,2,164,3,11,32,0,65,0,58,0,216,6,32,0,32,0,40,2,156,7,65,1,106,34,1,54,2,156,7,32,0,32,1,54,2,224,6,11,2,64,32,0,45,0,232,6,69,13,0,32,0,45,0,233,6,69,13,
      0,2,64,32,0,42,2,244,6,32,0,42,2,252,3,92,13,0,32,0,65,0,54,2,132,4,11,32,0,65,0,58,0,232,6,32,0,32,0,40,2,156,7,65,1,106,34,1,54,2,156,7,32,0,32,1,54,2,240,6,11,2,64,32,0,45,0,248,6,69,13,0,32,0,45,0,
      249,6,69,13,0,2,64,32,0,42,2,132,7,32,0,42,2,220,4,92,13,0,32,0,65,0,54,2,228,4,11,32,0,65,0,58,0,248,6,32,0,32,0,40,2,156,7,65,1,106,34,1,54,2,156,7,32,0,32,1,54,2,128,7,11,32,0,45,0,136,7,69,13,1,32,
      0,45,0,137,7,69,13,1,2,64,32,0,42,2,148,7,32,0,42,2,188,5,92,13,0,32,0,65,0,54,2,196,5,11,32,0,65,0,58,0,136,7,32,0,32,0,40,2,156,7,65,1,106,34,1,54,2,156,7,32,0,32,1,54,2,144,7,12,1,11,2,64,32,0,40,2,
      172,6,32,2,71,13,0,32,0,42,2,180,6,32,6,92,13,0,2,64,32,0,41,3,168,7,32,11,131,80,13,0,32,0,65,1,58,0,169,6,12,1,11,2,64,32,0,42,2,124,32,6,92,13,0,32,0,65,0,54,2,132,1,11,32,0,65,0,58,0,168,6,32,0,32,
      0,40,2,156,7,65,1,106,34,1,54,2,156,7,32,0,32,1,54,2,176,6,11,2,64,32,0,40,2,188,6,32,2,71,13,0,32,0,42,2,196,6,32,6,92,13,0,2,64,32,0,41,3,168,7,32,11,131,80,13,0,32,0,65,1,58,0,185,6,12,1,11,2,64,32,
      0,42,2,220,1,32,6,92,13,0,32,0,65,0,54,2,228,1,11,32,0,65,0,58,0,184,6,32,0,32,0,40,2,156,7,65,1,106,34,1,54,2,156,7,32,0,32,1,54,2,192,6,11,2,64,32,0,40,2,204,6,32,2,71,13,0,32,0,42,2,212,6,32,6,92,13,
      0,2,64,32,0,41,3,168,7,32,11,131,80,13,0,32,0,65,1,58,0,201,6,12,1,11,2,64,32,0,42,2,188,2,32,6,92,13,0,32,0,65,0,54,2,196,2,11,32,0,65,0,58,0,200,6,32,0,32,0,40,2,156,7,65,1,106,34,1,54,2,156,7,32,0,32,
      1,54,2,208,6,11,2,64,32,0,40,2,220,6,32,2,71,13,0,32,0,42,2,228,6,32,6,92,13,0,2,64,32,0,41,3,168,7,32,11,131,80,13,0,32,0,65,1,58,0,217,6,12,1,11,2,64,32,0,42,2,156,3,32,6,92,13,0,32,0,65,0,54,2,164,3,
      11,32,0,65,0,58,0,216,6,32,0,32,0,40,2,156,7,65,1,106,34,1,54,2,156,7,32,0,32,1,54,2,224,6,11,2,64,32,0,40,2,236,6,32,2,71,13,0,32,0,42,2,244,6,32,6,92,13,0,2,64,32,0,41,3,168,7,32,11,131,80,13,0,32,0,
      65,1,58,0,233,6,12,1,11,2,64,32,0,42,2,252,3,32,6,92,13,0,32,0,65,0,54,2,132,4,11,32,0,65,0,58,0,232,6,32,0,32,0,40,2,156,7,65,1,106,34,1,54,2,156,7,32,0,32,1,54,2,240,6,11,2,64,32,0,40,2,252,6,32,2,71,
      13,0,32,0,42,2,132,7,32,6,92,13,0,2,64,32,0,41,3,168,7,32,11,131,80,13,0,32,0,65,1,58,0,249,6,12,1,11,2,64,32,0,42,2,220,4,32,6,92,13,0,32,0,65,0,54,2,228,4,11,32,0,65,0,58,0,248,6,32,0,32,0,40,2,156,7,
      65,1,106,34,1,54,2,156,7,32,0,32,1,54,2,128,7,11,32,0,40,2,140,7,32,2,71,13,0,32,0,42,2,148,7,32,6,92,13,0,2,64,32,0,41,3,168,7,32,11,131,80,13,0,32,0,65,1,58,0,137,7,15,11,2,64,32,0,42,2,188,5,32,6,92,
      13,0,32,0,65,0,54,2,196,5,11,32,0,65,0,58,0,136,7,32,0,32,0,40,2,156,7,65,1,106,34,1,54,2,156,7,32,0,32,1,54,2,144,7,15,11,15,11,65,0,33,3,2,64,32,2,65,128,128,128,248,3,77,13,0,65,0,65,128,128,128,4,32,
      2,65,23,118,65,130,127,106,118,32,1,106,34,2,65,255,255,255,3,113,65,128,128,128,4,114,65,150,1,32,2,65,23,118,65,255,1,113,34,4,107,118,34,3,107,32,3,32,1,65,0,72,27,33,3,32,10,32,9,65,128,128,128,124,
      32,4,65,129,127,106,117,32,2,113,190,147,34,9,146,188,33,1,11,2,64,32,3,65,23,116,32,1,65,128,128,126,113,190,34,6,67,0,114,49,63,148,34,12,32,6,67,140,190,191,53,148,32,10,32,6,32,9,147,147,67,24,114,
      49,63,148,146,34,9,146,34,6,32,6,32,6,32,6,32,6,148,34,8,32,8,32,8,32,8,32,8,67,76,187,49,51,148,67,14,234,221,181,146,148,67,85,179,138,56,146,148,67,97,11,54,187,146,148,67,171,170,42,62,146,148,147,
      34,8,148,32,8,67,0,0,0,192,146,149,32,9,32,6,32,12,147,147,34,8,32,6,32,8,148,146,147,147,67,0,0,128,63,146,34,6,188,106,34,1,65,255,255,255,3,74,13,0,32,6,32,3,16,129,128,128,128,0,33,6,12,2,11,32,1,190,
      33,6,12,1,11,67,243,4,181,63,33,6,11,32,0,32,7,56,2,12,32,0,32,6,67,0,0,220,67,148,56,2,8,11,160,1,0,2,64,2,64,2,64,32,1,65,128,1,72,13,0,32,0,67,0,0,0,127,148,33,0,32,1,65,254,1,75,13,1,32,1,65,129,127,
      106,33,1,12,2,11,32,1,65,130,127,78,13,1,32,0,67,0,0,128,12,148,33,0,2,64,32,1,65,155,126,77,13,0,32,1,65,230,0,106,33,1,12,2,11,32,0,67,0,0,128,12,148,33,0,32,1,65,182,125,32,1,65,182,125,75,27,65,204,
      1,106,33,1,12,1,11,32,0,67,0,0,0,127,148,33,0,32,1,65,253,2,32,1,65,253,2,73,27,65,130,126,106,33,1,11,32,0,32,1,65,23,116,65,128,128,128,252,3,106,190,148,11,72,1,1,125,2,64,32,0,40,2,216,7,13,0,32,0,
      32,0,40,2,0,65,1,106,54,2,0,11,32,1,42,2,0,33,3,32,0,32,2,65,1,32,2,65,1,75,27,34,2,54,2,216,7,32,0,32,3,32,0,42,2,208,7,147,32,2,178,149,56,2,212,7,11,72,1,1,125,2,64,32,0,40,2,228,7,13,0,32,0,32,0,40,
      2,0,65,1,106,54,2,0,11,32,1,42,2,0,33,3,32,0,32,2,65,1,32,2,65,1,75,27,34,2,54,2,228,7,32,0,32,3,32,0,42,2,220,7,147,32,2,178,149,56,2,224,7,11,72,1,1,125,2,64,32,0,40,2,240,7,13,0,32,0,32,0,40,2,0,65,
      1,106,54,2,0,11,32,1,42,2,0,33,3,32,0,32,2,65,1,32,2,65,1,75,27,34,2,54,2,240,7,32,0,32,3,32,0,42,2,232,7,147,32,2,178,149,56,2,236,7,11,72,1,1,125,2,64,32,0,40,2,252,7,13,0,32,0,32,0,40,2,0,65,1,106,54,
      2,0,11,32,1,42,2,0,33,3,32,0,32,2,65,1,32,2,65,1,75,27,34,2,54,2,252,7,32,0,32,3,32,0,42,2,244,7,147,32,2,178,149,56,2,248,7,11,72,1,1,125,2,64,32,0,40,2,136,8,13,0,32,0,32,0,40,2,0,65,1,106,54,2,0,11,
      32,1,42,2,0,33,3,32,0,32,2,65,1,32,2,65,1,75,27,34,2,54,2,136,8,32,0,32,3,32,0,42,2,128,8,147,32,2,178,149,56,2,132,8,11,72,1,1,125,2,64,32,0,40,2,148,8,13,0,32,0,32,0,40,2,0,65,1,106,54,2,0,11,32,1,42,
      2,0,33,3,32,0,32,2,65,1,32,2,65,1,75,27,34,2,54,2,148,8,32,0,32,3,32,0,42,2,140,8,147,32,2,178,149,56,2,144,8,11,72,1,1,125,2,64,32,0,40,2,160,8,13,0,32,0,32,0,40,2,0,65,1,106,54,2,0,11,32,1,42,2,0,33,
      3,32,0,32,2,65,1,32,2,65,1,75,27,34,2,54,2,160,8,32,0,32,3,32,0,42,2,152,8,147,32,2,178,149,56,2,156,8,11,72,1,1,125,2,64,32,0,40,2,172,8,13,0,32,0,32,0,40,2,0,65,1,106,54,2,0,11,32,1,42,2,0,33,3,32,0,
      32,2,65,1,32,2,65,1,75,27,34,2,54,2,172,8,32,0,32,3,32,0,42,2,164,8,147,32,2,178,149,56,2,168,8,11,182,1,0,32,0,66,128,128,240,158,4,55,2,192,5,32,0,65,7,54,2,184,5,32,0,66,128,128,240,158,4,55,2,224,4,
      32,0,65,6,54,2,216,4,32,0,66,128,128,240,158,4,55,2,128,4,32,0,65,5,54,2,248,3,32,0,66,128,128,240,158,4,55,2,160,3,32,0,65,4,54,2,152,3,32,0,66,128,128,240,158,4,55,2,192,2,32,0,65,3,54,2,184,2,32,0,66,
      128,128,240,158,4,55,2,224,1,32,0,65,2,54,2,216,1,32,0,66,128,128,240,158,4,55,2,128,1,32,0,65,1,54,2,120,32,0,66,128,128,240,158,4,55,2,32,32,0,65,0,54,2,24,65,0,32,3,57,3,128,128,128,128,0,32,0,66,128,
      128,128,128,23,55,2,152,7,11,196,17,5,4,127,8,125,1,127,1,123,3,127,35,128,128,128,128,0,65,32,107,34,3,36,128,128,128,128,0,2,64,32,0,40,2,4,32,2,70,13,0,32,0,65,24,106,33,4,32,3,65,16,106,33,5,3,64,2,
      64,2,64,32,0,40,2,0,34,6,13,0,32,0,42,2,204,7,33,7,32,0,42,2,200,7,33,8,32,0,42,2,196,7,33,9,32,0,42,2,192,7,33,10,32,0,42,2,188,7,33,11,32,0,42,2,184,7,33,12,32,0,42,2,180,7,33,13,32,0,42,2,176,7,33,14,
      12,1,11,2,64,32,0,40,2,216,7,34,15,69,13,0,32,0,32,15,65,127,106,34,15,54,2,216,7,32,0,32,0,42,2,212,7,32,0,42,2,208,7,146,56,2,208,7,32,15,13,0,32,0,32,6,65,127,106,34,6,54,2,0,11,2,64,32,0,40,2,228,7,
      34,15,69,13,0,32,0,32,15,65,127,106,34,15,54,2,228,7,32,0,32,0,42,2,224,7,32,0,42,2,220,7,146,56,2,220,7,32,15,13,0,32,0,32,6,65,127,106,34,6,54,2,0,11,2,64,32,0,40,2,240,7,34,15,69,13,0,32,0,32,15,65,
      127,106,34,15,54,2,240,7,32,0,32,0,42,2,236,7,32,0,42,2,232,7,146,56,2,232,7,32,15,13,0,32,0,32,6,65,127,106,34,6,54,2,0,11,2,64,32,0,40,2,252,7,34,15,69,13,0,32,0,32,15,65,127,106,34,15,54,2,252,7,32,
      0,32,0,42,2,248,7,32,0,42,2,244,7,146,56,2,244,7,32,15,13,0,32,0,32,6,65,127,106,34,6,54,2,0,11,2,64,32,0,40,2,136,8,34,15,69,13,0,32,0,32,15,65,127,106,34,15,54,2,136,8,32,0,32,0,42,2,132,8,32,0,42,2,
      128,8,146,56,2,128,8,32,15,13,0,32,0,32,6,65,127,106,34,6,54,2,0,11,2,64,32,0,40,2,148,8,34,15,69,13,0,32,0,32,15,65,127,106,34,15,54,2,148,8,32,0,32,0,42,2,144,8,32,0,42,2,140,8,146,56,2,140,8,32,15,13,
      0,32,0,32,6,65,127,106,34,6,54,2,0,11,2,64,32,0,40,2,160,8,34,15,69,13,0,32,0,32,15,65,127,106,34,15,54,2,160,8,32,0,32,0,42,2,156,8,32,0,42,2,152,8,146,56,2,152,8,32,15,13,0,32,0,32,6,65,127,106,34,6,
      54,2,0,11,32,0,42,2,164,8,33,7,2,64,32,0,40,2,172,8,34,15,69,13,0,32,0,32,15,65,127,106,34,15,54,2,172,8,32,0,32,0,42,2,168,8,32,7,146,34,7,56,2,164,8,32,15,13,0,32,0,32,6,65,127,106,54,2,0,11,32,0,32,
      7,56,2,204,7,32,0,32,0,42,2,208,7,34,14,56,2,176,7,32,0,32,0,42,2,220,7,34,13,56,2,180,7,32,0,32,0,42,2,232,7,34,12,56,2,184,7,32,0,32,0,42,2,244,7,34,11,56,2,188,7,32,0,32,0,42,2,128,8,34,10,56,2,192,
      7,32,0,32,0,42,2,140,8,34,9,56,2,196,7,32,0,32,0,42,2,152,8,34,8,56,2,200,7,11,32,0,32,14,56,2,248,5,32,0,32,14,56,2,152,5,32,0,32,14,56,2,184,4,32,0,32,14,56,2,216,3,32,0,32,14,56,2,248,2,32,0,32,14,56,
      2,152,2,32,0,32,14,56,2,184,1,32,0,32,14,56,2,88,32,0,32,13,56,2,252,5,32,0,32,13,56,2,156,5,32,0,32,13,56,2,188,4,32,0,32,13,56,2,220,3,32,0,32,13,56,2,252,2,32,0,32,13,56,2,156,2,32,0,32,13,56,2,188,
      1,32,0,32,13,56,2,92,32,5,253,12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,34,16,253,11,3,0,32,3,32,16,253,11,3,0,32,0,32,12,56,2,128,6,32,0,32,12,56,2,160,5,32,0,32,12,56,2,192,4,32,0,32,12,56,2,224,3,32,0,32,12,
      56,2,128,3,32,0,32,12,56,2,160,2,32,0,32,12,56,2,192,1,32,0,32,12,56,2,96,32,0,32,11,56,2,100,32,0,32,11,56,2,196,1,32,0,32,11,56,2,164,2,32,0,32,11,56,2,132,3,32,0,32,11,56,2,228,3,32,0,32,11,56,2,196,
      4,32,0,32,11,56,2,164,5,32,0,32,11,56,2,132,6,32,0,32,10,56,2,104,32,0,32,10,56,2,200,1,32,0,32,10,56,2,168,2,32,0,32,10,56,2,136,3,32,0,32,10,56,2,232,3,32,0,32,10,56,2,200,4,32,0,32,10,56,2,168,5,32,
      0,32,10,56,2,136,6,32,0,32,9,56,2,140,6,32,0,32,9,56,2,172,5,32,0,32,9,56,2,204,4,32,0,32,9,56,2,236,3,32,0,32,9,56,2,140,3,32,0,32,9,56,2,172,2,32,0,32,9,56,2,204,1,32,0,32,9,56,2,108,32,0,32,8,56,2,144,
      6,32,0,32,8,56,2,176,5,32,0,32,8,56,2,208,4,32,0,32,8,56,2,240,3,32,0,32,8,56,2,144,3,32,0,32,8,56,2,176,2,32,0,32,8,56,2,208,1,32,0,32,8,56,2,112,32,0,32,7,56,2,148,6,32,0,32,7,56,2,180,5,32,0,32,7,56,
      2,212,4,32,0,32,7,56,2,244,3,32,0,32,7,56,2,148,3,32,0,32,7,56,2,180,2,32,0,32,7,56,2,212,1,32,0,32,7,56,2,116,65,0,33,15,65,0,43,3,128,128,128,128,0,182,33,11,3,64,67,0,0,0,0,33,10,65,0,33,17,67,0,0,0,
      0,33,8,2,64,32,4,32,15,65,224,0,108,106,34,6,40,2,16,65,127,70,13,0,32,6,65,1,54,2,16,32,6,42,2,12,67,0,0,0,0,94,33,17,32,6,42,2,8,67,0,0,0,0,146,33,8,11,2,64,32,6,40,2,24,65,127,70,13,0,32,6,42,2,20,34,
      7,67,0,0,0,0,146,67,219,15,201,64,148,16,140,128,128,128,0,33,9,2,64,32,7,32,8,32,6,42,2,72,148,67,0,0,0,0,146,32,11,149,146,34,7,67,0,0,128,63,96,69,13,0,3,64,32,7,67,0,0,128,191,146,34,7,67,0,0,128,63,
      96,13,0,11,11,32,6,32,7,56,2,20,2,64,32,7,67,0,0,0,0,93,69,13,0,3,64,32,7,67,0,0,128,63,146,34,7,67,0,0,0,0,93,13,0,11,32,6,32,7,56,2,20,11,32,6,65,1,54,2,24,32,9,67,0,0,0,0,146,33,10,11,67,0,0,0,0,33,
      9,67,0,0,0,0,33,7,2,64,32,6,40,2,32,65,127,70,13,0,32,10,32,6,42,2,76,148,67,0,0,0,0,146,32,6,42,2,28,34,7,146,67,219,15,201,64,148,16,140,128,128,128,0,33,10,2,64,32,7,32,8,32,6,42,2,68,148,67,0,0,0,0,
      146,32,11,149,146,34,7,67,0,0,128,63,96,69,13,0,3,64,32,7,67,0,0,128,191,146,34,7,67,0,0,128,63,96,13,0,11,11,32,6,32,7,56,2,28,2,64,32,7,67,0,0,0,0,93,69,13,0,3,64,32,7,67,0,0,128,63,146,34,7,67,0,0,0,
      0,93,13,0,11,32,6,32,7,56,2,28,11,32,6,65,1,54,2,32,32,10,67,0,0,0,0,146,33,7,11,32,3,32,15,65,2,116,106,33,18,32,6,32,6,42,2,80,34,12,56,2,44,32,6,32,6,42,2,84,34,13,56,2,48,32,6,32,6,42,2,88,34,10,56,
      2,52,32,6,32,6,42,2,92,34,8,56,2,56,2,64,32,6,40,2,60,65,127,70,13,0,32,6,40,2,40,33,19,2,64,2,64,2,64,2,64,2,64,2,64,2,64,2,64,2,64,32,17,69,13,0,32,19,14,5,1,2,3,4,1,7,11,32,19,65,123,113,13,4,32,19,
      65,127,106,14,4,1,2,3,5,6,11,32,6,65,1,54,2,40,11,32,6,67,0,0,128,63,67,0,0,128,63,32,12,32,11,148,34,8,149,32,8,67,0,0,128,63,93,27,32,6,42,2,36,146,34,8,56,2,36,32,8,67,0,0,128,63,96,69,13,5,32,6,66,
      128,128,128,252,35,55,2,36,67,0,0,128,63,33,8,12,5,11,32,6,32,6,42,2,36,67,0,0,128,63,67,0,0,128,63,32,10,147,32,13,32,11,148,34,8,149,32,8,67,0,0,128,63,93,27,147,34,8,56,2,36,32,8,32,10,95,69,13,4,32,
      6,65,3,54,2,40,11,32,6,32,10,56,2,36,32,10,33,8,12,3,11,32,6,65,4,54,2,40,11,32,6,32,6,42,2,36,34,9,32,9,32,9,32,8,32,11,148,34,8,149,32,8,67,0,0,128,63,93,27,147,34,8,56,2,36,32,8,67,0,0,0,0,95,69,13,
      1,32,6,66,0,55,2,36,67,0,0,0,0,33,8,12,1,11,32,6,42,2,36,33,8,11,32,6,65,1,54,2,60,32,8,67,0,0,0,0,146,33,9,11,32,18,32,18,42,2,0,32,7,32,9,148,32,6,42,2,64,148,146,56,2,0,32,15,65,1,106,34,15,65,8,71,
      13,0,11,32,1,32,0,40,2,4,65,2,116,106,32,3,42,2,28,32,3,42,2,24,32,3,42,2,20,32,3,42,2,16,32,3,42,2,12,32,3,42,2,8,32,3,42,2,4,32,3,42,2,0,67,0,0,0,0,146,146,146,146,146,146,146,146,56,2,0,32,0,32,0,40,
      2,4,65,1,106,34,6,54,2,4,32,6,32,2,71,13,0,11,11,32,0,65,0,54,2,4,32,3,65,32,106,36,128,128,128,128,0,11,225,33,10,3,127,3,124,1,127,1,123,7,127,1,124,8,127,16,123,2,126,2,127,35,128,128,128,128,0,65,128,
      3,107,34,1,36,128,128,128,128,0,2,64,2,64,32,0,188,34,2,65,255,255,255,255,7,113,34,3,65,218,159,164,250,3,75,13,0,32,0,32,0,187,34,4,32,4,162,34,5,32,4,162,34,6,32,5,32,5,162,162,32,5,68,167,70,59,140,
      135,205,198,62,162,68,116,231,202,226,249,0,42,191,160,162,32,6,32,5,68,178,251,110,137,16,17,129,63,162,68,119,172,203,84,85,85,197,191,160,162,32,4,160,160,182,32,3,65,128,128,128,204,3,73,27,33,0,12,
      1,11,2,64,2,64,2,64,2,64,32,3,65,210,167,237,131,4,73,13,0,32,3,65,214,227,136,135,4,79,13,2,32,0,187,33,5,32,3,65,224,219,191,133,4,79,13,1,68,0,0,0,0,0,0,240,63,32,5,68,210,33,51,127,124,217,18,64,160,
      34,4,32,4,162,34,4,68,129,94,12,253,255,255,223,63,162,161,32,4,32,4,162,34,6,68,66,58,5,225,83,85,165,63,162,160,32,4,32,6,162,32,4,68,105,80,238,224,66,147,249,62,162,68,39,30,15,232,135,192,86,191,160,
      162,160,182,68,0,0,0,0,0,0,240,63,32,5,68,210,33,51,127,124,217,18,192,160,34,5,32,5,162,34,5,68,129,94,12,253,255,255,223,63,162,161,32,5,32,5,162,34,4,68,66,58,5,225,83,85,165,63,162,160,32,5,32,4,162,
      32,5,68,105,80,238,224,66,147,249,62,162,68,39,30,15,232,135,192,86,191,160,162,160,182,140,32,2,65,0,72,27,33,0,12,4,11,32,0,187,33,5,32,3,65,228,151,219,128,4,73,13,2,68,24,45,68,84,251,33,9,64,68,24,
      45,68,84,251,33,9,192,32,2,65,0,72,27,32,5,160,34,4,32,4,162,34,5,32,4,154,162,34,6,32,5,32,5,162,162,32,5,68,167,70,59,140,135,205,198,62,162,68,116,231,202,226,249,0,42,191,160,162,32,6,32,5,68,178,251,
      110,137,16,17,129,63,162,68,119,172,203,84,85,85,197,191,160,162,32,4,161,160,182,33,0,12,3,11,68,24,45,68,84,251,33,25,64,68,24,45,68,84,251,33,25,192,32,2,65,0,72,27,32,5,160,34,4,32,4,32,4,162,34,5,
      162,34,6,32,5,32,5,162,162,32,5,68,167,70,59,140,135,205,198,62,162,68,116,231,202,226,249,0,42,191,160,162,32,4,32,6,32,5,68,178,251,110,137,16,17,129,63,162,68,119,172,203,84,85,85,197,191,160,162,160,
      160,182,33,0,12,2,11,2,64,32,3,65,255,255,255,251,7,75,13,0,2,64,2,64,32,3,65,218,159,164,238,4,75,13,0,32,0,187,34,5,32,5,68,131,200,201,109,48,95,228,63,162,68,0,0,0,0,0,0,56,67,160,68,0,0,0,0,0,0,56,
      195,160,34,4,68,0,0,0,80,251,33,249,191,162,160,32,4,68,99,98,26,97,180,16,81,190,162,160,33,5,32,4,252,2,33,7,12,1,11,32,1,66,128,128,128,128,208,227,252,180,53,55,3,248,2,32,1,66,128,128,128,128,168,
      196,224,241,54,55,3,240,2,32,1,66,128,128,128,128,132,164,137,189,56,55,3,232,2,32,1,66,128,128,128,128,184,240,134,248,57,55,3,224,2,32,1,66,128,128,128,128,150,138,179,188,59,55,3,216,2,32,1,66,128,128,
      128,128,136,211,145,252,60,55,3,208,2,32,1,66,128,128,128,128,208,133,145,186,62,55,3,200,2,32,1,66,128,128,128,128,180,191,200,252,63,55,3,192,2,2,64,65,128,1,69,13,0,32,1,65,192,1,106,65,0,65,128,1,252,
      11,0,11,2,64,65,224,0,69,13,0,32,1,65,192,0,106,65,32,106,65,0,65,224,0,252,11,0,11,32,1,65,16,106,253,12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,34,8,253,11,3,0,32,1,65,32,106,32,8,253,11,3,0,32,1,65,48,106,32,
      8,253,11,3,0,32,1,32,8,253,11,3,0,32,1,32,3,32,3,65,23,118,34,9,65,234,126,106,34,10,65,23,116,107,190,187,34,6,32,9,65,231,126,106,65,255,1,113,65,24,110,34,11,65,2,116,34,3,65,156,128,128,128,0,106,40,
      2,0,183,162,68,0,0,0,0,0,0,0,0,160,57,3,88,32,1,32,6,32,3,65,152,128,128,128,0,106,40,2,0,183,162,68,0,0,0,0,0,0,0,0,160,57,3,80,32,1,32,6,32,3,65,148,128,128,128,0,106,40,2,0,183,162,68,0,0,0,0,0,0,0,
      0,160,57,3,72,32,1,32,6,32,3,65,144,128,128,128,0,106,40,2,0,183,162,68,0,0,0,0,0,0,0,0,160,57,3,64,65,47,32,11,65,104,108,32,10,106,34,12,107,33,13,65,48,32,12,107,33,14,32,12,65,104,106,33,15,32,12,65,
      231,7,106,173,66,52,134,191,33,16,32,6,253,20,33,8,32,1,65,100,106,33,17,32,12,65,25,72,33,18,32,12,65,103,106,33,19,65,3,33,20,3,64,32,1,65,192,0,106,32,20,34,21,65,15,113,34,22,65,3,116,106,43,3,0,33,
      5,2,64,32,21,65,1,72,34,10,13,0,32,21,65,127,106,33,3,65,0,33,9,3,64,32,1,32,9,65,15,113,65,2,116,106,32,5,32,5,68,0,0,0,0,0,0,112,62,162,252,2,183,34,4,68,0,0,0,0,0,0,112,193,162,160,252,2,54,2,0,32,1,
      65,192,0,106,32,3,65,15,113,65,3,116,106,43,3,0,32,4,160,33,5,32,9,65,1,106,33,9,32,3,65,127,106,34,3,65,127,71,13,0,11,11,32,5,32,16,162,34,5,32,5,68,0,0,0,0,0,0,192,63,162,156,68,0,0,0,0,0,0,32,192,162,
      160,34,5,32,5,252,2,34,7,183,161,33,5,2,64,2,64,2,64,2,64,32,18,13,0,32,1,32,21,65,127,106,65,15,113,65,2,116,106,34,3,32,3,40,2,0,34,3,32,3,32,14,117,34,3,32,14,116,107,34,9,54,2,0,32,9,32,13,117,33,23,
      32,3,32,7,106,33,7,12,1,11,2,64,32,15,13,0,32,1,32,21,65,127,106,65,15,113,65,2,116,106,40,2,0,65,23,117,33,23,12,1,11,65,2,33,23,65,0,33,24,32,5,68,0,0,0,0,0,0,224,63,102,69,13,2,12,1,11,32,23,65,0,74,
      13,0,32,23,33,24,12,1,11,2,64,2,64,32,10,69,13,0,65,0,33,10,12,1,11,65,0,33,3,65,0,33,10,3,64,32,1,32,3,65,15,113,65,2,116,106,34,20,40,2,0,33,9,2,64,2,64,2,64,2,64,32,10,65,1,113,69,13,0,65,255,255,255,
      7,33,10,12,1,11,32,9,69,13,1,65,128,128,128,8,33,10,11,32,20,32,10,32,9,107,54,2,0,65,1,33,10,12,1,11,65,0,33,10,11,32,21,32,3,65,1,106,34,3,71,13,0,11,11,2,64,32,18,13,0,65,255,255,255,3,33,3,2,64,2,64,
      32,19,14,2,1,0,2,11,65,255,255,255,1,33,3,11,32,1,32,21,65,127,106,65,15,113,65,2,116,106,34,9,32,9,40,2,0,32,3,113,54,2,0,11,32,7,65,1,106,33,7,65,2,33,24,32,23,65,2,71,13,0,68,0,0,0,0,0,0,240,63,32,5,
      161,34,5,32,16,161,32,5,32,10,27,33,5,11,2,64,2,64,2,64,32,5,68,0,0,0,0,0,0,0,0,98,13,0,32,21,65,127,106,34,3,65,2,76,13,2,65,0,33,9,2,64,2,64,32,21,65,125,106,34,23,65,7,77,13,0,32,21,65,127,106,65,15,
      113,65,3,73,13,0,32,21,65,108,106,65,112,73,13,0,65,0,33,10,65,0,33,9,2,64,32,23,65,32,73,13,0,32,1,32,3,65,15,113,65,2,116,106,34,9,65,132,127,106,34,10,253,0,2,0,32,8,253,13,12,13,14,15,8,9,10,11,4,5,
      6,7,0,1,2,3,33,25,32,10,253,0,2,16,32,8,253,13,12,13,14,15,8,9,10,11,4,5,6,7,0,1,2,3,33,26,32,9,65,164,127,106,34,10,253,0,2,0,32,8,253,13,12,13,14,15,8,9,10,11,4,5,6,7,0,1,2,3,33,27,32,10,253,0,2,16,32,
      8,253,13,12,13,14,15,8,9,10,11,4,5,6,7,0,1,2,3,33,28,32,9,65,68,106,34,10,253,0,2,0,32,8,253,13,12,13,14,15,8,9,10,11,4,5,6,7,0,1,2,3,33,29,32,10,253,0,2,16,32,8,253,13,12,13,14,15,8,9,10,11,4,5,6,7,0,
      1,2,3,33,30,32,9,65,100,106,34,9,253,0,2,0,32,8,253,13,12,13,14,15,8,9,10,11,4,5,6,7,0,1,2,3,33,31,32,9,253,0,2,16,32,8,253,13,12,13,14,15,8,9,10,11,4,5,6,7,0,1,2,3,33,32,32,23,65,96,113,34,10,33,9,253,
      12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,34,33,33,34,32,33,33,35,32,33,33,36,32,33,33,37,32,33,33,38,32,33,33,39,32,33,33,40,3,64,32,26,32,39,253,80,33,39,32,28,32,37,253,80,33,37,32,30,32,35,253,80,33,35,32,
      32,32,33,253,80,33,33,32,25,32,40,253,80,33,40,32,27,32,38,253,80,33,38,32,29,32,36,253,80,33,36,32,31,32,34,253,80,33,34,32,9,65,96,106,34,9,13,0,11,32,39,32,37,32,35,32,33,253,80,253,80,253,80,32,40,
      32,38,32,36,32,34,253,80,253,80,253,80,253,80,34,33,32,33,32,8,253,13,8,9,10,11,12,13,14,15,0,1,2,3,0,1,2,3,253,80,34,33,32,33,32,8,253,13,4,5,6,7,0,1,2,3,0,1,2,3,0,1,2,3,253,80,253,27,0,33,9,32,23,32,
      10,70,13,2,32,23,65,24,113,13,0,32,3,32,10,107,33,3,12,1,11,253,12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,34,33,32,9,253,28,0,33,34,32,10,65,127,115,32,21,106,33,9,32,10,32,23,65,120,113,34,22,107,33,10,32,3,
      32,22,107,33,3,3,64,32,17,32,9,65,15,113,65,2,116,106,34,20,253,0,2,0,32,8,253,13,12,13,14,15,8,9,10,11,4,5,6,7,0,1,2,3,32,33,253,80,33,33,32,20,253,0,2,16,32,8,253,13,12,13,14,15,8,9,10,11,4,5,6,7,0,1,
      2,3,32,34,253,80,33,34,32,9,65,120,106,33,9,32,10,65,8,106,34,10,13,0,11,32,34,32,33,253,80,34,33,32,33,32,8,253,13,8,9,10,11,12,13,14,15,0,1,2,3,0,1,2,3,253,80,34,33,32,33,32,8,253,13,4,5,6,7,0,1,2,3,
      0,1,2,3,0,1,2,3,253,80,253,27,0,33,9,32,23,32,22,70,13,1,11,3,64,32,1,32,3,65,15,113,65,2,116,106,40,2,0,32,9,114,33,9,32,3,65,3,75,33,10,32,3,65,127,106,33,3,32,10,13,0,11,11,32,9,69,13,2,3,64,32,15,65,
      104,106,33,15,32,1,32,21,65,127,106,34,21,65,15,113,65,2,116,106,40,2,0,69,13,0,12,2,11,11,2,64,2,64,32,5,65,151,8,32,12,107,173,66,52,134,191,162,34,5,68,0,0,0,0,0,0,112,65,102,69,13,0,32,1,32,22,65,2,
      116,106,32,5,32,5,68,0,0,0,0,0,0,112,62,162,252,2,34,3,183,68,0,0,0,0,0,0,112,193,162,160,252,2,54,2,0,32,21,65,1,106,34,21,65,15,113,33,22,32,12,33,15,12,1,11,32,5,252,2,33,3,11,32,1,32,22,65,2,116,106,
      32,3,54,2,0,11,2,64,2,64,2,64,2,64,32,15,65,128,8,72,13,0,32,15,65,254,15,75,13,1,32,15,65,129,120,106,33,15,68,0,0,0,0,0,0,224,127,33,5,12,3,11,32,15,65,130,120,72,13,1,68,0,0,0,0,0,0,240,63,33,5,12,2,
      11,32,15,65,253,23,32,15,65,253,23,73,27,65,130,112,106,33,15,68,0,0,0,0,0,0,240,127,33,5,12,1,11,2,64,32,15,65,184,112,77,13,0,32,15,65,201,7,106,33,15,68,0,0,0,0,0,0,96,3,33,5,12,1,11,32,15,65,240,104,
      32,15,65,240,104,75,27,65,146,15,106,33,15,68,0,0,0,0,0,0,0,0,33,5,11,2,64,2,64,32,21,65,0,78,13,0,68,0,0,0,0,0,0,0,0,33,5,12,1,11,32,5,32,15,65,255,7,106,173,66,52,134,191,162,33,5,32,21,33,3,3,64,32,
      1,65,192,0,106,32,3,65,15,113,34,9,65,3,116,106,32,5,32,1,32,9,65,2,116,106,40,2,0,183,162,57,3,0,32,5,68,0,0,0,0,0,0,112,62,162,33,5,32,3,65,127,106,34,3,65,127,71,13,0,11,65,0,33,11,32,21,33,10,3,64,
      32,11,65,3,32,11,65,3,73,27,65,1,106,33,20,68,0,0,0,0,0,0,0,0,33,5,32,1,65,192,2,106,33,3,65,0,33,9,3,64,32,5,32,1,65,192,0,106,32,10,32,9,106,65,15,113,65,3,116,106,43,3,0,32,3,43,3,0,162,160,33,5,32,
      3,65,8,106,33,3,32,20,32,9,65,1,106,34,9,71,13,0,11,32,1,65,192,1,106,32,21,32,10,107,65,15,113,65,3,116,106,32,5,57,3,0,32,10,65,127,106,33,10,32,11,32,21,71,33,3,32,11,65,1,106,33,11,32,3,13,0,11,68,
      0,0,0,0,0,0,0,0,33,5,3,64,32,5,32,1,65,192,1,106,32,21,65,15,113,65,3,116,106,43,3,0,160,33,5,32,21,65,127,106,34,21,65,127,71,13,0,11,11,32,5,154,32,5,32,24,27,33,5,32,2,65,127,74,13,2,65,0,32,7,107,33,
      7,32,5,154,33,5,12,2,11,65,0,33,3,3,64,32,3,34,9,65,127,106,33,3,32,1,32,9,65,2,106,65,15,113,65,2,116,106,40,2,0,69,13,0,11,32,21,65,1,106,34,10,32,21,32,3,107,34,20,74,13,0,2,64,32,21,65,127,115,34,7,
      32,20,172,66,1,124,34,41,32,21,65,2,106,34,3,172,34,42,32,41,32,42,85,27,34,41,167,106,34,43,65,12,73,13,0,32,3,32,41,32,42,125,34,41,167,34,23,106,32,3,72,13,0,65,14,32,21,107,65,15,113,32,23,65,15,113,
      73,13,0,32,41,66,15,86,13,0,32,7,32,10,32,9,107,172,66,1,124,34,41,32,42,32,41,32,42,85,27,167,106,65,124,113,33,24,32,11,32,21,106,33,22,32,10,32,43,65,124,113,34,44,106,33,10,65,0,33,3,3,64,32,1,65,192,
      0,106,32,21,32,3,106,65,1,106,65,15,113,65,3,116,106,34,23,32,8,32,22,32,3,106,34,9,65,3,106,65,194,0,111,34,7,65,194,0,106,32,7,32,7,65,0,72,27,65,2,116,65,144,128,128,128,0,106,40,2,0,183,253,20,32,9,
      65,4,106,65,194,0,111,34,7,65,194,0,106,32,7,32,7,65,0,72,27,65,2,116,65,144,128,128,128,0,106,40,2,0,183,253,34,1,253,242,1,253,12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,34,33,253,240,1,253,11,3,16,32,23,32,
      8,32,9,65,1,106,65,194,0,111,34,7,65,194,0,106,32,7,32,7,65,0,72,27,65,2,116,65,144,128,128,128,0,106,40,2,0,183,253,20,32,9,65,2,106,65,194,0,111,34,9,65,194,0,106,32,9,32,9,65,0,72,27,65,2,116,65,144,
      128,128,128,0,106,40,2,0,183,253,34,1,253,242,1,32,33,253,240,1,253,11,3,0,32,24,32,3,65,4,106,34,3,71,13,0,11,32,43,32,44,70,13,1,11,3,64,32,1,65,192,0,106,32,10,65,15,113,65,3,116,106,32,6,32,11,32,10,
      106,65,194,0,111,34,3,65,194,0,106,32,3,32,3,65,0,72,27,65,2,116,65,144,128,128,128,0,106,40,2,0,183,162,68,0,0,0,0,0,0,0,0,160,57,3,0,32,10,65,1,106,34,10,32,20,76,13,0,12,1,11,11,11,2,64,2,64,2,64,2,
      64,32,7,65,3,113,14,4,0,1,2,3,0,11,32,5,32,5,32,5,162,34,4,162,34,6,32,4,32,4,162,162,32,4,68,167,70,59,140,135,205,198,62,162,68,116,231,202,226,249,0,42,191,160,162,32,5,32,6,32,4,68,178,251,110,137,
      16,17,129,63,162,68,119,172,203,84,85,85,197,191,160,162,160,160,182,33,0,12,5,11,32,5,32,5,162,34,5,68,129,94,12,253,255,255,223,191,162,68,0,0,0,0,0,0,240,63,160,32,5,32,5,162,34,4,68,66,58,5,225,83,
      85,165,63,162,160,32,5,32,4,162,32,5,68,105,80,238,224,66,147,249,62,162,68,39,30,15,232,135,192,86,191,160,162,160,182,33,0,12,4,11,32,5,32,5,162,34,4,32,5,154,162,34,6,32,4,32,4,162,162,32,4,68,167,70,
      59,140,135,205,198,62,162,68,116,231,202,226,249,0,42,191,160,162,32,6,32,4,68,178,251,110,137,16,17,129,63,162,68,119,172,203,84,85,85,197,191,160,162,32,5,161,160,182,33,0,12,3,11,32,5,32,5,162,34,5,
      68,129,94,12,253,255,255,223,191,162,68,0,0,0,0,0,0,240,63,160,32,5,32,5,162,34,4,68,66,58,5,225,83,85,165,63,162,160,32,5,32,4,162,32,5,68,105,80,238,224,66,147,249,62,162,68,39,30,15,232,135,192,86,191,
      160,162,160,182,140,33,0,12,2,11,32,0,32,0,147,33,0,12,1,11,68,0,0,0,0,0,0,240,63,32,5,68,24,45,68,84,251,33,249,63,160,34,4,32,4,162,34,4,68,129,94,12,253,255,255,223,63,162,161,32,4,32,4,162,34,6,68,
      66,58,5,225,83,85,165,63,162,160,32,4,32,6,162,32,4,68,105,80,238,224,66,147,249,62,162,68,39,30,15,232,135,192,86,191,160,162,160,182,140,68,0,0,0,0,0,0,240,63,32,5,68,24,45,68,84,251,33,249,191,160,34,
      5,32,5,162,34,5,68,129,94,12,253,255,255,223,63,162,161,32,5,32,5,162,34,4,68,66,58,5,225,83,85,165,63,162,160,32,5,32,4,162,32,5,68,105,80,238,224,66,147,249,62,162,68,39,30,15,232,135,192,86,191,160,
      162,160,182,32,2,65,0,72,27,33,0,11,32,1,65,128,3,106,36,128,128,128,128,0,32,0,11,11,156,130,128,128,0,2,0,65,0,11,8,0,0,0,0,0,0,0,0,0,65,16,11,136,2,131,249,162,0,68,78,110,0,252,41,21,0,209,87,39,0,
      221,52,245,0,98,219,192,0,60,153,149,0,65,144,67,0,99,81,254,0,187,222,171,0,183,97,197,0,58,110,36,0,210,77,66,0,73,6,224,0,9,234,46,0,28,146,209,0,235,29,254,0,41,177,28,0,232,62,167,0,245,53,130,0,68,
      187,46,0,156,233,132,0,180,38,112,0,65,126,95,0,214,145,57,0,83,131,57,0,156,244,57,0,139,95,132,0,40,249,189,0,248,31,59,0,222,255,151,0,15,152,5,0,17,47,239,0,10,90,139,0,109,31,109,0,207,126,54,0,9,
      203,39,0,70,79,183,0,158,102,63,0,45,234,95,0,186,39,117,0,229,235,199,0,61,123,241,0,247,57,7,0,146,82,138,0,251,107,234,0,31,177,95,0,8,93,141,0,48,3,86,0,123,252,70,0,240,171,107,0,32,188,207,0,54,244,
      154,0,227,169,29,0,94,97,145,0,8,27,230,0,133,153,101,0,160,20,95,0,141,64,104,0,128,216,255,0,39,115,77,0,6,6,49,0,202,86,21,0,201,168,115,0,123,226,96,0,107,140,192,0,0,216,131,128,128,0,7,108,105,110,
      107,105,110,103,2,8,146,131,128,128,0,16,0,32,0,17,95,115,101,110,100,69,118,101,110,116,95,109,105,100,105,73,110,0,2,1,67,46,76,115,116,100,95,95,105,110,116,114,105,110,115,105,99,115,95,95,105,110,
      116,101,114,110,97,108,95,95,109,97,116,104,95,105,109,112,108,101,109,101,110,116,97,116,105,111,110,115,95,95,104,101,108,112,101,114,115,95,95,115,99,97,108,98,110,102,0,32,2,16,95,115,101,116,86,97,
      108,117,101,95,118,111,108,117,109,101,0,32,3,22,95,115,101,116,86,97,108,117,101,95,99,97,114,114,105,101,114,82,97,116,105,111,0,32,4,24,95,115,101,116,86,97,108,117,101,95,109,111,100,117,108,97,116,
      111,114,82,97,116,105,111,0,32,5,17,95,115,101,116,86,97,108,117,101,95,102,109,73,110,100,101,120,0,32,6,16,95,115,101,116,86,97,108,117,101,95,97,116,116,97,99,107,0,32,7,15,95,115,101,116,86,97,108,
      117,101,95,100,101,99,97,121,0,32,8,17,95,115,101,116,86,97,108,117,101,95,115,117,115,116,97,105,110,0,32,9,17,95,115,101,116,86,97,108,117,101,95,114,101,108,101,97,115,101,0,32,10,10,105,110,105,116,
      105,97,108,105,115,101,1,2,14,46,76,103,95,95,102,114,101,113,117,101,110,99,121,0,0,8,0,32,11,12,97,100,118,97,110,99,101,66,108,111,99,107,2,16,0,0,2,12,54,46,76,115,116,100,95,95,105,110,116,114,105,
      110,115,105,99,115,95,95,105,110,116,101,114,110,97,108,95,95,109,97,116,104,95,105,109,112,108,101,109,101,110,116,97,116,105,111,110,115,95,95,115,105,110,1,2,15,46,76,103,95,95,95,99,111,110,115,116,
      97,110,116,95,1,0,136,2,5,177,128,128,128,0,2,19,46,98,115,115,46,46,76,103,95,95,102,114,101,113,117,101,110,99,121,3,0,23,46,114,111,100,97,116,97,46,46,76,103,95,95,95,99,111,110,115,116,97,110,116,
      95,4,0,0,232,128,128,128,0,10,114,101,108,111,99,46,67,79,68,69,5,20,0,147,28,1,3,210,35,11,0,7,242,35,13,7,253,35,13,3,239,45,11,0,0,226,46,14,0,154,48,14,7,164,53,13,7,194,53,13,7,206,53,13,4,144,61,
      15,12,4,175,61,15,8,4,206,61,15,4,4,237,61,15,0,4,208,80,15,0,4,247,80,15,0,4,193,81,15,0,4,232,81,15,0,4,196,82,15,0,7,133,87,13,0,157,129,128,128,0,15,116,97,114,103,101,116,95,102,101,97,116,117,114,
      101,115,9,43,11,98,117,108,107,45,109,101,109,111,114,121,43,15,98,117,108,107,45,109,101,109,111,114,121,45,111,112,116,43,22,99,97,108,108,45,105,110,100,105,114,101,99,116,45,111,118,101,114,108,111,
      110,103,43,10,109,117,108,116,105,118,97,108,117,101,43,15,109,117,116,97,98,108,101,45,103,108,111,98,97,108,115,43,19,110,111,110,116,114,97,112,112,105,110,103,45,102,112,116,111,105,110,116,43,15,114,
      101,102,101,114,101,110,99,101,45,116,121,112,101,115,43,8,115,105,103,110,45,101,120,116,43,7,115,105,109,100,49,50,56,]);
  }

  /** @access private */
  _getWasmBytesNonSIMD()
  {
    return new Uint8Array([0,97,115,109,1,0,0,0,1,158,128,128,128,0,5,96,2,127,127,0,96,2,125,127,1,125,96,3,127,127,127,0,96,4,127,127,127,124,0,96,1,125,1,125,2,175,128,128,128,0,2,3,101,110,118,15,95,95,
      108,105,110,101,97,114,95,109,101,109,111,114,121,2,0,1,3,101,110,118,15,95,95,115,116,97,99,107,95,112,111,105,110,116,101,114,3,127,1,3,142,128,128,128,0,13,0,1,2,2,2,2,2,2,2,2,3,2,4,7,217,129,128,128,
      0,11,17,95,115,101,110,100,69,118,101,110,116,95,109,105,100,105,73,110,0,0,16,95,115,101,116,86,97,108,117,101,95,118,111,108,117,109,101,0,2,22,95,115,101,116,86,97,108,117,101,95,99,97,114,114,105,101,
      114,82,97,116,105,111,0,3,24,95,115,101,116,86,97,108,117,101,95,109,111,100,117,108,97,116,111,114,82,97,116,105,111,0,4,17,95,115,101,116,86,97,108,117,101,95,102,109,73,110,100,101,120,0,5,16,95,115,
      101,116,86,97,108,117,101,95,97,116,116,97,99,107,0,6,15,95,115,101,116,86,97,108,117,101,95,100,101,99,97,121,0,7,17,95,115,101,116,86,97,108,117,101,95,115,117,115,116,97,105,110,0,8,17,95,115,101,116,
      86,97,108,117,101,95,114,101,108,101,97,115,101,0,9,10,105,110,105,116,105,97,108,105,115,101,0,10,12,97,100,118,97,110,99,101,66,108,111,99,107,0,11,12,129,128,128,128,0,2,10,132,217,128,128,0,13,191,
      28,4,4,127,5,125,1,126,1,125,2,64,2,64,2,64,2,64,32,1,40,2,0,34,1,65,128,128,192,7,113,34,2,65,128,128,192,4,71,13,0,32,1,65,255,1,113,69,13,0,32,0,65,7,65,6,65,5,65,4,65,3,65,2,32,0,40,2,176,6,34,2,32,
      0,40,2,160,6,34,3,72,34,4,32,0,40,2,192,6,34,5,32,2,32,3,32,4,27,34,2,72,34,3,27,32,0,40,2,208,6,34,4,32,5,32,2,32,3,27,34,2,72,34,3,27,32,0,40,2,224,6,34,5,32,4,32,2,32,3,27,34,2,72,34,3,27,32,0,40,2,
      240,6,34,4,32,5,32,2,32,3,27,34,2,72,34,3,27,32,0,40,2,128,7,34,5,32,4,32,2,32,3,27,34,2,72,34,3,27,32,0,40,2,144,7,32,5,32,2,32,3,27,72,27,34,3,65,4,116,106,34,2,32,1,65,16,118,65,15,113,54,2,156,6,32,
      2,65,1,59,0,152,6,32,2,32,1,65,8,118,65,255,0,113,34,4,179,34,6,56,2,164,6,32,0,32,3,65,224,0,108,106,34,3,32,6,56,2,28,32,0,32,0,40,2,152,7,65,1,106,34,5,54,2,152,7,32,2,32,5,54,2,160,6,32,3,65,24,106,
      33,0,32,1,65,255,0,113,179,67,4,2,1,60,148,33,7,2,64,32,4,65,187,127,106,178,67,171,170,170,61,148,34,8,188,34,2,65,255,255,255,255,7,113,34,1,13,0,67,0,0,128,63,33,6,12,4,11,2,64,32,1,65,129,128,128,252,
      7,73,13,0,32,8,67,0,0,0,64,146,33,6,12,4,11,2,64,2,64,32,1,65,128,128,128,252,3,70,13,0,32,1,65,128,128,128,252,7,71,13,1,32,8,67,0,0,0,0,32,2,65,127,74,27,33,6,12,5,11,67,0,0,0,64,67,0,0,0,63,32,2,65,
      127,74,27,33,6,12,4,11,32,2,65,128,128,128,248,3,70,13,2,2,64,32,2,65,128,128,128,128,4,71,13,0,67,0,0,128,64,33,6,12,4,11,2,64,32,1,65,129,128,128,232,4,73,13,0,67,0,0,128,127,67,0,0,0,0,32,2,65,0,74,
      27,33,6,12,4,11,67,0,0,128,127,33,6,32,8,67,0,0,0,0,148,32,8,32,2,65,128,96,113,190,34,9,147,146,34,10,32,9,146,34,8,188,34,1,65,128,128,128,152,4,74,13,3,2,64,32,1,65,128,128,128,152,4,71,13,0,32,10,67,
      60,170,56,51,146,32,8,32,9,147,94,13,4,32,8,188,65,255,255,255,255,7,113,33,2,12,2,11,67,0,0,0,0,33,6,32,8,188,65,255,255,255,255,7,113,34,2,65,128,128,216,152,4,75,13,3,32,1,65,128,128,216,152,124,71,
      13,1,32,10,32,8,32,9,147,95,69,13,1,12,3,11,2,64,2,64,2,64,2,64,32,2,65,128,128,128,4,70,13,0,32,1,65,255,129,192,7,113,65,128,128,192,4,71,13,1,11,32,1,65,16,118,65,15,113,33,2,32,1,65,8,118,65,255,0,
      113,179,33,6,32,0,40,2,156,6,33,1,2,64,2,64,32,0,45,0,160,7,13,0,66,1,32,2,173,134,33,11,32,1,32,2,71,13,3,32,0,42,2,164,6,32,6,92,13,3,32,0,41,3,168,7,32,11,131,80,13,1,32,0,65,1,58,0,153,6,12,3,11,2,
      64,32,1,32,2,71,13,0,32,0,42,2,164,6,32,6,92,13,0,32,0,65,1,58,0,153,6,11,2,64,32,0,40,2,172,6,32,2,71,13,0,32,0,42,2,180,6,32,6,92,13,0,32,0,65,1,58,0,169,6,11,2,64,32,0,40,2,188,6,32,2,71,13,0,32,0,42,
      2,196,6,32,6,92,13,0,32,0,65,1,58,0,185,6,11,2,64,32,0,40,2,204,6,32,2,71,13,0,32,0,42,2,212,6,32,6,92,13,0,32,0,65,1,58,0,201,6,11,2,64,32,0,40,2,220,6,32,2,71,13,0,32,0,42,2,228,6,32,6,92,13,0,32,0,65,
      1,58,0,217,6,11,2,64,32,0,40,2,236,6,32,2,71,13,0,32,0,42,2,244,6,32,6,92,13,0,32,0,65,1,58,0,233,6,11,2,64,32,0,40,2,252,6,32,2,71,13,0,32,0,42,2,132,7,32,6,92,13,0,32,0,65,1,58,0,249,6,11,32,0,40,2,140,
      7,32,2,71,13,3,32,0,42,2,148,7,32,6,92,13,3,32,0,65,1,58,0,137,7,15,11,2,64,32,0,42,2,28,32,6,92,13,0,32,0,65,0,54,2,36,11,32,0,65,0,58,0,152,6,32,0,32,0,40,2,156,7,65,1,106,34,1,54,2,156,7,32,0,32,1,54,
      2,160,6,12,1,11,32,2,65,128,128,192,5,71,13,1,32,1,65,8,118,65,255,0,113,34,2,65,202,0,70,13,1,32,2,65,192,0,71,13,1,66,1,32,1,65,16,118,65,15,113,34,2,173,134,33,11,2,64,32,1,65,255,0,113,179,67,4,2,1,
      60,148,67,0,0,0,63,96,69,13,0,32,0,32,0,41,3,168,7,32,11,132,55,3,168,7,32,2,13,2,32,0,65,1,58,0,160,7,15,11,32,0,32,0,41,3,168,7,32,11,66,127,133,131,55,3,168,7,2,64,32,2,69,13,0,2,64,32,0,40,2,156,6,
      32,2,71,13,0,32,0,45,0,152,6,69,13,0,32,0,45,0,153,6,69,13,0,2,64,32,0,42,2,164,6,32,0,42,2,28,92,13,0,32,0,65,0,54,2,36,11,32,0,65,0,58,0,152,6,32,0,32,0,40,2,156,7,65,1,106,34,1,54,2,156,7,32,0,32,1,
      54,2,160,6,11,2,64,32,0,40,2,172,6,32,2,71,13,0,32,0,45,0,168,6,69,13,0,32,0,45,0,169,6,69,13,0,2,64,32,0,42,2,180,6,32,0,42,2,124,92,13,0,32,0,65,0,54,2,132,1,11,32,0,65,0,58,0,168,6,32,0,32,0,40,2,156,
      7,65,1,106,34,1,54,2,156,7,32,0,32,1,54,2,176,6,11,2,64,32,0,40,2,188,6,32,2,71,13,0,32,0,45,0,184,6,69,13,0,32,0,45,0,185,6,69,13,0,2,64,32,0,42,2,196,6,32,0,42,2,220,1,92,13,0,32,0,65,0,54,2,228,1,11,
      32,0,65,0,58,0,184,6,32,0,32,0,40,2,156,7,65,1,106,34,1,54,2,156,7,32,0,32,1,54,2,192,6,11,2,64,32,0,40,2,204,6,32,2,71,13,0,32,0,45,0,200,6,69,13,0,32,0,45,0,201,6,69,13,0,2,64,32,0,42,2,212,6,32,0,42,
      2,188,2,92,13,0,32,0,65,0,54,2,196,2,11,32,0,65,0,58,0,200,6,32,0,32,0,40,2,156,7,65,1,106,34,1,54,2,156,7,32,0,32,1,54,2,208,6,11,2,64,32,0,40,2,220,6,32,2,71,13,0,32,0,45,0,216,6,69,13,0,32,0,45,0,217,
      6,69,13,0,2,64,32,0,42,2,228,6,32,0,42,2,156,3,92,13,0,32,0,65,0,54,2,164,3,11,32,0,65,0,58,0,216,6,32,0,32,0,40,2,156,7,65,1,106,34,1,54,2,156,7,32,0,32,1,54,2,224,6,11,2,64,32,0,40,2,236,6,32,2,71,13,
      0,32,0,45,0,232,6,69,13,0,32,0,45,0,233,6,69,13,0,2,64,32,0,42,2,244,6,32,0,42,2,252,3,92,13,0,32,0,65,0,54,2,132,4,11,32,0,65,0,58,0,232,6,32,0,32,0,40,2,156,7,65,1,106,34,1,54,2,156,7,32,0,32,1,54,2,
      240,6,11,2,64,32,0,40,2,252,6,32,2,71,13,0,32,0,45,0,248,6,69,13,0,32,0,45,0,249,6,69,13,0,2,64,32,0,42,2,132,7,32,0,42,2,220,4,92,13,0,32,0,65,0,54,2,228,4,11,32,0,65,0,58,0,248,6,32,0,32,0,40,2,156,7,
      65,1,106,34,1,54,2,156,7,32,0,32,1,54,2,128,7,11,32,0,40,2,140,7,32,2,71,13,2,32,0,45,0,136,7,69,13,2,32,0,45,0,137,7,69,13,2,2,64,32,0,42,2,148,7,32,0,42,2,188,5,92,13,0,32,0,65,0,54,2,196,5,11,32,0,65,
      0,58,0,136,7,32,0,32,0,40,2,156,7,65,1,106,34,1,54,2,156,7,32,0,32,1,54,2,144,7,15,11,32,0,65,0,58,0,160,7,2,64,32,0,45,0,152,6,69,13,0,32,0,45,0,153,6,69,13,0,2,64,32,0,42,2,164,6,32,0,42,2,28,92,13,0,
      32,0,65,0,54,2,36,11,32,0,65,0,58,0,152,6,32,0,32,0,40,2,156,7,65,1,106,34,1,54,2,156,7,32,0,32,1,54,2,160,6,11,2,64,32,0,45,0,168,6,69,13,0,32,0,45,0,169,6,69,13,0,2,64,32,0,42,2,180,6,32,0,42,2,124,92,
      13,0,32,0,65,0,54,2,132,1,11,32,0,65,0,58,0,168,6,32,0,32,0,40,2,156,7,65,1,106,34,1,54,2,156,7,32,0,32,1,54,2,176,6,11,2,64,32,0,45,0,184,6,69,13,0,32,0,45,0,185,6,69,13,0,2,64,32,0,42,2,196,6,32,0,42,
      2,220,1,92,13,0,32,0,65,0,54,2,228,1,11,32,0,65,0,58,0,184,6,32,0,32,0,40,2,156,7,65,1,106,34,1,54,2,156,7,32,0,32,1,54,2,192,6,11,2,64,32,0,45,0,200,6,69,13,0,32,0,45,0,201,6,69,13,0,2,64,32,0,42,2,212,
      6,32,0,42,2,188,2,92,13,0,32,0,65,0,54,2,196,2,11,32,0,65,0,58,0,200,6,32,0,32,0,40,2,156,7,65,1,106,34,1,54,2,156,7,32,0,32,1,54,2,208,6,11,2,64,32,0,45,0,216,6,69,13,0,32,0,45,0,217,6,69,13,0,2,64,32,
      0,42,2,228,6,32,0,42,2,156,3,92,13,0,32,0,65,0,54,2,164,3,11,32,0,65,0,58,0,216,6,32,0,32,0,40,2,156,7,65,1,106,34,1,54,2,156,7,32,0,32,1,54,2,224,6,11,2,64,32,0,45,0,232,6,69,13,0,32,0,45,0,233,6,69,13,
      0,2,64,32,0,42,2,244,6,32,0,42,2,252,3,92,13,0,32,0,65,0,54,2,132,4,11,32,0,65,0,58,0,232,6,32,0,32,0,40,2,156,7,65,1,106,34,1,54,2,156,7,32,0,32,1,54,2,240,6,11,2,64,32,0,45,0,248,6,69,13,0,32,0,45,0,
      249,6,69,13,0,2,64,32,0,42,2,132,7,32,0,42,2,220,4,92,13,0,32,0,65,0,54,2,228,4,11,32,0,65,0,58,0,248,6,32,0,32,0,40,2,156,7,65,1,106,34,1,54,2,156,7,32,0,32,1,54,2,128,7,11,32,0,45,0,136,7,69,13,1,32,
      0,45,0,137,7,69,13,1,2,64,32,0,42,2,148,7,32,0,42,2,188,5,92,13,0,32,0,65,0,54,2,196,5,11,32,0,65,0,58,0,136,7,32,0,32,0,40,2,156,7,65,1,106,34,1,54,2,156,7,32,0,32,1,54,2,144,7,12,1,11,2,64,32,0,40,2,
      172,6,32,2,71,13,0,32,0,42,2,180,6,32,6,92,13,0,2,64,32,0,41,3,168,7,32,11,131,80,13,0,32,0,65,1,58,0,169,6,12,1,11,2,64,32,0,42,2,124,32,6,92,13,0,32,0,65,0,54,2,132,1,11,32,0,65,0,58,0,168,6,32,0,32,
      0,40,2,156,7,65,1,106,34,1,54,2,156,7,32,0,32,1,54,2,176,6,11,2,64,32,0,40,2,188,6,32,2,71,13,0,32,0,42,2,196,6,32,6,92,13,0,2,64,32,0,41,3,168,7,32,11,131,80,13,0,32,0,65,1,58,0,185,6,12,1,11,2,64,32,
      0,42,2,220,1,32,6,92,13,0,32,0,65,0,54,2,228,1,11,32,0,65,0,58,0,184,6,32,0,32,0,40,2,156,7,65,1,106,34,1,54,2,156,7,32,0,32,1,54,2,192,6,11,2,64,32,0,40,2,204,6,32,2,71,13,0,32,0,42,2,212,6,32,6,92,13,
      0,2,64,32,0,41,3,168,7,32,11,131,80,13,0,32,0,65,1,58,0,201,6,12,1,11,2,64,32,0,42,2,188,2,32,6,92,13,0,32,0,65,0,54,2,196,2,11,32,0,65,0,58,0,200,6,32,0,32,0,40,2,156,7,65,1,106,34,1,54,2,156,7,32,0,32,
      1,54,2,208,6,11,2,64,32,0,40,2,220,6,32,2,71,13,0,32,0,42,2,228,6,32,6,92,13,0,2,64,32,0,41,3,168,7,32,11,131,80,13,0,32,0,65,1,58,0,217,6,12,1,11,2,64,32,0,42,2,156,3,32,6,92,13,0,32,0,65,0,54,2,164,3,
      11,32,0,65,0,58,0,216,6,32,0,32,0,40,2,156,7,65,1,106,34,1,54,2,156,7,32,0,32,1,54,2,224,6,11,2,64,32,0,40,2,236,6,32,2,71,13,0,32,0,42,2,244,6,32,6,92,13,0,2,64,32,0,41,3,168,7,32,11,131,80,13,0,32,0,
      65,1,58,0,233,6,12,1,11,2,64,32,0,42,2,252,3,32,6,92,13,0,32,0,65,0,54,2,132,4,11,32,0,65,0,58,0,232,6,32,0,32,0,40,2,156,7,65,1,106,34,1,54,2,156,7,32,0,32,1,54,2,240,6,11,2,64,32,0,40,2,252,6,32,2,71,
      13,0,32,0,42,2,132,7,32,6,92,13,0,2,64,32,0,41,3,168,7,32,11,131,80,13,0,32,0,65,1,58,0,249,6,12,1,11,2,64,32,0,42,2,220,4,32,6,92,13,0,32,0,65,0,54,2,228,4,11,32,0,65,0,58,0,248,6,32,0,32,0,40,2,156,7,
      65,1,106,34,1,54,2,156,7,32,0,32,1,54,2,128,7,11,32,0,40,2,140,7,32,2,71,13,0,32,0,42,2,148,7,32,6,92,13,0,2,64,32,0,41,3,168,7,32,11,131,80,13,0,32,0,65,1,58,0,137,7,15,11,2,64,32,0,42,2,188,5,32,6,92,
      13,0,32,0,65,0,54,2,196,5,11,32,0,65,0,58,0,136,7,32,0,32,0,40,2,156,7,65,1,106,34,1,54,2,156,7,32,0,32,1,54,2,144,7,15,11,15,11,65,0,33,3,2,64,32,2,65,128,128,128,248,3,77,13,0,65,0,65,128,128,128,4,32,
      2,65,23,118,65,130,127,106,118,32,1,106,34,2,65,255,255,255,3,113,65,128,128,128,4,114,65,150,1,32,2,65,23,118,65,255,1,113,34,4,107,118,34,3,107,32,3,32,1,65,0,72,27,33,3,32,10,32,9,65,128,128,128,124,
      32,4,65,129,127,106,117,32,2,113,190,147,34,9,146,188,33,1,11,2,64,32,3,65,23,116,32,1,65,128,128,126,113,190,34,6,67,0,114,49,63,148,34,12,32,6,67,140,190,191,53,148,32,10,32,6,32,9,147,147,67,24,114,
      49,63,148,146,34,9,146,34,6,32,6,32,6,32,6,32,6,148,34,8,32,8,32,8,32,8,32,8,67,76,187,49,51,148,67,14,234,221,181,146,148,67,85,179,138,56,146,148,67,97,11,54,187,146,148,67,171,170,42,62,146,148,147,
      34,8,148,32,8,67,0,0,0,192,146,149,32,9,32,6,32,12,147,147,34,8,32,6,32,8,148,146,147,147,67,0,0,128,63,146,34,6,188,106,34,1,65,255,255,255,3,74,13,0,32,6,32,3,16,129,128,128,128,0,33,6,12,2,11,32,1,190,
      33,6,12,1,11,67,243,4,181,63,33,6,11,32,0,32,7,56,2,12,32,0,32,6,67,0,0,220,67,148,56,2,8,11,160,1,0,2,64,2,64,2,64,32,1,65,128,1,72,13,0,32,0,67,0,0,0,127,148,33,0,32,1,65,254,1,75,13,1,32,1,65,129,127,
      106,33,1,12,2,11,32,1,65,130,127,78,13,1,32,0,67,0,0,128,12,148,33,0,2,64,32,1,65,155,126,77,13,0,32,1,65,230,0,106,33,1,12,2,11,32,0,67,0,0,128,12,148,33,0,32,1,65,182,125,32,1,65,182,125,75,27,65,204,
      1,106,33,1,12,1,11,32,0,67,0,0,0,127,148,33,0,32,1,65,253,2,32,1,65,253,2,73,27,65,130,126,106,33,1,11,32,0,32,1,65,23,116,65,128,128,128,252,3,106,190,148,11,72,1,1,125,2,64,32,0,40,2,216,7,13,0,32,0,
      32,0,40,2,0,65,1,106,54,2,0,11,32,1,42,2,0,33,3,32,0,32,2,65,1,32,2,65,1,75,27,34,2,54,2,216,7,32,0,32,3,32,0,42,2,208,7,147,32,2,178,149,56,2,212,7,11,72,1,1,125,2,64,32,0,40,2,228,7,13,0,32,0,32,0,40,
      2,0,65,1,106,54,2,0,11,32,1,42,2,0,33,3,32,0,32,2,65,1,32,2,65,1,75,27,34,2,54,2,228,7,32,0,32,3,32,0,42,2,220,7,147,32,2,178,149,56,2,224,7,11,72,1,1,125,2,64,32,0,40,2,240,7,13,0,32,0,32,0,40,2,0,65,
      1,106,54,2,0,11,32,1,42,2,0,33,3,32,0,32,2,65,1,32,2,65,1,75,27,34,2,54,2,240,7,32,0,32,3,32,0,42,2,232,7,147,32,2,178,149,56,2,236,7,11,72,1,1,125,2,64,32,0,40,2,252,7,13,0,32,0,32,0,40,2,0,65,1,106,54,
      2,0,11,32,1,42,2,0,33,3,32,0,32,2,65,1,32,2,65,1,75,27,34,2,54,2,252,7,32,0,32,3,32,0,42,2,244,7,147,32,2,178,149,56,2,248,7,11,72,1,1,125,2,64,32,0,40,2,136,8,13,0,32,0,32,0,40,2,0,65,1,106,54,2,0,11,
      32,1,42,2,0,33,3,32,0,32,2,65,1,32,2,65,1,75,27,34,2,54,2,136,8,32,0,32,3,32,0,42,2,128,8,147,32,2,178,149,56,2,132,8,11,72,1,1,125,2,64,32,0,40,2,148,8,13,0,32,0,32,0,40,2,0,65,1,106,54,2,0,11,32,1,42,
      2,0,33,3,32,0,32,2,65,1,32,2,65,1,75,27,34,2,54,2,148,8,32,0,32,3,32,0,42,2,140,8,147,32,2,178,149,56,2,144,8,11,72,1,1,125,2,64,32,0,40,2,160,8,13,0,32,0,32,0,40,2,0,65,1,106,54,2,0,11,32,1,42,2,0,33,
      3,32,0,32,2,65,1,32,2,65,1,75,27,34,2,54,2,160,8,32,0,32,3,32,0,42,2,152,8,147,32,2,178,149,56,2,156,8,11,72,1,1,125,2,64,32,0,40,2,172,8,13,0,32,0,32,0,40,2,0,65,1,106,54,2,0,11,32,1,42,2,0,33,3,32,0,
      32,2,65,1,32,2,65,1,75,27,34,2,54,2,172,8,32,0,32,3,32,0,42,2,164,8,147,32,2,178,149,56,2,168,8,11,182,1,0,32,0,66,128,128,240,158,4,55,2,192,5,32,0,65,7,54,2,184,5,32,0,66,128,128,240,158,4,55,2,224,4,
      32,0,65,6,54,2,216,4,32,0,66,128,128,240,158,4,55,2,128,4,32,0,65,5,54,2,248,3,32,0,66,128,128,240,158,4,55,2,160,3,32,0,65,4,54,2,152,3,32,0,66,128,128,240,158,4,55,2,192,2,32,0,65,3,54,2,184,2,32,0,66,
      128,128,240,158,4,55,2,224,1,32,0,65,2,54,2,216,1,32,0,66,128,128,240,158,4,55,2,128,1,32,0,65,1,54,2,120,32,0,66,128,128,240,158,4,55,2,32,32,0,65,0,54,2,24,65,0,32,3,57,3,128,128,128,128,0,32,0,66,128,
      128,128,128,23,55,2,152,7,11,196,17,3,5,127,8,125,4,127,35,128,128,128,128,0,65,32,107,34,3,36,128,128,128,128,0,2,64,32,0,40,2,4,32,2,70,13,0,32,0,65,24,106,33,4,32,3,65,16,106,33,5,32,3,65,8,106,33,6,
      3,64,2,64,2,64,32,0,40,2,0,34,7,13,0,32,0,42,2,204,7,33,8,32,0,42,2,200,7,33,9,32,0,42,2,196,7,33,10,32,0,42,2,192,7,33,11,32,0,42,2,188,7,33,12,32,0,42,2,184,7,33,13,32,0,42,2,180,7,33,14,32,0,42,2,176,
      7,33,15,12,1,11,2,64,32,0,40,2,216,7,34,16,69,13,0,32,0,32,16,65,127,106,34,16,54,2,216,7,32,0,32,0,42,2,212,7,32,0,42,2,208,7,146,56,2,208,7,32,16,13,0,32,0,32,7,65,127,106,34,7,54,2,0,11,2,64,32,0,40,
      2,228,7,34,16,69,13,0,32,0,32,16,65,127,106,34,16,54,2,228,7,32,0,32,0,42,2,224,7,32,0,42,2,220,7,146,56,2,220,7,32,16,13,0,32,0,32,7,65,127,106,34,7,54,2,0,11,2,64,32,0,40,2,240,7,34,16,69,13,0,32,0,32,
      16,65,127,106,34,16,54,2,240,7,32,0,32,0,42,2,236,7,32,0,42,2,232,7,146,56,2,232,7,32,16,13,0,32,0,32,7,65,127,106,34,7,54,2,0,11,2,64,32,0,40,2,252,7,34,16,69,13,0,32,0,32,16,65,127,106,34,16,54,2,252,
      7,32,0,32,0,42,2,248,7,32,0,42,2,244,7,146,56,2,244,7,32,16,13,0,32,0,32,7,65,127,106,34,7,54,2,0,11,2,64,32,0,40,2,136,8,34,16,69,13,0,32,0,32,16,65,127,106,34,16,54,2,136,8,32,0,32,0,42,2,132,8,32,0,
      42,2,128,8,146,56,2,128,8,32,16,13,0,32,0,32,7,65,127,106,34,7,54,2,0,11,2,64,32,0,40,2,148,8,34,16,69,13,0,32,0,32,16,65,127,106,34,16,54,2,148,8,32,0,32,0,42,2,144,8,32,0,42,2,140,8,146,56,2,140,8,32,
      16,13,0,32,0,32,7,65,127,106,34,7,54,2,0,11,2,64,32,0,40,2,160,8,34,16,69,13,0,32,0,32,16,65,127,106,34,16,54,2,160,8,32,0,32,0,42,2,156,8,32,0,42,2,152,8,146,56,2,152,8,32,16,13,0,32,0,32,7,65,127,106,
      34,7,54,2,0,11,32,0,42,2,164,8,33,8,2,64,32,0,40,2,172,8,34,16,69,13,0,32,0,32,16,65,127,106,34,16,54,2,172,8,32,0,32,0,42,2,168,8,32,8,146,34,8,56,2,164,8,32,16,13,0,32,0,32,7,65,127,106,54,2,0,11,32,
      0,32,8,56,2,204,7,32,0,32,0,42,2,208,7,34,15,56,2,176,7,32,0,32,0,42,2,220,7,34,14,56,2,180,7,32,0,32,0,42,2,232,7,34,13,56,2,184,7,32,0,32,0,42,2,244,7,34,12,56,2,188,7,32,0,32,0,42,2,128,8,34,11,56,2,
      192,7,32,0,32,0,42,2,140,8,34,10,56,2,196,7,32,0,32,0,42,2,152,8,34,9,56,2,200,7,11,32,0,32,15,56,2,248,5,32,0,32,15,56,2,152,5,32,0,32,15,56,2,184,4,32,0,32,15,56,2,216,3,32,0,32,15,56,2,248,2,32,0,32,
      15,56,2,152,2,32,0,32,15,56,2,184,1,32,0,32,15,56,2,88,32,0,32,14,56,2,252,5,32,0,32,14,56,2,156,5,32,0,32,14,56,2,188,4,32,0,32,14,56,2,220,3,32,0,32,14,56,2,252,2,32,0,32,14,56,2,156,2,32,0,32,14,56,
      2,188,1,32,0,32,14,56,2,92,32,3,65,24,106,66,0,55,3,0,32,5,66,0,55,3,0,32,6,66,0,55,3,0,32,3,66,0,55,3,0,32,0,32,13,56,2,128,6,32,0,32,13,56,2,160,5,32,0,32,13,56,2,192,4,32,0,32,13,56,2,224,3,32,0,32,
      13,56,2,128,3,32,0,32,13,56,2,160,2,32,0,32,13,56,2,192,1,32,0,32,13,56,2,96,32,0,32,12,56,2,100,32,0,32,12,56,2,196,1,32,0,32,12,56,2,164,2,32,0,32,12,56,2,132,3,32,0,32,12,56,2,228,3,32,0,32,12,56,2,
      196,4,32,0,32,12,56,2,164,5,32,0,32,12,56,2,132,6,32,0,32,11,56,2,104,32,0,32,11,56,2,200,1,32,0,32,11,56,2,168,2,32,0,32,11,56,2,136,3,32,0,32,11,56,2,232,3,32,0,32,11,56,2,200,4,32,0,32,11,56,2,168,5,
      32,0,32,11,56,2,136,6,32,0,32,10,56,2,140,6,32,0,32,10,56,2,172,5,32,0,32,10,56,2,204,4,32,0,32,10,56,2,236,3,32,0,32,10,56,2,140,3,32,0,32,10,56,2,172,2,32,0,32,10,56,2,204,1,32,0,32,10,56,2,108,32,0,
      32,9,56,2,144,6,32,0,32,9,56,2,176,5,32,0,32,9,56,2,208,4,32,0,32,9,56,2,240,3,32,0,32,9,56,2,144,3,32,0,32,9,56,2,176,2,32,0,32,9,56,2,208,1,32,0,32,9,56,2,112,32,0,32,8,56,2,148,6,32,0,32,8,56,2,180,
      5,32,0,32,8,56,2,212,4,32,0,32,8,56,2,244,3,32,0,32,8,56,2,148,3,32,0,32,8,56,2,180,2,32,0,32,8,56,2,212,1,32,0,32,8,56,2,116,65,0,33,16,65,0,43,3,128,128,128,128,0,182,33,12,3,64,67,0,0,0,0,33,11,65,0,
      33,17,67,0,0,0,0,33,9,2,64,32,4,32,16,65,224,0,108,106,34,7,40,2,16,65,127,70,13,0,32,7,65,1,54,2,16,32,7,42,2,12,67,0,0,0,0,94,33,17,32,7,42,2,8,67,0,0,0,0,146,33,9,11,2,64,32,7,40,2,24,65,127,70,13,0,
      32,7,42,2,20,34,8,67,0,0,0,0,146,67,219,15,201,64,148,16,140,128,128,128,0,33,10,2,64,32,8,32,9,32,7,42,2,72,148,67,0,0,0,0,146,32,12,149,146,34,8,67,0,0,128,63,96,69,13,0,3,64,32,8,67,0,0,128,191,146,
      34,8,67,0,0,128,63,96,13,0,11,11,32,7,32,8,56,2,20,2,64,32,8,67,0,0,0,0,93,69,13,0,3,64,32,8,67,0,0,128,63,146,34,8,67,0,0,0,0,93,13,0,11,32,7,32,8,56,2,20,11,32,7,65,1,54,2,24,32,10,67,0,0,0,0,146,33,
      11,11,67,0,0,0,0,33,10,67,0,0,0,0,33,8,2,64,32,7,40,2,32,65,127,70,13,0,32,11,32,7,42,2,76,148,67,0,0,0,0,146,32,7,42,2,28,34,8,146,67,219,15,201,64,148,16,140,128,128,128,0,33,11,2,64,32,8,32,9,32,7,42,
      2,68,148,67,0,0,0,0,146,32,12,149,146,34,8,67,0,0,128,63,96,69,13,0,3,64,32,8,67,0,0,128,191,146,34,8,67,0,0,128,63,96,13,0,11,11,32,7,32,8,56,2,28,2,64,32,8,67,0,0,0,0,93,69,13,0,3,64,32,8,67,0,0,128,
      63,146,34,8,67,0,0,0,0,93,13,0,11,32,7,32,8,56,2,28,11,32,7,65,1,54,2,32,32,11,67,0,0,0,0,146,33,8,11,32,3,32,16,65,2,116,106,33,18,32,7,32,7,42,2,80,34,13,56,2,44,32,7,32,7,42,2,84,34,14,56,2,48,32,7,
      32,7,42,2,88,34,11,56,2,52,32,7,32,7,42,2,92,34,9,56,2,56,2,64,32,7,40,2,60,65,127,70,13,0,32,7,40,2,40,33,19,2,64,2,64,2,64,2,64,2,64,2,64,2,64,2,64,2,64,32,17,69,13,0,32,19,14,5,1,2,3,4,1,7,11,32,19,
      65,123,113,13,4,32,19,65,127,106,14,4,1,2,3,5,6,11,32,7,65,1,54,2,40,11,32,7,67,0,0,128,63,67,0,0,128,63,32,13,32,12,148,34,9,149,32,9,67,0,0,128,63,93,27,32,7,42,2,36,146,34,9,56,2,36,32,9,67,0,0,128,
      63,96,69,13,5,32,7,66,128,128,128,252,35,55,2,36,67,0,0,128,63,33,9,12,5,11,32,7,32,7,42,2,36,67,0,0,128,63,67,0,0,128,63,32,11,147,32,14,32,12,148,34,9,149,32,9,67,0,0,128,63,93,27,147,34,9,56,2,36,32,
      9,32,11,95,69,13,4,32,7,65,3,54,2,40,11,32,7,32,11,56,2,36,32,11,33,9,12,3,11,32,7,65,4,54,2,40,11,32,7,32,7,42,2,36,34,10,32,10,32,10,32,9,32,12,148,34,9,149,32,9,67,0,0,128,63,93,27,147,34,9,56,2,36,
      32,9,67,0,0,0,0,95,69,13,1,32,7,66,0,55,2,36,67,0,0,0,0,33,9,12,1,11,32,7,42,2,36,33,9,11,32,7,65,1,54,2,60,32,9,67,0,0,0,0,146,33,10,11,32,18,32,18,42,2,0,32,8,32,10,148,32,7,42,2,64,148,146,56,2,0,32,
      16,65,1,106,34,16,65,8,71,13,0,11,32,1,32,0,40,2,4,65,2,116,106,32,3,42,2,28,32,3,42,2,24,32,3,42,2,20,32,3,42,2,16,32,3,42,2,12,32,3,42,2,8,32,3,42,2,4,32,3,42,2,0,67,0,0,0,0,146,146,146,146,146,146,146,
      146,56,2,0,32,0,32,0,40,2,4,65,1,106,34,7,54,2,4,32,7,32,2,71,13,0,11,11,32,0,65,0,54,2,4,32,3,65,32,106,36,128,128,128,128,0,11,216,35,6,3,127,3,124,8,127,1,124,71,127,2,126,35,128,128,128,128,0,65,128,
      3,107,34,1,36,128,128,128,128,0,2,64,2,64,32,0,188,34,2,65,255,255,255,255,7,113,34,3,65,218,159,164,250,3,75,13,0,32,0,32,0,187,34,4,32,4,162,34,5,32,4,162,34,6,32,5,32,5,162,162,32,5,68,167,70,59,140,
      135,205,198,62,162,68,116,231,202,226,249,0,42,191,160,162,32,6,32,5,68,178,251,110,137,16,17,129,63,162,68,119,172,203,84,85,85,197,191,160,162,32,4,160,160,182,32,3,65,128,128,128,204,3,73,27,33,0,12,
      1,11,2,64,2,64,2,64,2,64,32,3,65,210,167,237,131,4,73,13,0,32,3,65,214,227,136,135,4,79,13,2,32,0,187,33,5,32,3,65,224,219,191,133,4,79,13,1,68,0,0,0,0,0,0,240,63,32,5,68,210,33,51,127,124,217,18,64,160,
      34,4,32,4,162,34,4,68,129,94,12,253,255,255,223,63,162,161,32,4,32,4,162,34,6,68,66,58,5,225,83,85,165,63,162,160,32,4,32,6,162,32,4,68,105,80,238,224,66,147,249,62,162,68,39,30,15,232,135,192,86,191,160,
      162,160,182,68,0,0,0,0,0,0,240,63,32,5,68,210,33,51,127,124,217,18,192,160,34,5,32,5,162,34,5,68,129,94,12,253,255,255,223,63,162,161,32,5,32,5,162,34,4,68,66,58,5,225,83,85,165,63,162,160,32,5,32,4,162,
      32,5,68,105,80,238,224,66,147,249,62,162,68,39,30,15,232,135,192,86,191,160,162,160,182,140,32,2,65,0,72,27,33,0,12,4,11,32,0,187,33,5,32,3,65,228,151,219,128,4,73,13,2,68,24,45,68,84,251,33,9,64,68,24,
      45,68,84,251,33,9,192,32,2,65,0,72,27,32,5,160,34,4,32,4,162,34,5,32,4,154,162,34,6,32,5,32,5,162,162,32,5,68,167,70,59,140,135,205,198,62,162,68,116,231,202,226,249,0,42,191,160,162,32,6,32,5,68,178,251,
      110,137,16,17,129,63,162,68,119,172,203,84,85,85,197,191,160,162,32,4,161,160,182,33,0,12,3,11,68,24,45,68,84,251,33,25,64,68,24,45,68,84,251,33,25,192,32,2,65,0,72,27,32,5,160,34,4,32,4,32,4,162,34,5,
      162,34,6,32,5,32,5,162,162,32,5,68,167,70,59,140,135,205,198,62,162,68,116,231,202,226,249,0,42,191,160,162,32,4,32,6,32,5,68,178,251,110,137,16,17,129,63,162,68,119,172,203,84,85,85,197,191,160,162,160,
      160,182,33,0,12,2,11,2,64,32,3,65,255,255,255,251,7,75,13,0,2,64,2,64,32,3,65,218,159,164,238,4,75,13,0,32,0,187,34,5,32,5,68,131,200,201,109,48,95,228,63,162,68,0,0,0,0,0,0,56,67,160,68,0,0,0,0,0,0,56,
      195,160,34,4,68,0,0,0,80,251,33,249,191,162,160,32,4,68,99,98,26,97,180,16,81,190,162,160,33,5,32,4,252,2,33,7,12,1,11,32,1,66,128,128,128,128,208,227,252,180,53,55,3,248,2,32,1,66,128,128,128,128,168,
      196,224,241,54,55,3,240,2,32,1,66,128,128,128,128,132,164,137,189,56,55,3,232,2,32,1,66,128,128,128,128,184,240,134,248,57,55,3,224,2,32,1,66,128,128,128,128,150,138,179,188,59,55,3,216,2,32,1,66,128,128,
      128,128,136,211,145,252,60,55,3,208,2,32,1,66,128,128,128,128,208,133,145,186,62,55,3,200,2,32,1,66,128,128,128,128,180,191,200,252,63,55,3,192,2,2,64,65,128,1,69,13,0,32,1,65,192,1,106,65,0,65,128,1,252,
      11,0,11,2,64,65,224,0,69,13,0,32,1,65,192,0,106,65,32,106,65,0,65,224,0,252,11,0,11,32,1,65,8,106,66,0,55,3,0,32,1,65,16,106,66,0,55,3,0,32,1,65,24,106,66,0,55,3,0,32,1,65,32,106,66,0,55,3,0,32,1,65,40,
      106,66,0,55,3,0,32,1,65,48,106,66,0,55,3,0,32,1,65,56,106,66,0,55,3,0,32,1,66,0,55,3,0,32,1,32,3,32,3,65,23,118,34,8,65,234,126,106,34,9,65,23,116,107,190,187,34,6,32,8,65,231,126,106,65,255,1,113,65,24,
      110,34,10,65,2,116,34,3,65,156,128,128,128,0,106,40,2,0,183,162,68,0,0,0,0,0,0,0,0,160,57,3,88,32,1,32,6,32,3,65,152,128,128,128,0,106,40,2,0,183,162,68,0,0,0,0,0,0,0,0,160,57,3,80,32,1,32,6,32,3,65,148,
      128,128,128,0,106,40,2,0,183,162,68,0,0,0,0,0,0,0,0,160,57,3,72,32,1,32,6,32,3,65,144,128,128,128,0,106,40,2,0,183,162,68,0,0,0,0,0,0,0,0,160,57,3,64,65,47,32,10,65,104,108,32,9,106,34,11,107,33,12,65,
      48,32,11,107,33,13,32,11,65,104,106,33,14,32,11,65,231,7,106,173,66,52,134,191,33,15,32,1,65,100,106,33,16,32,11,65,25,72,33,17,32,11,65,103,106,33,18,65,3,33,19,3,64,32,1,65,192,0,106,32,19,34,20,65,15,
      113,34,21,65,3,116,106,43,3,0,33,5,2,64,32,20,65,1,72,34,9,13,0,32,20,65,127,106,33,3,65,0,33,8,3,64,32,1,32,8,65,15,113,65,2,116,106,32,5,32,5,68,0,0,0,0,0,0,112,62,162,252,2,183,34,4,68,0,0,0,0,0,0,112,
      193,162,160,252,2,54,2,0,32,1,65,192,0,106,32,3,65,15,113,65,3,116,106,43,3,0,32,4,160,33,5,32,8,65,1,106,33,8,32,3,65,127,106,34,3,65,127,71,13,0,11,11,32,5,32,15,162,34,5,32,5,68,0,0,0,0,0,0,192,63,162,
      156,68,0,0,0,0,0,0,32,192,162,160,34,5,32,5,252,2,34,7,183,161,33,5,2,64,2,64,2,64,2,64,32,17,13,0,32,1,32,20,65,127,106,65,15,113,65,2,116,106,34,3,32,3,40,2,0,34,3,32,3,32,13,117,34,3,32,13,116,107,34,
      8,54,2,0,32,8,32,12,117,33,22,32,3,32,7,106,33,7,12,1,11,2,64,32,14,13,0,32,1,32,20,65,127,106,65,15,113,65,2,116,106,40,2,0,65,23,117,33,22,12,1,11,65,2,33,22,65,0,33,23,32,5,68,0,0,0,0,0,0,224,63,102,
      69,13,2,12,1,11,32,22,65,0,74,13,0,32,22,33,23,12,1,11,2,64,2,64,32,9,69,13,0,65,0,33,9,12,1,11,65,0,33,3,65,0,33,9,3,64,32,1,32,3,65,15,113,65,2,116,106,34,19,40,2,0,33,8,2,64,2,64,2,64,2,64,32,9,65,1,
      113,69,13,0,65,255,255,255,7,33,9,12,1,11,32,8,69,13,1,65,128,128,128,8,33,9,11,32,19,32,9,32,8,107,54,2,0,65,1,33,9,12,1,11,65,0,33,9,11,32,20,32,3,65,1,106,34,3,71,13,0,11,11,2,64,32,17,13,0,65,255,255,
      255,3,33,3,2,64,2,64,32,18,14,2,1,0,2,11,65,255,255,255,1,33,3,11,32,1,32,20,65,127,106,65,15,113,65,2,116,106,34,8,32,8,40,2,0,32,3,113,54,2,0,11,32,7,65,1,106,33,7,65,2,33,23,32,22,65,2,71,13,0,68,0,
      0,0,0,0,0,240,63,32,5,161,34,5,32,15,161,32,5,32,9,27,33,5,11,2,64,2,64,2,64,32,5,68,0,0,0,0,0,0,0,0,98,13,0,32,20,65,127,106,34,3,65,2,76,13,2,65,0,33,8,2,64,2,64,32,20,65,125,106,34,24,65,7,77,13,0,32,
      20,65,127,106,65,15,113,65,3,73,13,0,32,20,65,108,106,65,112,73,13,0,65,0,33,22,65,0,33,25,65,0,33,8,2,64,32,24,65,32,73,13,0,32,1,32,3,65,15,113,65,2,116,106,34,9,40,2,0,33,26,32,9,65,132,127,106,34,8,
      40,2,0,33,27,32,8,40,2,4,33,28,32,8,40,2,8,33,29,32,8,40,2,12,33,30,32,8,40,2,16,33,31,32,8,40,2,20,33,32,32,8,40,2,24,33,33,32,8,40,2,28,33,34,32,9,65,164,127,106,34,8,40,2,0,33,35,32,8,40,2,4,33,36,32,
      8,40,2,8,33,37,32,8,40,2,12,33,38,32,8,40,2,16,33,39,32,8,40,2,20,33,40,32,8,40,2,24,33,41,32,8,40,2,28,33,42,32,9,65,68,106,34,8,40,2,0,33,43,32,8,40,2,4,33,44,32,8,40,2,8,33,45,32,8,40,2,12,33,46,32,
      8,40,2,16,33,47,32,8,40,2,20,33,48,32,8,40,2,24,33,49,32,8,40,2,28,33,50,32,9,65,100,106,34,8,40,2,0,33,51,32,8,40,2,4,33,52,32,8,40,2,8,33,53,32,8,40,2,12,33,54,32,8,40,2,16,33,55,32,8,40,2,20,33,56,32,
      8,40,2,24,33,57,65,0,33,8,32,24,65,96,113,34,25,33,58,65,0,33,9,65,0,33,19,65,0,33,21,65,0,33,59,65,0,33,60,65,0,33,61,65,0,33,62,65,0,33,63,65,0,33,64,65,0,33,65,65,0,33,66,65,0,33,67,65,0,33,68,65,0,
      33,69,65,0,33,70,65,0,33,71,65,0,33,72,65,0,33,73,65,0,33,74,65,0,33,75,65,0,33,76,65,0,33,77,65,0,33,78,65,0,33,79,65,0,33,80,65,0,33,81,65,0,33,82,65,0,33,83,65,0,33,84,65,0,33,85,65,0,33,86,3,64,32,
      34,32,79,114,33,79,32,42,32,71,114,33,71,32,50,32,63,114,33,63,32,26,32,8,114,33,8,32,33,32,80,114,33,80,32,41,32,72,114,33,72,32,49,32,64,114,33,64,32,57,32,9,114,33,9,32,32,32,81,114,33,81,32,40,32,73,
      114,33,73,32,48,32,65,114,33,65,32,56,32,19,114,33,19,32,31,32,82,114,33,82,32,39,32,74,114,33,74,32,47,32,66,114,33,66,32,55,32,21,114,33,21,32,30,32,83,114,33,83,32,38,32,75,114,33,75,32,46,32,67,114,
      33,67,32,54,32,59,114,33,59,32,29,32,84,114,33,84,32,37,32,76,114,33,76,32,45,32,68,114,33,68,32,53,32,60,114,33,60,32,28,32,85,114,33,85,32,36,32,77,114,33,77,32,44,32,69,114,33,69,32,52,32,61,114,33,
      61,32,27,32,86,114,33,86,32,35,32,78,114,33,78,32,43,32,70,114,33,70,32,51,32,62,114,33,62,32,58,65,96,106,34,58,13,0,11,32,79,32,71,32,63,32,8,114,114,114,32,83,32,75,32,67,32,59,114,114,114,114,32,81,
      32,73,32,65,32,19,114,114,114,32,85,32,77,32,69,32,61,114,114,114,114,114,32,80,32,72,32,64,32,9,114,114,114,32,84,32,76,32,68,32,60,114,114,114,114,32,82,32,74,32,66,32,21,114,114,114,32,86,32,78,32,70,
      32,62,114,114,114,114,114,114,33,8,32,24,32,25,70,13,2,32,24,65,24,113,13,0,32,3,32,25,107,33,3,12,1,11,32,25,65,127,115,32,20,106,33,19,32,25,32,24,65,120,113,34,65,107,33,64,32,3,32,65,107,33,3,65,0,
      33,21,65,0,33,59,65,0,33,60,65,0,33,61,65,0,33,62,65,0,33,63,3,64,32,16,32,19,65,15,113,65,2,116,106,34,9,40,2,12,32,60,114,33,60,32,9,40,2,16,32,59,114,33,59,32,9,40,2,20,32,21,114,33,21,32,9,40,2,24,
      32,22,114,33,22,32,9,40,2,28,32,8,114,33,8,32,9,40,2,8,32,61,114,33,61,32,9,40,2,4,32,62,114,33,62,32,9,40,2,0,32,63,114,33,63,32,19,65,120,106,33,19,32,64,65,8,106,34,64,13,0,11,32,8,32,60,114,32,21,32,
      62,114,114,32,22,32,61,114,32,59,32,63,114,114,114,33,8,32,24,32,65,70,13,1,11,3,64,32,1,32,3,65,15,113,65,2,116,106,40,2,0,32,8,114,33,8,32,3,65,3,75,33,9,32,3,65,127,106,33,3,32,9,13,0,11,11,32,8,69,
      13,2,3,64,32,14,65,104,106,33,14,32,1,32,20,65,127,106,34,20,65,15,113,65,2,116,106,40,2,0,69,13,0,12,2,11,11,2,64,2,64,32,5,65,151,8,32,11,107,173,66,52,134,191,162,34,5,68,0,0,0,0,0,0,112,65,102,69,13,
      0,32,1,32,21,65,2,116,106,32,5,32,5,68,0,0,0,0,0,0,112,62,162,252,2,34,3,183,68,0,0,0,0,0,0,112,193,162,160,252,2,54,2,0,32,20,65,1,106,34,20,65,15,113,33,21,32,11,33,14,12,1,11,32,5,252,2,33,3,11,32,1,
      32,21,65,2,116,106,32,3,54,2,0,11,2,64,2,64,2,64,2,64,32,14,65,128,8,72,13,0,32,14,65,254,15,75,13,1,32,14,65,129,120,106,33,14,68,0,0,0,0,0,0,224,127,33,5,12,3,11,32,14,65,130,120,72,13,1,68,0,0,0,0,0,
      0,240,63,33,5,12,2,11,32,14,65,253,23,32,14,65,253,23,73,27,65,130,112,106,33,14,68,0,0,0,0,0,0,240,127,33,5,12,1,11,2,64,32,14,65,184,112,77,13,0,32,14,65,201,7,106,33,14,68,0,0,0,0,0,0,96,3,33,5,12,1,
      11,32,14,65,240,104,32,14,65,240,104,75,27,65,146,15,106,33,14,68,0,0,0,0,0,0,0,0,33,5,11,2,64,2,64,32,20,65,0,78,13,0,68,0,0,0,0,0,0,0,0,33,5,12,1,11,32,5,32,14,65,255,7,106,173,66,52,134,191,162,33,5,
      32,20,33,3,3,64,32,1,65,192,0,106,32,3,65,15,113,34,8,65,3,116,106,32,5,32,1,32,8,65,2,116,106,40,2,0,183,162,57,3,0,32,5,68,0,0,0,0,0,0,112,62,162,33,5,32,3,65,127,106,34,3,65,127,71,13,0,11,65,0,33,22,
      32,20,33,9,3,64,32,22,65,3,32,22,65,3,73,27,65,1,106,33,19,68,0,0,0,0,0,0,0,0,33,5,32,1,65,192,2,106,33,3,65,0,33,8,3,64,32,5,32,1,65,192,0,106,32,9,32,8,106,65,15,113,65,3,116,106,43,3,0,32,3,43,3,0,162,
      160,33,5,32,3,65,8,106,33,3,32,19,32,8,65,1,106,34,8,71,13,0,11,32,1,65,192,1,106,32,20,32,9,107,65,15,113,65,3,116,106,32,5,57,3,0,32,9,65,127,106,33,9,32,22,32,20,71,33,3,32,22,65,1,106,33,22,32,3,13,
      0,11,68,0,0,0,0,0,0,0,0,33,5,3,64,32,5,32,1,65,192,1,106,32,20,65,15,113,65,3,116,106,43,3,0,160,33,5,32,20,65,127,106,34,20,65,127,71,13,0,11,11,32,5,154,32,5,32,23,27,33,5,32,2,65,127,74,13,2,65,0,32,
      7,107,33,7,32,5,154,33,5,12,2,11,65,0,33,3,3,64,32,3,34,8,65,127,106,33,3,32,1,32,8,65,2,106,65,15,113,65,2,116,106,40,2,0,69,13,0,11,32,20,65,1,106,34,9,32,20,32,3,107,34,19,74,13,0,2,64,32,20,65,127,
      115,34,22,32,19,172,66,1,124,34,87,32,20,65,2,106,34,3,172,34,88,32,87,32,88,85,27,34,87,167,106,34,61,65,12,73,13,0,32,3,32,87,32,88,125,34,87,167,34,21,106,32,3,72,13,0,65,14,32,20,107,65,15,113,32,21,
      65,15,113,73,13,0,32,87,66,15,86,13,0,32,22,32,9,32,8,107,172,66,1,124,34,87,32,88,32,87,32,88,85,27,167,106,65,124,113,33,59,32,10,32,20,106,33,60,32,9,32,61,65,124,113,34,62,106,33,9,65,0,33,3,3,64,32,
      1,65,192,0,106,32,20,32,3,106,65,1,106,65,15,113,65,3,116,106,34,8,32,6,32,60,32,3,106,34,22,65,4,106,65,194,0,111,34,21,65,194,0,106,32,21,32,21,65,0,72,27,65,2,116,65,144,128,128,128,0,106,40,2,0,183,
      162,68,0,0,0,0,0,0,0,0,160,57,3,24,32,8,32,6,32,22,65,3,106,65,194,0,111,34,21,65,194,0,106,32,21,32,21,65,0,72,27,65,2,116,65,144,128,128,128,0,106,40,2,0,183,162,68,0,0,0,0,0,0,0,0,160,57,3,16,32,8,32,
      6,32,22,65,2,106,65,194,0,111,34,21,65,194,0,106,32,21,32,21,65,0,72,27,65,2,116,65,144,128,128,128,0,106,40,2,0,183,162,68,0,0,0,0,0,0,0,0,160,57,3,8,32,8,32,6,32,22,65,1,106,65,194,0,111,34,22,65,194,
      0,106,32,22,32,22,65,0,72,27,65,2,116,65,144,128,128,128,0,106,40,2,0,183,162,68,0,0,0,0,0,0,0,0,160,57,3,0,32,59,32,3,65,4,106,34,3,71,13,0,11,32,61,32,62,70,13,1,11,3,64,32,1,65,192,0,106,32,9,65,15,
      113,65,3,116,106,32,6,32,10,32,9,106,65,194,0,111,34,3,65,194,0,106,32,3,32,3,65,0,72,27,65,2,116,65,144,128,128,128,0,106,40,2,0,183,162,68,0,0,0,0,0,0,0,0,160,57,3,0,32,9,65,1,106,34,9,32,19,76,13,0,
      12,1,11,11,11,2,64,2,64,2,64,2,64,32,7,65,3,113,14,4,0,1,2,3,0,11,32,5,32,5,32,5,162,34,4,162,34,6,32,4,32,4,162,162,32,4,68,167,70,59,140,135,205,198,62,162,68,116,231,202,226,249,0,42,191,160,162,32,
      5,32,6,32,4,68,178,251,110,137,16,17,129,63,162,68,119,172,203,84,85,85,197,191,160,162,160,160,182,33,0,12,5,11,32,5,32,5,162,34,5,68,129,94,12,253,255,255,223,191,162,68,0,0,0,0,0,0,240,63,160,32,5,32,
      5,162,34,4,68,66,58,5,225,83,85,165,63,162,160,32,5,32,4,162,32,5,68,105,80,238,224,66,147,249,62,162,68,39,30,15,232,135,192,86,191,160,162,160,182,33,0,12,4,11,32,5,32,5,162,34,4,32,5,154,162,34,6,32,
      4,32,4,162,162,32,4,68,167,70,59,140,135,205,198,62,162,68,116,231,202,226,249,0,42,191,160,162,32,6,32,4,68,178,251,110,137,16,17,129,63,162,68,119,172,203,84,85,85,197,191,160,162,32,5,161,160,182,33,
      0,12,3,11,32,5,32,5,162,34,5,68,129,94,12,253,255,255,223,191,162,68,0,0,0,0,0,0,240,63,160,32,5,32,5,162,34,4,68,66,58,5,225,83,85,165,63,162,160,32,5,32,4,162,32,5,68,105,80,238,224,66,147,249,62,162,
      68,39,30,15,232,135,192,86,191,160,162,160,182,140,33,0,12,2,11,32,0,32,0,147,33,0,12,1,11,68,0,0,0,0,0,0,240,63,32,5,68,24,45,68,84,251,33,249,63,160,34,4,32,4,162,34,4,68,129,94,12,253,255,255,223,63,
      162,161,32,4,32,4,162,34,6,68,66,58,5,225,83,85,165,63,162,160,32,4,32,6,162,32,4,68,105,80,238,224,66,147,249,62,162,68,39,30,15,232,135,192,86,191,160,162,160,182,140,68,0,0,0,0,0,0,240,63,32,5,68,24,
      45,68,84,251,33,249,191,160,34,5,32,5,162,34,5,68,129,94,12,253,255,255,223,63,162,161,32,5,32,5,162,34,4,68,66,58,5,225,83,85,165,63,162,160,32,5,32,4,162,32,5,68,105,80,238,224,66,147,249,62,162,68,39,
      30,15,232,135,192,86,191,160,162,160,182,32,2,65,0,72,27,33,0,11,32,1,65,128,3,106,36,128,128,128,128,0,32,0,11,11,156,130,128,128,0,2,0,65,0,11,8,0,0,0,0,0,0,0,0,0,65,16,11,136,2,131,249,162,0,68,78,110,
      0,252,41,21,0,209,87,39,0,221,52,245,0,98,219,192,0,60,153,149,0,65,144,67,0,99,81,254,0,187,222,171,0,183,97,197,0,58,110,36,0,210,77,66,0,73,6,224,0,9,234,46,0,28,146,209,0,235,29,254,0,41,177,28,0,232,
      62,167,0,245,53,130,0,68,187,46,0,156,233,132,0,180,38,112,0,65,126,95,0,214,145,57,0,83,131,57,0,156,244,57,0,139,95,132,0,40,249,189,0,248,31,59,0,222,255,151,0,15,152,5,0,17,47,239,0,10,90,139,0,109,
      31,109,0,207,126,54,0,9,203,39,0,70,79,183,0,158,102,63,0,45,234,95,0,186,39,117,0,229,235,199,0,61,123,241,0,247,57,7,0,146,82,138,0,251,107,234,0,31,177,95,0,8,93,141,0,48,3,86,0,123,252,70,0,240,171,
      107,0,32,188,207,0,54,244,154,0,227,169,29,0,94,97,145,0,8,27,230,0,133,153,101,0,160,20,95,0,141,64,104,0,128,216,255,0,39,115,77,0,6,6,49,0,202,86,21,0,201,168,115,0,123,226,96,0,107,140,192,0,0,216,
      131,128,128,0,7,108,105,110,107,105,110,103,2,8,146,131,128,128,0,16,0,32,0,17,95,115,101,110,100,69,118,101,110,116,95,109,105,100,105,73,110,0,2,1,67,46,76,115,116,100,95,95,105,110,116,114,105,110,115,
      105,99,115,95,95,105,110,116,101,114,110,97,108,95,95,109,97,116,104,95,105,109,112,108,101,109,101,110,116,97,116,105,111,110,115,95,95,104,101,108,112,101,114,115,95,95,115,99,97,108,98,110,102,0,32,
      2,16,95,115,101,116,86,97,108,117,101,95,118,111,108,117,109,101,0,32,3,22,95,115,101,116,86,97,108,117,101,95,99,97,114,114,105,101,114,82,97,116,105,111,0,32,4,24,95,115,101,116,86,97,108,117,101,95,
      109,111,100,117,108,97,116,111,114,82,97,116,105,111,0,32,5,17,95,115,101,116,86,97,108,117,101,95,102,109,73,110,100,101,120,0,32,6,16,95,115,101,116,86,97,108,117,101,95,97,116,116,97,99,107,0,32,7,15,
      95,115,101,116,86,97,108,117,101,95,100,101,99,97,121,0,32,8,17,95,115,101,116,86,97,108,117,101,95,115,117,115,116,97,105,110,0,32,9,17,95,115,101,116,86,97,108,117,101,95,114,101,108,101,97,115,101,0,
      32,10,10,105,110,105,116,105,97,108,105,115,101,1,2,14,46,76,103,95,95,102,114,101,113,117,101,110,99,121,0,0,8,0,32,11,12,97,100,118,97,110,99,101,66,108,111,99,107,2,16,0,0,2,12,54,46,76,115,116,100,
      95,95,105,110,116,114,105,110,115,105,99,115,95,95,105,110,116,101,114,110,97,108,95,95,109,97,116,104,95,105,109,112,108,101,109,101,110,116,97,116,105,111,110,115,95,95,115,105,110,1,2,15,46,76,103,95,
      95,95,99,111,110,115,116,97,110,116,95,1,0,136,2,5,177,128,128,128,0,2,19,46,98,115,115,46,46,76,103,95,95,102,114,101,113,117,101,110,99,121,3,0,23,46,114,111,100,97,116,97,46,46,76,103,95,95,95,99,111,
      110,115,116,97,110,116,95,4,0,0,232,128,128,128,0,10,114,101,108,111,99,46,67,79,68,69,5,20,0,147,28,1,3,210,35,11,0,7,238,35,13,7,249,35,13,3,239,45,11,0,0,226,46,14,0,154,48,14,7,164,53,13,7,186,53,13,
      7,198,53,13,4,154,61,15,12,4,185,61,15,8,4,216,61,15,4,4,247,61,15,0,4,187,82,15,0,4,242,82,15,0,4,169,83,15,0,4,224,83,15,0,4,187,84,15,0,7,252,88,13,0,148,129,128,128,0,15,116,97,114,103,101,116,95,102,
      101,97,116,117,114,101,115,8,43,11,98,117,108,107,45,109,101,109,111,114,121,43,15,98,117,108,107,45,109,101,109,111,114,121,45,111,112,116,43,22,99,97,108,108,45,105,110,100,105,114,101,99,116,45,111,
      118,101,114,108,111,110,103,43,10,109,117,108,116,105,118,97,108,117,101,43,15,109,117,116,97,98,108,101,45,103,108,111,98,97,108,115,43,19,110,111,110,116,114,97,112,112,105,110,103,45,102,112,116,111,
      105,110,116,43,15,114,101,102,101,114,101,110,99,101,45,116,121,112,101,115,43,8,115,105,103,110,45,101,120,116,]);
  }
}
